### ISSUE TITLE
BuildDeployWindow: warning CS0162: Unreachable code detected 

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/HoloToolkit-Unity#101]
Assets/HoloToolkit/Build/Editor/BuildDeployWindow.cs(88,13): warning CS0162: Unreachable code detected

**Comment by jwittner** [comment]
Just make LocalIPsOnly non-const?

**Comment by riverar** [comment]
Great, now I made a mess with git's online editor and my attempted silent fix w/ rebase.
