### ISSUE TITLE
Ability to configure HoloLens IP address in the Build Window

### ISSUE THREAD

**Issue by robertlevy** [Microsoft/HoloToolkit-Unity#105]
The utilities in the Build Window seem to have a hardcoded 127.0.0.1 IP address that they use.  Need a way to specify the actual IP of my device.

**Comment by riverar** [comment]
This is for security reasons as it currently requires unencrypted HTTP communication to work, which isn't appropriate for anything other than localhost traffic. See https://github.com/Microsoft/HoloToolkit-Unity/pull/87 for more background.

**Comment by NeerajW** [comment]
@robertlevy appreciate the feedback. Is it ok to close your issue as a duplicate of #98?
