### ISSUE TITLE
Add UnityEvent support

### ISSUE THREAD

**Issue by stbertou** [Microsoft/HoloToolkit-Unity#107]
Hi guys

I think it would be really useful to make the HoloToolKit work nicely with Unity's Event system.
Basically invoking an event for when we gaze (OnGazeEnter / OnGazeLeave), when we select (OnSelectObject / OnClearSelection) etc..

I've prototyped it already, happy to put a PR if you also think that would be useful !

**Comment by stbertou** [comment]
`c#
public class OnGazeEnterEvent : MonoBehaviour
{
    public UnityEvent Event;
    public void OnGazeEnter()
    {
        if (Event != null)
        {
            Event.Invoke();
        }
    }
}
`

**Comment by stbertou** [comment]
I've prototyped, it works well and you can litterally do "anything" as you can now invoke an event from a gaze interaction
For the selection side, it looks like we have 2 similar-ish messages already : OnSelect and OnSelectObject
Any idea what the difference is ?

**Comment by Subere23** [comment]
That seems like a great idea

On Fri, Jul 8, 2016 at 7:54 AM, Stephane Bertout <notifications@github.com>
wrote:

> I've prototyped, it works well and you can litterally do "anything" as you
> can now invoke an event from a gaze interaction
> For the selection side, it looks like we have 2 similar-ish messages
> already : OnSelect and OnSelectObject
> Any idea what the difference is ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/HoloToolkit-Unity/issues/107#issuecomment-231351847>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AG3e5c-tZNNMSvKVORl__Bd4dGZbbu0Bks5qTkh5gaJpZM4JH07P>
> .
>



-- 
Jason Odom
*Thought Experiment*
205-223-1011
Jasonodom23@gmail.com

**Comment by NeerajW** [comment]
@stbertou sounds like a great idea and one step closer to moving towards more polymorphic code :)
How about you start with Gaze and OnSelect events?
The SelectObject events are for sending messages to focused objects which help tie them with keywords manager.

This is also a good opportunity to think through the event names :)

**Comment by stbertou** [comment]
Here you go: https://github.com/Microsoft/HoloToolkit-Unity/pull/109
