### ISSUE TITLE
Gazeable Canvas Button

### ISSUE THREAD

**Issue by stbertou** [Microsoft/HoloToolkit-Unity#113]
Hi guys

I've created a quite simple component that you can add to an existing Canvas Button (from Unity UI) and that makes it works nicely with gaze (similarly to how it works with mouse).
Was wondering if I could keep it in my local repo or make it available here.

Anyone interested ?
Happy to upload a PR so you can give it a try.

**Comment by robertlevy** [comment]
Yes please!  This is going to be a very common need in HL apps.

**Comment by jwittner** [comment]
I believe Unity is providing support for this, via addition of the HoloLens Input Module. It's currently available in the latest HTP previews. It's the HoloLens equivalent of the Standalone Input Module, which I believe is what handles mouse/touch for Canvas elements. This should make Canvas work without any additional components.

I'll dig into it a bit further.

**Comment by stbertou** [comment]
That would be even better indeed !

**Comment by jwittner** [comment]
Closing as supported by the platform via HoloLens Input Module. If there are issues with that implementation we can reopen this.

**Comment by stbertou** [comment]
So this was added to the lates beta from the unity side is that what you mean ?
