### ISSUE TITLE
Gazeable Color Picker

### ISSUE THREAD

**Issue by stbertou** [Microsoft/HoloToolkit-Unity#114]
Hey again

Another thing I would be keen to share..

I’ve implemented a Color picker that is HL friendly:
-	You can do “something“ with the currently gazed color
-	You can do “ something” with the current selected color (after you air tap)
The “something” is a UnityEvent so very flexible and you set it up straight from the inspector (no need to code anything).
Of course the color palette image itself can be changed.

Anyway let me know if you want me to put another PR for that.

**Comment by NeerajW** [comment]
@stbertou this is a good idea but feels more like an example/sample type thing rather than a reusable component in the HoloToolkit. 

I will keep this issue open so we can find a better story to host such examples. Will get back to you with some ideas.

**Comment by stbertou** [comment]
Happy to add it as an example so ppl can just grab it if they need it.
Up to you, I can also keep in our local repo, that's not a problem at all !

**Comment by jwittner** [comment]
How about an explicit Examples folder, i.e. Assets/HoloToolkit/Examples/<ExampleName>?

**Comment by NeerajW** [comment]
Actually I don't think we need to have the Examples folder inside the Assets folder.
This will unnecessarily increase the Unity packages being produced using Assets.

Perhaps it should be a the root level.

**Comment by jwittner** [comment]
If we pull them out, I don't think we'll be able to include them in the .unitypackage if we ever publish one.  When importing unity packages, it's pretty easy to uncheck the whole Example folder and avoid importing it into one's project. I've seen lots of packages organized this way, and it's really nice to be able to add the examples when you're first learning a package.

**Comment by jwittner** [comment]
I'm seeing 7.71 MB off of master right now.

**Comment by jwittner** [comment]
Now that we've got an examples folder - #128, do we believe this belongs there?

**Comment by stbertou** [comment]
Happy to move it there, let me know what you think guys.

**Comment by NeerajW** [comment]
@stbertou we have a HoloToolkit-Examples folder now :)

**Comment by stbertou** [comment]
ah ah yeah I've noticed ;-)

**Comment by stbertou** [comment]
OK it's live now => https://github.com/Microsoft/HoloToolkit-Unity/pull/164

**Comment by jwittner** [comment]
PR was merged.
