### ISSUE TITLE
Can't get stencil buffers to behave

### ISSUE THREAD

**Issue by Polyrhythm** [Microsoft/HoloToolkit-Unity#121]
I'm trying to make a "portal" in my application. I'm using two shaders - one that is for hidden objects visible only through the portal, and one is for the portal itself.

Hidden shader:
```
 Stencil {
   Ref 1
   Comp Equal
 }
```

Portal shader:
```
 ZWrite Off
 ColorMask 0
     
 Pass {
     Stencil {
         Ref 1
         Comp always
         Pass replace
     }
 }
```

This works perfectly in the Unity editor but I can't get it to work in the Hololens. I've tried a mish-mash of solutions to no avail - even tried it on a bare Unity app with just the Holotoolkit assets. What am I missing? When running this on the device, everything just renders normally.

**Comment by NeerajW** [comment]
Interesting. Have you tried looking at the [WindowOcclusion ](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Shaders/WindowOcclusion.shader)shader in the HoloToolkit?

**Comment by jwittner** [comment]
I would definitely reach out here too: http://forums.hololens.com/

**Comment by Polyrhythm** [comment]
@NeerajW Thanks for your suggestion. I have looked at that but concluded that it wouldn't help me because I'm trying to hide an entire scene from the player view, not something that can easily be encapsulated in a cube with the occlusion material attached.

@jwittner I suppose this issue is more of a general Hololens issue than something to do with the Holotoolkit, and have posted my question on the Hololens forums as per your suggestion. I'll close this and leave my question in the forum.

**Comment by SimonStHilaire** [comment]
Hi know this us an old and closed Issue but since I just bumped into this problem myself and I see no answer anywhere, I though I might add one: the stencil buffer is not created when configuring the depth buffer at 16bits precision like suggested. 24bits must be selected for it to work.

**Comment by Patsu4Cad** [comment]
> Hi know this us an old and closed Issue but since I just bumped into this problem myself and I see no answer anywhere, I though I might add one: the stencil buffer is not created when configuring the depth buffer at 16bits precision like suggested. 24bits must be selected for it to work.

Thanks you so much ! I had thought about it but not tested it.

**Comment by SashelI** [comment]
> Hi know this us an old and closed Issue but since I just bumped into this problem myself and I see no answer anywhere, I though I might add one: the stencil buffer is not created when configuring the depth buffer at 16bits precision like suggested. 24bits must be selected for it to work.

Hi,
I am getting mad on this : how (or where) do you change this depth buffer size ?? I can't find any parameter that allows me to select a 24bits buffer.
Thanks
