### ISSUE TITLE
Feature: Add Maniupulation gesture support to move holograms smoothly

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/HoloToolkit-Unity#123]
**Scenario:** 
The Holograms 211 course provides a basic implementation of the manipulation events. 
This update will help add a more smooth and sophisticated approach to moving holograms where the user wants then to be. 
Developers should be simply able to add this to the hologram in their app which they want to move.

**Proposed change:**
1. Update GestureManager.cs to support manipulation gestures
2. Add another script that consumes the manipulation data to help move holograms.

**Comment by micthom-msft** [comment]
I'm working on this now.  Will have a PR out before the end of the week.

**Comment by NeerajW** [comment]
@micthom-msft thanks so much! Looking forward to it.

**Comment by micthom-msft** [comment]
@NeerajW This was resolved with 3549fa022a51e87bb9be8f430461f9f53f1549bc.  Unfortunately I didn't use the magic words in the commit message but this should probably be closed.
