### ISSUE TITLE
Add persistence WorldAnchor component to objects when placing them in the world

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/HoloToolkit-Unity#129]
HoloToolkit has TapToPlace which helps in placing objects on real world surfaces.
We should be world anchoring them when they are placed so persistence works.

**Comment by aaronsnoswell** [comment]
Hi @NeerajW - Are you saying that we need a way to make WorldAnchors persist across application re-starts? If, so I'm currently trying to solve this problem - e.g. see [this post](http://forum.unity3d.com/threads/persist-hologram-locations-after-game-restart.417259/) on the Unity forums. My apologies if this is not what you are referring to.

**Comment by jwittner** [comment]
@aaronsnoswell Checkout the WorldAnchorStore available in UnityEngine.VR.WSA.Persistence.

If you haven't yet, I'd strongly recommend installing the offline Unity Documentation available here: http://unity3d.com/partners/windows/hololens, it contains lots of documentation on the HoloLens that is only available there - the online 5.4 docs don't have WorldAnchorStore for example, but the offline for the HoloLens Technical Preview does.

**Comment by NeerajW** [comment]
@aaronsnoswell adding WorldAnchor component to holograms surely will help with hologram stability because you can sign up for tracking lost events.
Using the WorldAnchorStore you can save these world anchors by name to the local HoloLens anchor store and retrieve them when the app restarts. Very similar to how ImportExportAnchorManager.cs does.

I hope to add both these capabilities.

**Comment by aaronsnoswell** [comment]
Thanks Josh, I wasn't aware of WorldAnchorStore.

**Comment by jwittner** [comment]
@NeerajW Assuming this is closed now by your merged PR?

**Comment by jwittner** [comment]
Closing due to merged PR - @NeerajW  please reopen if that isn't the case.

**Comment by HjoshM** [comment]
@NeerajW Hi, Neither of the two links you have provided works. Would you be so kind to edit your answer with updated links? Many thanks

**Comment by jessemcculloch** [comment]
@HjoshM - I have updated links as closely as possible
