### ISSUE TITLE
BuildWindow doesn't work for me

### ISSUE THREAD

**Issue by aaronsnoswell** [Microsoft/HoloToolkit-Unity#131]
I don't know if the BuildWindow is stable yet but I haven't been able to get it to work.

I'm using Unity HoloLens 5.4.0b24-HTP (64-bit), Visual Studio 2015 Professional with Update 3 that came out a few weeks ago, and the latest HoloTooklkit as of the time of writing (commit 117f8c5d344ddaf2314012ddb7602a2078b9ce0d, 2 days ago).

I've exported the HoloToolkit as a Unity package, then re-imported it into my new HoloLens project. When I manually build my VS2015 solution, then build and deploy, my app works fine. When I use the HoloToolkit 'Build Window' to try and build the SLN, APPX and deploy, msbuild will run in the console that pops up for a few minutes, then I get errors in the Unity status bar down the bottom of the Unity editor. E.g. in the screenshot you can see a "System.NUllReferenceException: Object reference not set to an instance of an object", although sometimes I see other errors.

![Screenshot of error](http://i.imgur.com/zacTpqs.png)

Does anyone know if the HoloToolkit build window is functional at this point in time? If it is, can I help write some documentation about how to use it correctly? I haven't been able to figure it out yet.

This is a re-post of [this Unity HoloLens forum topic](http://forum.unity3d.com/threads/holotoolkit-build-window-doesnt-work.417213). This bug post is possibly related: https://github.com/Microsoft/HoloToolkit-Unity/issues/98

**Comment by riverar** [comment]
Hey there @aaronsnoswell, this feature works but may be a little rough around the edges. Are you using the latest from this repository? Can you click **Open SLN** and build from that Visual Studio instance? I found a one-time open of that solution to change it from _Any CPU_ to _x86_ is required before things start working correctly.

**Comment by jwittner** [comment]
@riverar The one time change to x86 strikes me as really odd. Looking at the MSBuild command we are explicitly trying to specify x86.

@aaronsnoswell If you could try the steps one at a time and let us know which one is failing that would help us narrow in.

Thanks!

**Comment by jwittner** [comment]
@aaronsnoswell Also, if could find that error in your console, we might be able to get a line number, which would really help! =)

**Comment by aaronsnoswell** [comment]
Hi folks. I'm a away for a few days but will give both your points a shot
when I get back. Watch this space.

**Comment by jwittner** [comment]
@aaronsnoswell There have been several fixes since you opened this bug. Please let us know if you're still seeing problems. =)

**Comment by aaronsnoswell** [comment]
Hi :) I don't have time to test at my end right now. Please close the issue
and I'll re-open if I am still seeing it in the future :) Cheers!
