### ISSUE TITLE
URL in comment is out of date

### ISSUE THREAD

**Issue by nuernber** [Microsoft/HoloToolkit-Unity#132]
The url at https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/SpatialMapping/Shaders/Wireframe.shader#L35 no longer is valid. You can still access an archive version here: http://wayback.archive.org/web/20140213062544/http://cgg-journal.com/2008-2/06/index.html. I'm not sure if there's a better archive version or not; the link I just gave has missing pictures.

**Comment by NeerajW** [comment]
@nuernber would you like to make the fix :)
