### ISSUE TITLE
clicking Launch Sharing service does nothing

### ISSUE THREAD

**Issue by jacksro** [Microsoft/HoloToolkit-Unity#135]
clicking the menu button for launching the shared service doesn't do anything,

**Comment by NeerajW** [comment]
Are you sure you have copied all the binaries? The SharingService.exe is under the Externals folder.

**Comment by jwittner** [comment]
Tested on master, SessionServer was successfully launched. Closing unless we get a fuller repro.

**Comment by jwittner** [comment]
Ok, I'm seeing this now. The menu item breaks when embedding the Assets/HoloToolkit folder into a new project. It makes assumptions about the existence of the "External" folder and the location of the SharingService executable.

**Comment by NeerajW** [comment]
Perhaps we add a check or Debug.LogError for better discoverability?

**Comment by jwittner** [comment]
Definitely should be logging an error. We should update the integration instructions to include copying the External directory to the right place too.

**Comment by stbertou** [comment]
Hey guys, are you meant to compile SharingService.exe ourselves or it should be part of this repo?
Also +1 for LogError in case the file isn't there ! Specially when you have no idea what to expect.

**Comment by jwittner** [comment]
@stbertou It's already a part of the repo - https://github.com/Microsoft/HoloToolkit-Unity/blob/master/External/HoloToolkit/Sharing/Server/SharingService.exe

**Comment by stbertou** [comment]
Indeed ! My bad I was looking into the Assets folder in fact ! (I do have an External foldere but in Assets hence why I was confused)
OK all good and that makes way more sense now! 
Thanks for checking Josh!
Having said that.. it's quite possible that we all have a different way of storing "external" projects, what about using a environment variable (or something else) so we can all decide where to store those executables without breaking the HolotoolKit unity editor tools.
Any thoughts on this?

**Comment by NeerajW** [comment]
@stbertou part of the trouble is these binaries don't need to be part of the unity packages. So even if devs download those, they stand the chance of missing these binaries. We could make it work with environment variables though to give more flexibility.

**Comment by jwittner** [comment]
@NeerajW @stbertou Not a bad idea to allow customization! I think we should put the executables required by the scripts into the Unity Package. Otherwise confusion will occur.

**Comment by jwittner** [comment]
Fixed by #160
