### ISSUE TITLE
GazeManager logs error messages for objects lacking OnGazeEnter / OnGazeLeave

### ISSUE THREAD

**Issue by pnolen** [Microsoft/HoloToolkit-Unity#14]
Unity will spam the console error log with the text "SendMessage OnGazeEnter has no receiver!" if no method for OnGazeEnter or OnGazeLeave has been created for the object. This can be mitigated by using the SendMessageOptions.DontRequireReceiver option as the second parameter to the SendMessage method on the GameObject.

**Comment by NeerajW** [comment]
@pnolen thank you for filing.
@dotMorten thank you for fixing. Merged into master.
