### ISSUE TITLE
Inconsistencies Between Hologram 230 and This Repo

### ISSUE THREAD

**Issue by deriven** [Microsoft/HoloToolkit-Unity#144]
Specifically...
HoloToolkit\SpatialMapping\Scripts\
SpatialMappingObserver.cs
SpatialMappingManager.cs

I compared the two and found vast differences.  Being as Hologram 230 works well, I tried to pull just those scripts from the 230 tutorial into the Holotoolkit.  No luck though.  Even though no errors were found in the scripts, Unity's Inspector claims that the scripts "can not be loaded. Please fix any compile errors and assign a valid script."

As soon as I copied/pasted the entire set of scripts from the 230 tutorials HoloToolkit\SpatialMapping\Scripts folder, all was well.

This has me to believe that the Hologram 230 tutorial one or more of these:
a) has a better implementation
b) has a specific implementation that is incompatible with the newest toolkit
c) has a completely different repo of its toolkit

I believe the community would benefit from a single repo rather than picking and choosing.  In other words, I believe the community would much like to go to the tutorials with the _understanding_ that the toolkit utilized is consistent with the toolkit on GitHub.

Lastly, I did a search on this repo and commits for ObjectSurfaceObserver (which exists in the 230 tutorial).  Not found.  Therefore I do believe two or more toolkit repos are in play here.

**Comment by riverar** [comment]
Yep, I believe this is just a wart that should get resolved soon. See #39.

**Comment by angelaHillier** [comment]
There will always be some inconsistencies between the toolkit and the course, but this particular one should be going away soon.

**Comment by deriven** [comment]
I assume they will be out of sync because (over time) the course will have older code.  Currently Hologram 230 and other courses have -- in some ways -- better solutions than this repo.  However this GitHub repo's wiki [states](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/GettingStarted.md):

> We'll build the HoloToolkit from source since it's a reasonable assumption that you want the latest and greatest if you are reading this document.

That's what confused me here.  It's not that they are out of sync.  It's that the coursework has some very nice extras in its HoloToolkit folder and I thought it was using this repo as a starting point (which it wasn't) .. or vice versa at the very least.

Hmm .. maybe it would be easier to rename the HoloToolkit folder in the courses to something else.  That would resolve this issue quite quickly.

Pardon my rambling.

**Comment by angelaHillier** [comment]
So far, we've been trying out new stuff in our courses first. Then, if we decide that they're a good fit for the toolkit, we move it over. I've been meaning to move the ObjectSurfaceObserver over to the HoloToolkit for a while, as we have found it much easier to use then the remote mapping components.

The HoloToolkit is quickly expanding with community contributions. Some of the improvements are not necessary to take for the courses, which need to be kept simple and teachable, so there will be more drift as time progresses.

Agreed, renaming the course folders would be a good idea. At least that way we would know what 'HoloToolkit' people are using, since many developers use one of the courses to jump-start their project.

**Comment by deriven** [comment]
Well I cannot thank you enough for the kit and examples.  Makes our projects feasible.

**Comment by robertlevy** [comment]
With the courses and the toolkit diverging, it's a pretty bumpy ride to "graduate" from the courses and start building real apps with the toolkit.  Assuming graduation is the goal, it would be extremely helpful if these things did not diverge.

Some ideas to consider:

* adding the course content to this repo so the community can help keep them in sync
* building the course sample code as forks of this repo so it's easier to keep them in sync
* placing the course sample code in the /examples directory of this repo
* tagging each course with the version or commit hash of the toolkit it uses

**Comment by jwittner** [comment]
Was this fixed by #151?
