### ISSUE TITLE
Currently no way to push builds to the HoloLens Emulator from Unity.

### ISSUE THREAD

**Issue by jwittner** [Microsoft/HoloToolkit-Unity#149]
Having the Build Window is really great for testing on device, but for living with the emulator the process is still lacking. I'm envisioning the ability to install to the emulator from the Build Window, but I'm not sure if that's possible outside of Visual Studio.

**Comment by riverar** [comment]
Definitely possible, just need to build a few extra smarts to detect the correct interface for the Dev Portal.

**Comment by jwittner** [comment]
@jevertt Any idea how to go about this?

**Comment by jevertt** [comment]
No, sorry, never tried it. Love to see an option for this, though.

**Comment by riverar** [comment]
I wrote all the plumbing needed for emulator discovery, just need to wire it up into Unity now. This OnGui is terrible to work with.
