### ISSUE TITLE
Rename "ploygon" to "polygon"

### ISSUE THREAD

**Issue by richiecarmichael** [Microsoft/HoloToolkit-Unity#152]
Typo in [IPloygonClosable ](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/GazeRuler/Scripts/IPloygonClosable.cs)interface.

**Comment by NeerajW** [comment]
@ChangweiZhang please fix this issue by renaming the interface to the proper spelling.
@richiecarmichael thank you for filing the issue.

**Comment by NeerajW** [comment]
@ChangweiZhang do you have any updates on this?

**Comment by stbertou** [comment]
Funny how the type was duplicated everywhere (see PloygonManager in the GazeRuler example) :-)
