### ISSUE TITLE
GazeRuler: Unused variable warning

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/HoloToolkit-Unity#153]
Assets/HoloToolkit-Examples/GazeRuler/Scripts/Test/LineTest.cs(15,18): warning CS0414: The private field `LineTest.created' is assigned but its value is never used

Please fix this issue by deleting the unused variable.

**Comment by ChangweiZhang** [comment]
I have deleted the unused variable and fix the issue. New pull request was cretaed.

**Comment by NeerajW** [comment]
Thanks for the fix. Merged.
