### ISSUE TITLE
"Couldn't decompress package" error when importing

### ISSUE THREAD

**Issue by anandx** [Microsoft/HoloToolkit-Unity#157]
I have cloned and successfully built HoloToolkit-Unity.  However, when I try to do Assets -> Import Package -> Custom Package… I get the following error:  

`Failed to import package with error: Couldn't decompress package
`

I've rebuilt it twice.  I've also tried moving it to various places on my hard disk with no luck.  Any ideas whats up?  Here's a [link to the package file](https://www.dropbox.com/s/drvu2hd6intf3ki/HoloToolkit-Unity.unitypackage?dl=0) it produced.

**Comment by NeerajW** [comment]
@anandx how did you create your unity package?

**Comment by NeerajW** [comment]
I just tried the following and it worked:

1. Opened the cloned HoloToolkit-Unity in Unity
2. Right click on Assets > Export package
3. Give it a name and export
4. Used a different Test project
5. Right click on Assets > Import Package > Custom Package
6. Selected the previously created package > Open
7. Clicked Import in the Import dialog box.
8. Everything worked.

I suspect something was created incorrectly in your unity package.

**Comment by anandx** [comment]
Hmm... I am using those exact steps but at step 6 I get the compression
error. I have retried this process 3x including fresh clone from git.

Might be a broader Unity related error? I'm fairly new to Unity, wonder if
anyone has suggestions of what to try?

**Comment by jwittner** [comment]
What version of Unity are you using?

**Comment by anandx** [comment]
I'm using the latest, Unity HTP 5.4.0f1  :/  

Would love any ideas/suggestions

**Comment by angelaHillier** [comment]
You might want to try a more selective export. Instead of exporting everything, limit it to just the features that you need in your app. Or, go folder by folder, to see if there is one particular feature set (like 'Spatial Mapping' or 'Sharing') that could be causing the error.

**Comment by anandx** [comment]
I was using Boot Camp on a mac laptop and the problems went away when I booted natively into Windows and did a fresh rebuild :stuck_out_tongue_closed_eyes:
