### ISSUE TITLE
SpatialMappingManager: change "drawVisualMeshes" to "drawSurface"

### ISSUE THREAD

**Issue by richiecarmichael** [Microsoft/HoloToolkit-Unity#162]
I think it makes more sense to have surfaceMaterial/**drawSurface** property pairing rather than surfaceMaterial/drawVisualMeshes.

**Comment by angelaHillier** [comment]
While I agree that 'drawSurface' would be a better name, if we change the name, it would be a 'breaking change' that will require anyone setting this property in code to fix their code. Devs would have to double-check that their prefab settings are still correct after updating to the latest HoloToolkit. Changing public properties has the potential of causing regressions for other developers, so we should be careful about doing so.

**Comment by jwittner** [comment]
Well, he could use the FormerlySerializedAsAttribute to markup the new property without breaking anything.

https://docs.unity3d.com/ScriptReference/Serialization.FormerlySerializedAsAttribute.html

**Comment by jwittner** [comment]
@richiecarmichael you want to make this change?

**Comment by jwittner** [comment]
@richiecarmichael Any chance you'll do this?

**Comment by jwittner** [comment]
Closing as won't fix.
