### ISSUE TITLE
Large NetworkOutMessages leak?

### ISSUE THREAD

**Issue by mfrenkie** [Microsoft/HoloToolkit-Unity#163]
Hi all,
   If I create large NetworkOutMessage objects and then run the script in Unity, Unity quickly eats all of my available RAM and ultimately crashes. For example:

    public void SendDepthData(ushort[] depthData)
    {
        if (this.serverConnection != null && this.serverConnection.IsConnected())
        {
            NetworkOutMessage msg = CreateMessage((byte)TestMessageID.HeadTransform);
            int totalLength = depthData.Length;
            for (int x = 0; x < totalLength; x++)
            {
               msg.Write(depthData[x]);
            }
            this.serverConnection.Broadcast(
                msg,
                MessagePriority.Immediate,
                MessageReliability.UnreliableSequenced,
                MessageChannel.Avatar);

        }
    }

If I comment out msg.Write(depthData[x]); it resolves the issue. If I replace it with msg.Write(999); the issue persists. I know large messages are suboptimal but this is preventing me from optimizing things. 

Also of note, adding msg.Destroy(); after broadcasting has no effect.

Any thoughts?

**Comment by jwittner** [comment]
Any chance you would create a small project with a scene that repros this?

**Comment by jwittner** [comment]
Without further information we can't really dig into this.
