### ISSUE TITLE
Consider adding TapToPlaceParent like functionality

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/HoloToolkit-Unity#17]
**Scenario:**

Adam is a developer who wants an easy way to move his objects around. Place them where they matter to him.
He wants a quick way to tap on an object, gaze at a different location and then tap again to place the object at that location.

**Proposed Solution:**

Add a new script called TapToPlaceParent or something similar to either the Input or Utilities folder.

**Comment by DanTDMMcpe** [comment]
yeah i would like it too.

**Comment by NeerajW** [comment]
@jochao is working on a simple TapToPlaceOnSurface script which will help place an object on a real world surface.

This can be extended to make work for other scenarios which are specific to your applications.
