### ISSUE TITLE
Is it possible to prepare a unity-package of this toolkit?

### ISSUE THREAD

**Issue by matatabi-ux** [Microsoft/HoloToolkit-Unity#171]
Great toolkit!

But I hope to import this toolkit to my project more easily.
Is it possible to prepare a unity-package of this toolkit?

Double-clicking a unity-package file, UnityEditor import this package automatically.

Unity Manual - Exporting Packages
https://docs.unity3d.com/Manual/HOWTO-exportpackage.html

**Comment by NeerajW** [comment]
Yes. Please follow the steps in GettingStarted.md.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Sat, Aug 13, 2016 at 3:13 AM -0700, "matatabi-ux" <notifications@github.com<mailto:notifications@github.com>> wrote:


Great toolkit!

But I hope to import this toolkit to my project more easily.
Is it possible to prepare a unity-package of this toolkit?

Double-clicking a unity-package file, UnityEditor import this package automatically.

Unity Manual - Exporting Packages
https://docs.unity3d.com/Manual/HOWTO-exportpackage.html

-

**Comment by riverar** [comment]
You can also download the latest up-to-date package from https://riverar.github.io/HoloToolkit-Unity-Builds/ (my personal little project, no guarantees right now)

**Comment by NeerajW** [comment]
@matatabi-ux did this help answer your question? Is it ok to close this issue?
