### ISSUE TITLE
Implement AutoDiscovery for Sharing 

### ISSUE THREAD

**Issue by alexdrenea** [Microsoft/HoloToolkit-Unity#172]
Create a new script that is able to auto discover the server in a shared experience using the autodiscovery feature in the SharingClient.dll.

**Comment by alexdrenea** [comment]
@NeerajW  I noticed some issues when trying to implement the autodiscover script separately from the sharing stage - All the other helpers (session tracker, auto join session, direct pairing), depend on the sharingstage instance.

**Comment by alexdrenea** [comment]
Based on my previous comment I updated the SharingStage with autodiscover functionality instead of creating a new script. I also updated some of the other scripts to ensure they are not dependent on connection times (ImportExportAnchorManager and CustomMessages). You can check the changes in my fork on [this commit](https://github.com/Microsoft/HoloToolkit-Unity/commit/4b54da742821f9614b81d0a320c03ca96a9a1e4a). Let me know if you want me to get a PR in.

I also created a [prefab](https://github.com/Microsoft/HoloToolkit-Unity/commit/e9f47d05139e8651b54596be369e35327a45b27c) for development mode to show the status of the connection (Disconnected, Connecting, Connected to). With some effort, I suppose we could make it Production ready - maybe I should open a new issue for that?

**Comment by jwittner** [comment]
Can you make a PR for the first bit? It'll be easier to compare that way. =)

The prefab sounds useful to me too!

**Comment by alexdrenea** [comment]
I broke the 2 features in separate branches / PRs. Submitting them now.

**Comment by NeerajW** [comment]
Will take a look. Thanks!
