### ISSUE TITLE
Build Window - Add field for WSATestCertificate.pfx password

### ISSUE THREAD

**Issue by twoopy** [Microsoft/HoloToolkit-Unity#189]
If one changes the WSATestCertificate.pfx via the 'Create' button in Project Settings > Player > Setting for Windows Store > Publishing Settings > Certificate then 'Build APPX from SLN' will fail if the certificate is secured with a password.

If the password is removed via the same 'Create button' procedure mentioned above the Build Window correctly builds the SLN, APPX & Installs using the newly created pfx.

Suggested solution is to add a field in the APPX section for the 'WSATestCertificate.pfx' password and to pass the password to MSBuild.

The error message is: C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1930,5): warning APPX0105: Cannot import the key file 'WSATestCertificate.pfx'. The key file may be password protected. To correct this, try to import the certificate manually into the current user's personal certificate store...

Additional Info: I did add the certificate to my personal certificate store. It was only then that I was able to build the APPX and deploy from Visual Studio.

**Comment by StephenHodgson** [comment]
Unity doesn't provide a way to create new certificates but through the player settings window, but we can select an existing one and input the password.
