### ISSUE TITLE
Apply HoloLens Scene Settings

### ISSUE THREAD

**Issue by julespong** [Microsoft/HoloToolkit-Unity#190]
Is the change from a 60 degree FOV to 16 degree FOV intentional?

**Comment by julespong** [comment]
After investigating the change I see it was initially set to 19 to match the HL. So, why 16?

**Comment by angelaHillier** [comment]
Yes, this change was intentional. It only changes the camera when using the Unity Editor. The emulator and HoloLens will override with their own settings. See this thread for details:
https://github.com/Microsoft/HoloToolkit-Unity/issues/176

**Comment by julespong** [comment]
Thanks for the explanation, makes sense.
