### ISSUE TITLE
Spatial Understanding Room Size Limitations

### ISSUE THREAD

**Issue by JeffPack** [Microsoft/HoloToolkit-Unity#193]
I noticed that I could not scan my entire basement. I am assuming this has to do with the vertex limit per mesh. Will there be any support in the future for making multiple meshes, and making them "watertight"?

**Comment by HodgsonSDAS** [comment]
Was this closed by https://github.com/Microsoft/HoloToolkit-Unity/pull/245?

**Comment by HodgsonSDAS** [comment]
@JeffPack did https://github.com/Microsoft/HoloToolkit-Unity/pull/245 fix your issue?
