### ISSUE TITLE
Spatial Understanding: MainCamera is missing some script references

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/HoloToolkit-Unity#195]
![image](https://cloud.githubusercontent.com/assets/13281538/18101588/2bfd301a-6ea4-11e6-88e5-5a399fe77908.png)

HoloToolkit-Examples\SpatialUnderstanding\SpatialUnderstanding-FeatureOverview\Scenes\Main

**Comment by NeerajW** [comment]
Also fix misc issues like:
1. Unused variable stats in AppState.cs
2. README location under SpatialUnderstanding-FeatureOverview folder to match other examples.

**Comment by HodgsonSDAS** [comment]
@NeerajW is this still open?
