### ISSUE TITLE
Sorry,but maybe there's a small error on  HoloToolkit-Unity/Assets/HoloToolkit/Input/Scripts/BasicCursor.cs 

### ISSUE THREAD

**Issue by zwxbest** [Microsoft/HoloToolkit-Unity#197]
At the 33 line.
` if ((GazeManager.Instance.RaycastLayerMask & this.gameObject.layer) == 0)
          `
I think judge whether a layer in the layerMask,probably use
` if ((GazeManager.Instance.RaycastLayerMask & (1<< this.gameObject.layer)) != 0)
        `

**Comment by jwittner** [comment]
Wanna make the change and submit a PR?
