### ISSUE TITLE
Manipulate gesture events do not trigger with Spatial Understanding active

### ISSUE THREAD

**Issue by acylum** [Microsoft/HoloToolkit-Unity#198]
I tried to use manipulate gesture while using the spatial understanding module, but none of the manipulate gestures seem to fire, however, when I deactivate the spatial understanding scripts, manipulation gesture events trigger as expected.

**Comment by izatar** [comment]
I am seeing gestures are difficult to trigger while the scanner is running.
I wildly speculate this is related to bug #194 , the shader may be bogging down the recognizer.

**Comment by NeerajW** [comment]
I see the FPS certainly drops to about 30 - 35 FPS during the scan phase but I did not have trouble air tapping. I have not tried manipulation yet though.

**Comment by acylum** [comment]
More information:: Scripts attached to the main camera that have manipulation events will not trigger.  However, if you move either the script or just the manipulation events off of the main camera to another gameObject,etc,.., then the manipulation events will trigger as expected.

**Comment by HodgsonSDAS** [comment]
@acylum is this still an issue?

**Comment by HodgsonSDAS** [comment]
@acylum is this still an issue now that we're using the new input methods?

**Comment by HodgsonSDAS** [comment]
I'm going to close this because there's a new input system.  Please reopen if issue still persists..
