### ISSUE TITLE
Spatial Understanding in the Emulator

### ISSUE THREAD

**Issue by carter-james89** [Microsoft/HoloToolkit-Unity#199]
I can't seem to get the Spacial Understanding scene or components to work in the emulator.  Is this just me?

**Comment by jwittner** [comment]
@jevertt Any idea if this should work in the emulator or not? Thanks!

**Comment by jevertt** [comment]
I don't see any reason why it wouldn't, but I haven't tried it. @carter-james89 - I'd check that spatial mapping is working correctly for you (if you are using the provided unity sample for spatial understanding, you could also try just defaulting on the "draw meshes" checkbox on the spatial mapping prefab).

**Comment by jessemcculloch** [comment]
@jevertt - I can confirm that the Spatial Understanding does not seem to work in the Emulator, even when spatial mapping is active and working.  I wasn't able to determine where it's failing, but I did notice it is finding the planes and adding them to the array, but there is no rendering happening.

**Comment by kaiomagalhaes** [comment]
Facing the exactly same issue here @jessemcculloch

**Comment by darax** [comment]
I think I have this.  Cleaning up the change.

**Comment by darax** [comment]
Possible fix: https://github.com/Microsoft/HoloToolkit-Unity/pull/297

**Comment by NayanPerron** [comment]
I try to use the spatial understanding in my emulator, but i see nothing. I see my spacial mapping, but the spacial understanding  don't seem to work.

Emulator: 10.0.14393.1358
Unity: 2017.4.0f1
HoloToolkit: 2017.2.1.4
