### ISSUE TITLE
SpatialUnderstanding sometimes creates meshes that are too large for Unity

### ISSUE THREAD

**Issue by izatar** [Microsoft/HoloToolkit-Unity#200]
I am occasionally (1 out of 5 or so scans) getting these errors after finalizing a scan of my living room:

    Mesh.vertices is too large. A mesh may not have more than 65000 vertices. 
    (Filename: C:\buildslave\unity\build\Runtime/Graphics/Mesh/Mesh.cpp Line: 814)
    Mesh.normals is out of bounds. The supplied array needs to be the same size as the Mesh.vertices array. 
    (Filename: C:\buildslave\unity\build\Runtime/Graphics/Mesh/Mesh.cpp Line: 866)
    Failed setting triangles. Some indices are referencing out of bounds vertices. IndexCount: 398433, VertexCount: 0

**Comment by izatar** [comment]
I can't be the only one who is seeing this?   I think this is a major issue since it might make apps fail to pass the Windows Store smoke test.

**Comment by izatar** [comment]
I have tracked down the error in the code to "SpatialUnderstandingCustomMesh.cs" in function "Import_UnderstandingMesh".  The mesh passed from the DLL is not sanity checked for size, and instead is passed on to Unity to choke on.

The right solution involves cutting up the mesh into multiple meshes.

But, for my own purposes, I just put in a hack to limit size of the meshVertices, meshNormals,and meshIndices arrays and also go through the indices to make sure no indice is out of range.  This is not great, but it is much better than having Unity throw and mesh go dark.

```
  // Create output mesh
                if ((meshVertices != null) &&
                    (meshVertices.Length > 0) &&
                    (meshIndices != null) &&
                    (meshIndices.Length > 0))
                {
                    if (customMesh != null)
                    {
                        Destroy(customMesh);
                    }
                    bool gottahack = false;
                    if (meshVertices.Length > 65532)
                    {
                        gottahack = true;
                        Debug.Log(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>vertCount adjusted from" + meshVertices.Length + "to 65534 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
                        Vector3[] temp = new Vector3[65532];
                        Array.Copy(meshVertices,temp, 65532);
                        meshVertices = temp;

                        Vector3[] temp2 = new Vector3[65532];
                        Array.Copy(meshNormals, temp2, 65532);
                        meshNormals = temp;
                    }
                  
                    if (meshIndices.Length > 65532 * 3)
                    {
                        Debug.Log(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>idxCount adjusted from" + meshIndices.Length + "to " + 65532 * 3 + " <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
                        int[] temp = new int[65532*3];
                        Array.Copy(meshIndices, temp, 65532*3);
                        meshIndices = temp;
                    }

                    if (gottahack)
                        for (int i = 0; i < meshIndices.Length; i++)
                        {
                            if (meshIndices[i] > 65531)
                            {
                                meshIndices[i] = 65531;
                            }
                        }
                    customMesh = new Mesh
                    {
                        vertices = meshVertices,
                        normals = meshNormals,
                        triangles = meshIndices
                    };
                    GameObject spatialMesh = AddSurfaceObject(customMesh, string.Format("SurfaceUnderstanding Mesh-{0}", transform.childCount), transform);
                    spatialMesh.AddComponent<UnityEngine.VR.WSA.WorldAnchor>();
                }

```

**Comment by jwittner** [comment]
Nice find @izatar, hopefuly we can get a more thorough fix in soon!

**Comment by darax** [comment]
out of curiosity, did #245 address this?  I think the change should make the situation very unlikely to occur.

**Comment by izatar** [comment]
Since the meshes are cut down so much smaller, this problem is much less likely to occur as you say.

It is up to you to decide if "unlikely" is good enough.  I think it ought to be easy enough to guarantee this doesnt happen though, even if it just stops adding triangles to a sector mesh if it gets too large.  It might never happen, but if it does happen, it will be when Nadella is doing a live demo, guaranteed.

**Comment by darax** [comment]
:) fair point, I've added a check that will discard excess triangles and log a warning.  I also reviewed the native code of the plugin and it looks to create up to ~2000 voxels per cubic meter.  I think that makes the degenerate case where every other voxel is filled (~250 voxels) and makes a complete cube (24 verts/cube) at a max of ~6k verts.
