### ISSUE TITLE
SpatialUnderstanding.cs throws warning about unreachable code

### ISSUE THREAD

**Issue by HodgsonSDAS** [Microsoft/HoloToolkit-Unity#207]
`Assets\HoloToolkit\SpatialUnderstanding\Scripts\SpatialUnderstanding.cs(53,17): warning CS0162: Unreachable code detected`

**Comment by darax** [comment]
would it be bad if I included a fix for this with the fix to make the spatial understanding meshes not flicker?

**Comment by darax** [comment]
I'll just pretend that it wouldn't be bad.
