### ISSUE TITLE
GameControllerManipulator: evaluate whether to obsolete the modifier button once Unity fixes the gamepad stick issues.

### ISSUE THREAD

**Issue by vbandi** [Microsoft/HoloToolkit-Unity#211]
Currently there is a bug in unity that doesn't allow HoloLens to use all the sticks and buttons on an Xbox One controller. See [https://forums.hololens.com/discussion/comment/8002/#Comment_8002]
Because of this, GameControllerManipulator uses a "mode changer" button to switch between moving and rotating the objects. 

We should re-evaluate this mode changer and possibly make it obsolete once the bug is fixed.

**Comment by HodgsonSDAS** [comment]
@vbandi any word on this?

**Comment by HodgsonSDAS** [comment]
I'm going to close this in favor of https://github.com/Microsoft/HoloToolkit-Unity/issues/362 due to the major architectural changes from the new input modules.

**Comment by HodgsonSDAS** [comment]
Seems Unity 5.5.1f1 addresses this:

> - VR:  Y-Axis Range For VR Controllers now match XBox controllers (858634)
