### ISSUE TITLE
GestureRecognizer throws exception

### ISSUE THREAD

**Issue by JeffPack** [Microsoft/HoloToolkit-Unity#213]
So I was running debugging to watch for error messages, and upon loading a scene I got the following error message.

Exception thrown: 'System.NullReferenceException' in UnityEngine.dll NullReferenceException: Object reference not set to an instance of an object.  at UnityEngine.VR.WSA.Input.GestureRecognizer.InvokeNavigationEvent(GestureEventType eventType, InteractionSourceKind source, Vector3 relativePosition, Ray headRay)  at UnityEngine.VR.WSA.Input.GestureRecognizer.$Invoke30(Int64 instance, Int64\* args)  at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64\* args, IntPtr method)

I am using the camera prefab from the Holotoolkit. None of the code that handles gestures is my own, it is all default code so it is supposed to only register a tap event. The only thing that calls GestureRecognizer is the GestureManager script It seems like it has a missing delegate. Has anyone else noticed this or have this problem?

**Comment by NeerajW** [comment]
So I can debug the same thing, were you using some test scene?

**Comment by JeffPack** [comment]
I will try to come up with some repro information for you.

**Comment by NeerajW** [comment]
Please do feel free to submit a fix if you find it.

**Comment by HodgsonSDAS** [comment]
@JeffPack were you able to reproduce this?

**Comment by JeffPack** [comment]
I have not been able to give it any time as of yet. I remember this happened when clicking a UI button to load a scene. I have a hunch that due to system hang, it thought that I was trying to do a navigation gesture on the button that was then being unloaded, which may have thrown the error. I could be wrong.

**Comment by NeerajW** [comment]
Please open if you repro again with latest master.
