### ISSUE TITLE
RemoteHeadManager does not update local head position properly

### ISSUE THREAD

**Issue by HodgsonSDAS** [Microsoft/HoloToolkit-Unity#214]
Remote head manager does not update the local users "head".

Repo Steps:

1. Create new project
2. Import HoloToolkit
3. Open Sharing scene
4. Open Build Settings and add open scene
5. Build, and deploy to device
6. A cube initially gets created in the position the user is standing, but if you walk about, you will see the cube in the position where it was create when you started the application.

Simple fix:
Don't create a local game object for your head.  We probably don't need to see our own head anyway.

Inside RemoteHeadManager.cs
```
private void Instance_SessionJoined( object sender, SharingSessionTracker.SessionJoinedEventArgs e )
    {
        if( e.joiningUser.GetID() != SharingStage.Instance.Manager.GetLocalUser().GetID() )
        {
            GetRemoteHeadInfo( e.joiningUser.GetID() );
        }
    }
```

**Comment by NeerajW** [comment]
True that. Will fix.
