### ISSUE TITLE
Release / Versioning system ?

### ISSUE THREAD

**Issue by stbertou** [Microsoft/HoloToolkit-Unity#217]
Hi guys

I was thinking that it may be useful to put some sort of "release process" in place or simply a versioning tagging system.
Basically when I get the latest version of the HolotoolKit and copy it into another project, I use the git SHA to reference which version I'm on but this obviously not ideal.
What about using a major/minor/patch scheme when branches are merged to master ? 

Related to that I have to create some sort of release notes myself but this could be auto-generated as well for each new "release".

Just my 2c.
-s

**Comment by jwittner** [comment]
We've talked about that a lot actually! Hopefully something materializes soon!

**Comment by HodgsonSDAS** [comment]
Any word on this?  I think this is important.

**Comment by jwittner** [comment]
@NeerajW What's it take to get a build server and VSTS account going that we can use to automate builds of the HTK?

**Comment by HodgsonSDAS** [comment]
I'd even like to see you guys throw this on the Unity Asset store to make it easier to push versioned updates.

**Comment by NeerajW** [comment]
@ChimeraScorn and I have been brainstorming and working towards this. I don't have an update at the moment but our current plan is to leverage internal automated build systems to snap builds, mark them as releases and publish them to the Unity asset store.

**Comment by StephenHodgson** [comment]
@NeerajW I assume there's a plan in place for for this already, but could this be documented somewhere in the contributing document?
