### ISSUE TITLE
Fill out Spatial Mapping Doc

### ISSUE THREAD

**Issue by HodgsonSDAS** [Microsoft/HoloToolkit-Unity#218]
https://github.com/Microsoft/HoloToolkit-Unity/wiki/Spatial-Mapping is blank.

suggest we fill in information from @angelaHillier 's walk through on  http://forums.hololens.com/discussion/comment/8700 and knowledge dump from http://forums.hololens.com/discussion/2375/systems-spaces-vs-in-app-mapping

**Comment by angelaHillier** [comment]
I just used 'Spatial Mapping' as an example. This might be a better description to add at the top level of our HoloToolkit-Unity, since it describes how to build and run a test/example project.

**Comment by angelaHillier** [comment]
The knowledge dump section is more relevant for Spatial Mapping, but might be better to trim it/re-word it in reference to the HoloToolkit components (Spatial Understanding, planefinding, etc) and why you might use them. I'll put this as a to-do for myself.

**Comment by HodgsonSDAS** [comment]
Updated the wiki to point to the[ Spatial Mapping in Unity](https://developer.microsoft.com/en-us/windows/holographic/spatial_mapping_in_unity) documentation.
