### ISSUE TITLE
RemoveSurfaceVerticies not working.

### ISSUE THREAD

**Issue by arondesign** [Microsoft/HoloToolkit-Unity#23]
The script is not removing any verticies.

**Comment by NeerajW** [comment]
@arondesign thank you for filing this issue. Would you like to code up a fix for this?
Do you have a proposal?

**Comment by keveleigh** [comment]
@NeerajW I believe #24 is related to this issue.

**Comment by keveleigh** [comment]
Closed via #24 (please reopen if there's still more work to be done).
