### ISSUE TITLE
Need Improved Configuration Settings and Descriptions

### ISSUE THREAD

**Issue by jbienzms** [Microsoft/HoloToolkit-Unity#230]
As discussed in #219 we should update **Apply HoloLens Project Settings** and **Apply HoloLens Scene Settings** to better communicate with users the changes that will be applied to their project. The following approach is proposed:
1. Leverage a popup window with check boxes similar to the one demonstrated in #219 
2. Provide descriptions of the changes that each check box will make to the project
3. Update notes for the Internet Client capability to indicate that it is also needed for DictationRecognizer and Unity's profiler

I am volunteering to do the work on this issue. Please feel free to assign it to me.

**Comment by HodgsonSDAS** [comment]
Might be a good time to do this now that some features have been depreciated with 5.5

**Comment by jbienzms** [comment]
Agreed. I've actually been thinking about this recently and wanting to get to it maybe even later this week.

What features have been depreciated with 5.5 though? I would like to make sure I implement it properly.

**Comment by HodgsonSDAS** [comment]
https://github.com/Microsoft/HoloToolkit-Unity/issues/365

**Comment by jbienzms** [comment]
Got it. Thanks. I'll see if I can resolve this weekend.
