### ISSUE TITLE
Improper usage to material references in test scenes

### ISSUE THREAD

**Issue by HodgsonSDAS** [Microsoft/HoloToolkit-Unity#236]
1. renderer.material.color will make a copy of the material in memory increasing memory and draw calls
2. renderer.sharedmaterial.color is better than 1 but will change all objects that use that material
3. Best is you use a shader on the material which exposes a highlight color and use this script to change that color. To reference this code, please look at the Holograms 210 Gaze academy code for highlighting objects. It uses a custom shader for this which is more performant than 1 and 2.

This applies to the following classes in the Test/Scripts folder:

- FocusedObjectColorChanger.cs
- SelectedObjectMessageReceiver.cs
- SphereKeywords.cs
- SphereGlobalKeywords.cs
- DirectionIndicator.cs
- TestButton.cs
- Utils.cs

**Comment by NeerajW** [comment]
Thanks for filing!

**Comment by jwittner** [comment]
This is one of the most annoying APIs in Unity - can't tell you the number of leaks I've found to be this. In cases where accessing the material is necessary we've tended to wrap that in a place that owns the new reference and can delete it in OnDestroy.
