### ISSUE TITLE
Holotoolkit folder cannot be imported without Holotoolkit-examples folder

### ISSUE THREAD

**Issue by DomDumont** [Microsoft/HoloToolkit-Unity#242]
When I import only the Holotoolkit folder, I got several compiling erros in the sharing section

**Comment by jwittner** [comment]
Can you put the compiler warnings here?

**Comment by NeerajW** [comment]
I just tried this without any errors. Are you sure you did not forget to export the *.rsp files under the Assets folder?
What version of Unity are you using?

**Comment by DomDumont** [comment]
Hi,

You were right, it was because of missing rsp files. The error was "Assets/HoloToolkit/Sharing/Scripts/SDK/AnchorDownloadRequest.cs(58,22): error CS0227: Unsafe code requires the `unsafe' command line option to be specified"
My version is 5.4.0f3-HTP
Thanks, sorry for the false positive
