### ISSUE TITLE
BasicCursor.cs sometimes creates null reference exception

### ISSUE THREAD

**Issue by jomalli** [Microsoft/HoloToolkit-Unity#246]
BasicCursor sometimes cannot find GazeManager.Instance because it is doing it from Awake(). 

The reason for this appears to be script execution order.

Solution: place all the Awake() code into the Start() function instead.

**Comment by HodgsonSDAS** [comment]
Not sure how many people use the Basic cursor but it might not be good that we change the Awake to Start because it might break the inherited classes.

**Comment by jomalli** [comment]
@HodgsonSDAS good point. Another solution would be to include script execution order in project settings, and place GazeManager before BasicCursor. Any other suggestions?

**Comment by HodgsonSDAS** [comment]
I ended up just moving the code where we find the GazeManager into the LateUpdate loop.  Take a look at my pull request.

**Comment by HodgsonSDAS** [comment]
We just moved the trouble code into the Start. Left everything else in place.
