### ISSUE TITLE
Script I can attach to the model to make it hologram?

### ISSUE THREAD

**Issue by ywj7931** [Microsoft/HoloToolkit-Unity#251]
Is there a script that I can attach it to my gameobject to make it movable and scalable like the hologram demo?

**Comment by HodgsonSDAS** [comment]
I think this is a better question best answered in the [Q&A Forum](https://forums.hololens.com/categories/questions-and-answers)

One person even found a great blog post about it.
http://blog.ickydime.com/2016/05/hololens-manipulate-gestures-and.html

I think the two best scripts to just throw on and try out would be `ScaleObjectMessageReciever.cs` and `TapToPlace.cs`.  Also check out the `SelectedObjectKeywprds.unity` scene to see some implementation.

**Comment by ywj7931** [comment]
@HodgsonSDAS Thanks! that is really helpful!
