### ISSUE TITLE
HoloToolkitCommands.BuildSLN will return error code 0 even on failure

### ISSUE THREAD

**Issue by jwittner** [Microsoft/HoloToolkit-Unity#255]
I've got automated processes depending on this build tooling. This is very annoying. See here for how to enforce the proper return code:

https://docs.unity3d.com/Manual/CommandLineArguments.html

> To return an error from the command line process, either throw an exception which causes Unity to exit with return code 1, or call EditorApplication.Exit with a non-zero return code. To pass parameters, add them to the command line and retrieve them inside the function using System.Environment.GetCommandLineArgs. To use -executeMethod, you need to place the enclosing script in an Editor folder. The method to be executed must be defined as static.

**Comment by StephenHodgson** [comment]
Pretty sure this has already been addressed.
