### ISSUE TITLE
Spatial Understanding Missing README

### ISSUE THREAD

**Issue by jamesmgg** [Microsoft/HoloToolkit-Unity#261]
https://github.com/Microsoft/HoloToolkit-Unity/tree/master/Assets/HoloToolkit/SpatialUnderstanding

**Comment by jwittner** [comment]
@jevertt Do you have any documentation on this we can quickly convert to a readme?

**Comment by jevertt** [comment]
Yes - we have documentation here: https://developer.microsoft.com/en-us/windows/holographic/spatial_mapping_in_unity#holotoolkit.spatialunderstanding

**Comment by jwittner** [comment]
Maybe we can just add a small readme that links to this documentation?
