### ISSUE TITLE
New spatial mapping drops frames every update period

### ISSUE THREAD

**Issue by izatar** [Microsoft/HoloToolkit-Unity#264]
The new spatial mapping mesh code is dropping several frames every update period.  This makes the mesh blink on and off in an unsettling manner.   

I have tracked it down to the fact that 'yields' are being called between the mesh 'Cleanup()' and the completion of the 'AddSurfaceObject' calls.   During this time, the meshes are in an inconsistent state.

From line 252 of SpatialUnderstandingCustomMesh.cs: I tried changing it from:

```
252             yield return null;

                // Clear our old surface objects.
                Cleanup();

                yield return null;

                startTime = DateTime.Now;

                // now we have all of our triangles assigned to the correct mesh, we can make all of the meshes.
                foreach (MeshData meshdata in meshSectors.Values)
                {
                    // Tell the meshdata class to generate its mesh.
                    meshdata.Commit();
                    // And create a surface object using the mesh.
                    AddSurfaceObject(meshdata.MeshObject, string.Format("SurfaceUnderstanding Mesh-{0}", transform.childCount), transform).AddComponent<WorldAnchor>();

                    // Limit our run time so that we don't cause too many frame drops.
                    if ((DateTime.Now - startTime).TotalMilliseconds > MaxFrameTime)
                    {
                        yield return null;
                        startTime = DateTime.Now;
                    }
                }
            }

            // Wait a frame
            yield return null;
```
to

```
252               yield return null;
                startTime = DateTime.Now;

                // now we have all of our triangles assigned to the correct mesh, we can make all of the meshes.
                foreach (MeshData meshdata in meshSectors.Values)
                {
                    // Tell the meshdata class to generate its mesh.
                    meshdata.Commit();
                    
                    // Limit our run time so that we don't cause too many frame drops.
                    if ((DateTime.Now - startTime).TotalMilliseconds > MaxFrameTime)
                    {
                        yield return null;
                        startTime = DateTime.Now;
                    }
                }
                yield return null;
                // Clear our old surface objects.
                Cleanup();

                foreach (MeshData meshdata in meshSectors.Values)
                {
                    // And create a surface object using the mesh.
                    AddSurfaceObject(meshdata.MeshObject, string.Format("SurfaceUnderstanding Mesh-{0}", transform.childCount), transform).AddComponent<WorldAnchor>();

                }
            }


```

This change gets rid of the frame drop outs at the price of a slight frame-rate reduction on the update beat.   What it is doing is chopping the code up a little bit and ensuring that no yields happen after the call to CleanUp();

I also should note that the finalized mesh (in the original checked in code) was still only getting 29fps even when I am only looking at a small piece of the mesh.   ~~I suspect this can be addressed in the shader by not using a geometry shader~~(EDIT: i tried this, still at 29fps), although it leaves me questioning the effectiveness of this new approach in terms of frame rate improvement.

However, this code does seem to address bug #200 in practice, however this code still does not actually explicitly guarantee one of the meshes wont be too large.

**Comment by darax** [comment]
removing the yield in the foreach loop probably isn't the best, but I do think that I can address the 'blinking' of the meshes in another way.

**Comment by darax** [comment]
BTW, if you want to see the gain of the change, try removing the UI and text renderers from the test scene.  That keeps me around 60 unless I look at the mesh from a distance where a lot of the submeshes will be rendering, and even then it still runs above 30 most of the time.   Without the change (and without the extra UI) I get 30 - 40fps looking at the same places where I get 60 with the mesh split.

**Comment by darax** [comment]
Okay, I've pushed some changes that should address the flickering of meshes.
