### ISSUE TITLE
Spatial Mapping Disabled for Holographic Remoting

### ISSUE THREAD

**Issue by markgrossnickle** [Microsoft/HoloToolkit-Unity#272]
Within SpatialMappingManager there is an #if UNITY_ENGINE check within the StartObserver and StopObserver methods.

This check prevents SpatialMapping from occurring during a Holographic Remoting session.

This may be a bigger issue/ticket as there may be other areas of the code base using similar macros that did not anticipate the addition of Holographic Remoting platform.

**Comment by HodgsonSDAS** [comment]
Is this closed?

**Comment by HodgsonSDAS** [comment]
@markgrossnickle is this issue closed?

**Comment by jwittner** [comment]
Close per #288.

**Comment by BhavaniGudimetla** [comment]
Hi markgrossnickle,

I am unable to get the visual meshes in hololens when i use holographic remoting, if i don't mention any room scale model.
can you please help me how to get visual meshes in hololens when i use holographic remoting without giving any room scale model reference.

**Comment by markgrossnickle** [comment]
@BhavaniGudimetla This ticket is a few years old and was addressed. I'd either post on StackOverflow and tag it Hololens if you think you may be doing something wrong with your setup or post a new ticket here if you think there is a new bug.

**Comment by BhavaniGudimetla** [comment]
Hi Mark,

I have gone through the ticket which you have raised and I have made changes in the script which you have posted(SpatialMappingManager).
One thing I want to confirm here is, in my project I am not using any room scale model reference and you didn’t mention that whether it is with room scale model or not.
My issue is to display visual meshes by using spatial mapping in HoloLens when I use holographic remoting without any room scale model reference.

Please help me if you have the solution.
Thanks in advance……

Regards,
Bhavani Gudimetla.

**Comment by markgrossnickle** [comment]
I was not using a room model

**Comment by BhavaniGudimetla** [comment]
Hi Mark,
Thank you for the response....when i do this change in the script i am getting errors..it might be the Holotoolkit version issue.
i am using unity 2018.1.0f2 version
**I am following this link:**
https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/288/commits/c21851d84b9734be634f1ca5ec8e76af32044c09

**Comment by markgrossnickle** [comment]
@BhavaniGudimetla 
You should be using the HTK release branch here: https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/htk_release   

I am not sure what version of Unity it officially supports but I believe it is 2017.x

Using an older version of HTK or a newer version of Unity could cause issues.  

Again, this ticket is from 2016 and was addressed. If you continue to have issues please make a new ticket (if there is a bug in the toolkit) or create a stackoverflow post (if there is a question about your setup).  I'm going to unsubscribe from this ticket as it is closed.

**Comment by BhavaniGudimetla** [comment]
Ok
