### ISSUE TITLE
HoloToolkit Input Module: design discussion

### ISSUE THREAD

**Issue by maxouellet** [Microsoft/HoloToolkit-Unity#277]
This is the initial suggested design for the new input module. Feel free to ask questions / request changes.

I already have a version of this implemented, to which I will make improvements as needed. Goal is to add it to HoloToolkit so that new features can be added by the community as needed. It has been designed to be as extensible as possible.
## Why design a new Input Module?

A lot of applications have a need for an efficient way to handle input. In an ideal world, game objects can handle the input events they are interested in without having to write the same code in multiple components. The current solution in HoloToolkit isn't very performant and relies on Unity's messaging system, which is not very performant and doesn't make it obvious that behaviours are handling input events. It also doesn't extend well to support multiple different input mechanisms.

Unity provides an [event system ](https://docs.unity3d.com/Manual/EventSystem.html) that it currently leverages to send out inputs to game objects. It contains a **HoloLensInputModule** that interprets HoloLens input and sends out the standard [Unity events](https://docs.unity3d.com/Manual/SupportedEvents.html). The solution I propose does not use this input module, for the following reasons:
- It does not easily support gaze stabilization: instead, it always assumes that you are targeting the center point of your camera, using a raycaster attached to your camera.
- It only supports sending out the standard Unity events, which are 2D events. This lacks some of the key information that is needed to manipulate 3D objects with input devices that have more than 2 degrees of freedom.

The proposed design leverages Unity's event system, but implements its own version of an input module (called _InputManager_ in this case). This currently gives us more flexibility in exploring various interaction mechanisms, which is very helpful when working with novel inputs devices such as what HoloLens provides.
## Class diagram

Overall view of the main classes and interfaces that make up the initial version of this input module. Minor changes could still be done before submission (for example, HandsInput will likely be merged with GesturesInput, as their functionalities are very similar).

![inputmodule](https://cloud.githubusercontent.com/assets/8505814/19321359/98bbeca0-9069-11e6-9e17-e9845c8846f0.png)
## Input Module Design

The input module is designed to be extensible: it could support various input mechanisms and various types of gazers.

Each input source (hands, gestures, others) implement a **IInputSource** interface. The interface defines various events that the input sources can trigger. The input sources register themselves with the InputManager, whose role it is to forward input to the appropriate game objects. Input sources can be dynamically enabled / disabled as necessary, and new input sources can be created to support different input devices.

Game objects that want to consume input events can implement one or many **input interfaces**, such as:
- **IFocusable** for focus enter and exit. The focus can be triggered by the user's gaze or any other gaze source.
- **IHoldHandle** for the Windows hold gesture.
- **IInputHandler** for source up, down and clicked. The source can be a hand that tapped, a clicker that was pressed, etc.
- **IManipulationHandler** for the Windows manipulation gesture.
- **ISourceStateHandler** to handle when an input source is detected or lost. This can be triggered when a hand comes into view of the HoloLens, for example.

The **input manager** listens to the various events coming from the input sources, and also takes into account the gaze. Currently, that gaze is always coming from the GazeManager class, but this could be extended to support multiple gaze sources if the need arises.

By default, input events are sent to the currently focused game object, if that object implements the appropriate interface. Modals input handlers can also be added to the input manager: these modal handlers will take priority over the currently focused object Fallback handlers can also be defined, so that the application can react to global inputs that aren't targeting a specific element. Any event sent by the input manager always bubbles up from the object to its ancestors. 

In recap, the input manager forwards the various input sources events to the appropriate game object, using the following order:
1. The registered modal input handlers, in LIFO order of registration
2. The currently focused object
3. The fallback input handlers, in LIFO order of registration

The input manager also has a pointer to the currently active **Cursor**, allowing it to be accessed from there. The cursor currently also depends on the gaze coming from the GazeManager class.

**Comment by HodgsonSDAS** [comment]
LIFO?

**Comment by maxouellet** [comment]
Last In, First Out. It's a stack

**Comment by genereddick** [comment]
When will this be ready for testing?

**Comment by maxouellet** [comment]
Good question. I'm aiming for the week of the 24th. Current plan is to initially put this in a separate branch, give it a few weeks to communicate the breaking changes + stabilize as needed, and then RI into master.

I have this working locally on a few projects, but there's some cleanup I need to do beforehand to cleanly integrate it. Notably, this comes with some other utility fixes and additions that might have ripple effects, such as a modified Singleton that doesn't call FindByType.

**Comment by HodgsonSDAS** [comment]
@maxouellet Any News?

**Comment by aalmada** [comment]
Have you considered using Reactive Extensions (UniRx)? It allows compact and robust code specially when handling asynchronous inputs from multiple sources. Here is a reactive version of the GazeGestureManager for the Origami sample: https://github.com/aalmada/OrigamiRx/blob/master/Assets/Scripts/GazeGestureManager.cs

**Comment by HodgsonSDAS** [comment]
I was considering UniRx as well, but I didn't like that it was essentially using Linq

**Comment by aalmada** [comment]
The Linq performance issue was already raised in the Hololens forum and here is the clarification by the UniRx developer: https://forums.hololens.com/discussion/comment/7938/#Comment_7938

**Comment by maxouellet** [comment]
@HodgsonSDAS I'll likely get started on this today or tomorrow. I have all the code written for a first version, it's just a matter of cleaning it up so that i can publish it externally. My schedule is clearing up this afternoon, so hoping to have a first pull request out by end of the week, 

@aalmada  I have not considered UnirRx. My understanding is that we want to keep HoloToolkit as light and standalone as possible, and also make it simple to use for new developers. While I have no doubt that UniRx is great, I'm not convinced that we should add it as a mandatory dependency to the core HoloToolkit. That being said, this can definitely be brought up in a separate discussion if someone is willing to do the work. Maybe it could be an optional extension to HoloToolkit, or something like that.

**Comment by NeerajW** [comment]
I agree with Max. We should keep HoloToolkit strongly typed, easy to read code and extensible.
Personally, I felt UnirRx did not meet the readable code criteria.
I don't doubt its power but I'd rather not take a dependency on that less known design pattern. Interface/Singleton based patterns are understood by all. If not then they can be easy to ramp up to. Hope this helps!

**Comment by darax** [comment]
@maxouellet are you planning on switching back to the singleton that requires setting the instance in awake?

**Comment by NeerajW** [comment]
Max here are some questions/thoughts based on the interface diagram:

1. **Gaze**:
Since we have named all classes so far related to Gaze to be Gaze*something does it makes sense to call IFocusable to be IGazeable and OnGazeEnter and OnGazeExit? This might have the transition easier as well for current code bases.

2. **Gesture:**
- Would it make sense to define all interfaces for gestures? And not just Hold/Manipulation.

- ISourceStateHandler Vs IInputHandler: Looks like these split out the UnityEngine.VR.WSA.Input.InteractionManager functionality. I think the names are confusing. Perhaps keep the interface names closer to the actual API? For example: It can be confusing to know which interface to use for what in this design. Unless I misunderstood something?

3. **Voice:**
- I don't see much around that. Any thoughts?

**Comment by aalmada** [comment]
I totally agree with @maxouellet reasoning but not with @NeerajW . Rx is strongly typed, easier to read and easier to extend. For these same reasons so many people are now adopting functional languages.
I already started working on a reactive version of HoloToolkit but I'm still trying to figure out the best way to take advantage of your work without replicating it. If it was natively reactive it would be much simpler and that's why I raised the issue. 
Thanks a lot for the feedback and for all the amazing work.

**Comment by maxouellet** [comment]
@darax Yes, but we have improvements to it so that it automatically sets itself up in Awake. There are two drawbacks to this, but at least it's better coding practice than doing FindByType across your whole scene. 

1. If your singleton class needs to declare an Awake, it has to call base.Awake() to set the instance.
2. Singletons are only guaranteed to be set in Start(), so you should never call into a Singleton in Awake. This is consistent with the expectation that Awake is to set-up your class, and Start is to setup its dependencies and behaviors.

**Comment by darax** [comment]
var is the opposite of strongly typed. :)

Having a function like .RefCount is a hint that people working on it will need to understand object lifetime of Rx.  This makes it harder to extend without introducing leaks or crashes. 

I don't consider Linq to be more readable.  The script you posted is hard for me to follow. What does .Publish() do? How does the focused object get set? I'd expect to see a raycast somewhere to set the focused object, but I don't see that.

I like where it looks like Max is going with the interfaces, and I'm sure that Rx can be wrapped around that once he's done.

**Comment by darax** [comment]
FindByType is only called once per singleton.  I'm not sure why that's a problem.

**Comment by HodgsonSDAS** [comment]
I agree, Linq isn't strongly typed and can be confusing to read at first, but the definitive answer lies in hard data.

**Comment by HodgsonSDAS** [comment]
@maxouellet how different is this new singleton generic?

**Comment by maxouellet** [comment]
I'll make it simpler by just sharing out what we're using right now.

```
    /// <summary>
    /// Singleton behaviour class, used for components that should only have one instance
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public class Singleton<T> : MonoBehaviour where T : Singleton<T>
    {
        private static T instance;
        public static T Instance
        {
            get
            {
                return instance;
            }
        }

        /// <summary>
        /// Returns whether the instance has been initialized or not.
        /// </summary>
        public static bool IsInitialized
        {
            get
            {
                return instance != null;
            }
        }

        /// <summary>
        /// Base awake method that sets the singleton's unique instance.
        /// </summary>
        public virtual void Awake()
        {
            if (instance != null)
            {
                Debug.LogErrorFormat("Trying to instantiate a second instance of singleton class {0}", GetType().Name);
            }
            else
            {
                instance = (T) this;
            }
        }

        public virtual void OnDestroy()
        {
            if (instance == this)
            {
                instance = null;
            }
        }
    }
```

**Comment by HodgsonSDAS** [comment]
I like it, but we will need to make sure everyone calls the base classes when utilizing it.  I wish there was a way to make calling the base class required.

**Comment by maxouellet** [comment]
You get a warning in the editor if you override Awake without specifying "override". Also, if you don't call base.Awake(), you will get a bunch of null exceptions every time you try to access the instance.

**Comment by timGerken** [comment]
should Awake and OnDestroy be marked as "protected" instead of "public"

**Comment by HodgsonSDAS** [comment]
What happens if someone doesn't call base.OnDestory?

**Comment by timGerken** [comment]
I've also seen this pattern, in the `(instance != null)` case call `DestroyImmediate(this)` just to be sure.

**Comment by maxouellet** [comment]
@timGerken  Yes it should be protected, the reason it is public is that when this was written at a time where there was a bug in Unity where protected inheritance caused a runtime exception. I'd fix it before submitting :)

If you don't call base.OnDestroy, you have a dangling static reference, which I _think_ will eventually be cleaned up by the garbage collector. Realistically, this is only useful in cases where you want to destroy a Singleton before your app closes. That's already the case with the existing Singleton.

I'm not sure there is a need to call DestroyImmediate in this case, but not strongly opposed to it either.

**Comment by timGerken** [comment]
Should this Singleton pattern survive Unity scene transitions?
If so, in Awake, it should also call `DontDestroyOnLoad(this);`

**Comment by HodgsonSDAS** [comment]
@timGerken  I think that should be optional, but a good idea.

**Comment by HodgsonSDAS** [comment]
@maxouellet I think documenting the required call to the base class should be good enough.

**Comment by maxouellet** [comment]
@NeerajW 
**Gaze:** It's purposefully not called Gaze because it isn't necessarily tied to gaze. Part of the goal of this design is to be flexible around input mechanisms, so I wouldn't want to strongly tie it to Gaze.

**Gesture events:** Yes. I think only Navigation was originally missing in there. The reason its missing is because a GestureRecognizer can only support either manipulation or Navigation. I'll likely add Navigation by creating a second GestureRecognizer for that purpose.

**Merging ISourceStateHandler and IInputHandler:** I don't have strong feelings about that, I think both sides could be argued. I originally made them separate because I'd rather have smaller interfaces than a big interface that forces you to have 5 methods even though you might only care about one of them. This is consistent with Unity's event system interfaces: in fact, they push it even more by having one interface per method.

**Voice:** This does not aim at addressing voice for now.

**Comment by maxouellet** [comment]
@timGerken It's not in there by design, because we've had cases where we only wanted a singleton for a single scene. I haven't played with it much, but what I've typically done is have a "DontDestroyOnLoad.cs" MonoBehaviour that calls DontDestroyOnLoad(this) in Start. That makes it easy to make any GameObject survive scene transitions, without having to add that logic to many of your scripts.

Otherwise you can end up with many singletons calling DontDestroyOnLoad on the same GameObject. Or you can end up with undesired behaviours when reusing components across projects. Making it optional like @HodgsonSDAS suggested would also work if people feel that's really valuable.

**Comment by NeerajW** [comment]
@maxouellet sounds good on the GGV discussion. Thanks for considering!

**Comment by aalmada** [comment]
@darax Not knowing Rx is one thing but saying the "var is the opposite of strongly typed" is shocking!
This project needs some discussion forum. What about Gitter just like many other .NET project?

**Comment by HodgsonSDAS** [comment]
@aalmada Yes, var is the opposite of strongly typed. 
[MSDN for reference](https://msdn.microsoft.com/en-us/library/bb383973.aspx):
```
var i = 10; // implicitly typed

int i = 10; //explicitly typed
```

**Comment by paseb** [comment]
@maxouellet and @NeerajW, I strongly agree with moving away from the term gaze to focus.  Gaze has a single use target where focus has a broader understanding for multiple targets.  Example: targeted interactions from the hand forward or other device.  You can allow for multiple "focusers" where "gaze" implicitly has the understanding of originating from the head.  

I largely agree with all of the Input changes though the cursor should also be abstracted accordingly.  Having an interface -> abstract base class for input sources should also be used for cursors.  Trying to model it after the shell cursor from the start doesn't provide the base for other cursors (sprites, material, lights... etc).

All in all awesome work @maxouellet!

**Comment by HodgsonSDAS** [comment]
@maxouellet any chance we get to play with this over the weekend?

**Comment by maxouellet** [comment]
@HodgsonSDAS Merging internal changes with the public version took more time than expected, but I'm back to a state that compiles. I still need to make sure all the tests and example scenes still work, and fix them as appropriate, which I expect is going to take most of today.

I'll try to have some early version (potentially without all example scenes working and with some changes still needed) up on my GitHub account today so that you can play with it. Will update this thread with my progress towards the end of the day.

**Comment by maxouellet** [comment]
I've pushed an early first version of this on my [GitHub](https://github.com/maxouellet/HoloToolkit-Unity/tree/ExtensibleInputModule), so that you can play around with it. There's likely still a bunch of broken scenes, mainly references that broke when I deleted / moved / added when I moved from our internal project to the public HoloToolkit project. The best scene to try out the new features is the "InputManagerTest" scene, which shows most of the new functionalities.

I still need to clean up a lot of the code, such as adding the final file header, making the singleton methods protected and adding support for the navigation gesture. I'll also go through all the example scenes to make sure everything works before I send out an official pull request.

One deficiency that I've noticed is the ability to send voice commands to the focused object. I've fixed the test scenes that were doing that, but it's not as clean as I'd like it to be. I'm not 100% sure how to address these scenarios yet, so it will likely be addressed in a future update of that input module.

**Comment by HodgsonSDAS** [comment]
Overall. Wow, great work!  I'm really excited to use this.
I do have a few thoughts though.

I noticed in the GazeManager.cs that we're [prioritizing hits](https://github.com/maxouellet/HoloToolkit-Unity/blob/ExtensibleInputModule/Assets/HoloToolkit/Input/Scripts/Gaze/GazeManager.cs#L321-L332) during the [update loop](https://github.com/maxouellet/HoloToolkit-Unity/blob/ExtensibleInputModule/Assets/HoloToolkit/Input/Scripts/Gaze/GazeManager.cs#L147).  Should we use a for loop instead of foreach?

In BaseInputSource.cs in the Events wrappers region the `RaiseSourceDetectedEvent` and `RaiseSourceLostEvent` [raises the opposite event](https://github.com/maxouellet/HoloToolkit-Unity/blob/ExtensibleInputModule/Assets/HoloToolkit/Input/Scripts/InputSources/BaseInputSource.cs#L125-L139). Is this intentional?

In Button.cs in Awake we set a hash to [trigger the dehydrate animation](https://github.com/maxouellet/HoloToolkit-Unity/blob/ExtensibleInputModule/Assets/HoloToolkit/Input/Scripts/UI/Button.cs#L92), but what if we would also like to trigger the hydrate as well?

Other than that I think most everything else is cosmetic, like preferring explicit vars, protected overrides, and extra lines.

**Comment by maxouellet** [comment]
Thanks a lot for the feedback @HodgsonSDAS . Most of what you mentioned are likely bugs, I'll look into them today.

I'm not super familiar with Button.cs, and might end up moving it to the Tests folder because I'm not convinced it's generic enough yet. The intend as I understand it is that the button states (including its active state) is completely controlled by its associated Animator state machine: the script mostly contains logic to toggle between these animations. The hash that is retrieved is just used to optimize modifying modifying the "Dehydrate" parameter on that animator ([Unity docs).](https://docs.unity3d.com/ScriptReference/Animator.StringToHash.html)

One issues that was pointed out by @NeerajW is that InputManager currently allocates the event data classes at each frame. I'll try to take a look at this and see if I can somehow improve this.

**Comment by HodgsonSDAS** [comment]
@maxouellet Yeah the button class you had looks very similar to the one we had while working on our project at MS earlier this year. We ended up making the hydrate and dehydrate animations completely automated based on the `GameObjects` active flag, but still included the option to hydrate in and out independently of the active status.  One caveat though is that we had to explicitly call a public method that in turn triggered the dehydrate animation then deactivated the `GameObject` after it completed.

**Comment by aalmada** [comment]
@maxouellet Tried your version and it's a great improvement. No more script execution order issues.

On the explicit typing, I understand your reasoning but it's arguable: https://blogs.msdn.microsoft.com/ericlippert/2011/04/20/uses-and-misuses-of-implicit-typing/

**Comment by HodgsonSDAS** [comment]
> However, the use of var does have at least the potential to make your code more difficult to understand for other developers. For that reason, the C# documentation generally uses var only when it is required.

I think it's important to make the code easier for [others to understand](https://msdn.microsoft.com/en-us/library/bb384061.aspx).  From my understanding the HTK is also for newbies who are just starting out.

**Comment by maxouellet** [comment]
I just pushed some more changes to my repository to fix the bugs that @HodgsonSDAS had pointed out, and do the additional fixes:

- Added support for the Navigation event
- Fixed the headers that were not in the MIT license format
- InputManager no longer allocates for every event that is sent out
- Removed old "Main Camera" prefab and associated camera movement script, since we now have the new HoloLensCamera prefab

Last thing I want to do before sending out an official pull request is to take a stab at merging HandsInput.cs and GesturesInput.cs, while would unify hands input with over other Windows-supported type of input.

**Comment by HodgsonSDAS** [comment]
Really digging that InputManagerTest scene

**Comment by maxouellet** [comment]
Good points.

We have a better implementation of the cursor coming in soon from @paseb, so the new cursor on my GitHub is really just a stand-in. I'll take a quick look at cleaning it up in the meantime, but odds are it simply won't be part of the pull request.

We could add some description in the example scene, but it's already pretty heavy on text. It's meant as a demo that shows the various capabilities of the input system and the cursor system, so it's kinda by design that users should explore the scene and look at the GameObjects to understand the behaviours they might be interested in having in their own project. My suggestion would be to leave it as-is for now, and we can always eventually add a ReadMe.md or something like that as necessary.

**Comment by HodgsonSDAS** [comment]
@maxouellet you also have two extra meta files that can be deleted from your repo:

Assets/HoloToolkit/Input/Models/Cursor/cursor_hand_ready.fbm/templates.meta
Assets/HoloToolkit/Input/Models/Cursor/cursor_ready.fbm/templates.meta

The Editor complains when I switch over to your branch each time, saying they've been deleted because there aren't any assets they're related to.

**Comment by maxouellet** [comment]
Thanks for the notice, I pushed a change that removes these two files.

The input stuff is pretty much done at this point, minus the cursor. Goal is to get the cursor in today or tomorrow at latest, and send out a pull request once that's done. I also need to update the documentation, which I will do today.

**Comment by aalmada** [comment]
@maxouellet You don't need so many delegates for the input sources. Two are enough and you don't even need to declare them. Use Action&lt;&gt; in the event declaration as suggested in the [.NET design guidelines for callbacks](https://msdn.microsoft.com/en-us/library/ms229041(v=vs.110).aspx):

  event Action&lt;IInputSource, uint&gt; SourceUp;
  event Action&lt;IInputSource, uint, Vector3&gt; ManipulationStarted;

This doesn't follow the [.NET design guidelines for events](https://msdn.microsoft.com/en-us/library/ms229011(v=vs.110).aspx) but this would make the sender not strongly-typed.

**Comment by maxouellet** [comment]
@aalmada In this specific case, I'm not a big fan of using Action, because it hides the meaning of the uint. I can certainly change it if people feel it's more obvious when using Action.

It agree that EventHandler and event args for the various events would be better overall, but I was trying to avoid the allocation of an *EventArgs object instance on every interaction event, given that this will be running in Unity on HoloLens. I'm open to suggestions on this

**Comment by aalmada** [comment]
@maxouellet Come on! Everything that is not C# 1.0 is not readable? Generics is 2.0
At least you could reduce to only two delegates...

**Comment by maxouellet** [comment]
@aalmada This isn't a C# 1.0 vs C# 2.0 fight :) I meant that a delegate such as:

`NavigationStartedEventDelegate(IInputSource inputSource, uint sourceId, Vector3 cumulativeDelta);`

better indicates what each of the parameters represent than

`Action<IInputSource, uint, Vector3>`

I agree that the right solution to this is to have a single parameter to your Action / EventHandler that can be a class with multiple members.

That being said, this isn't something I care about that much, so I can switch it to Action if that's the general consensus. One interesting thing is that Unity itself uses delegate (in GestureRecognizer, for example), although I'm not sure if it's because their code is auto-generated.

**Comment by paseb** [comment]
![cursor_update](https://cloud.githubusercontent.com/assets/19958303/19947429/46c9b308-a105-11e6-9ef2-725cf5f27953.PNG)

I just pushed my changes for the cursor to match the extensible nature of Input.  Look at the AnimatedCursor and SpriteCursor as a example for creating new cursors.  The animator state information is set in the current DefaultCursor prefab.  There are also some handy exposed surface rotation functionality to surface (see LookRotationBlend in cursor).

**Comment by robertlevy** [comment]
Re: eventarg allocation... you can reuse the same instance of the eventarg object each time you raise the event.  Not sure if that's weird from a Unity perspective but it's a common pattern in Microsoft's implementation of .NET input APIs

On Nov 2, 2016, at 2:13 PM, Max Ouellet <notifications@github.com<mailto:notifications@github.com>> wrote:


@aalmada<https://github.com/aalmada> In this specific case, I'm not a big fan of using Action, because it hides the meaning of the uint. I can certainly change it if people feel it's more obvious when using Action.

It agree that EventHandler and event args for the various events would be better overall, but I was trying to avoid the allocation of an *EventArgs object instance on every interaction event, given that this will be running in Unity on HoloLens. I'm open to suggestions on this

-

**Comment by maxouellet** [comment]
@robertlevy From what I'm seeing in the .NET framework, that doesn't seem right. For example, MouseButtonEventArgs has all of its properties as read-only, and a new instance of it is constructed every time a mouse button is clicked. My understanding is that EventArgs classes are meant to be immutable (unless you're using EventArgs as-is with no parameters, in which case it doesn't matter).

That being said, the performance impact of instantiating a short lived event args when input occurs is most likely negligible in the grand scheme of thing. Given that it improves the design by allowing us to more easily add input information in the events, I'll go ahead and make that change.

**Comment by robertlevy** [comment]
wow it's been a while :)  you're right, i got stuff mixed up.  different eventarg instance each time.  but the eventarg objects are fairly light weight, delegating just about everything to a device object that is shared across each args instance (example: https://referencesource.microsoft.com/#PresentationCore/Core/CSharp/System/Windows/Input/TouchEventArgs.cs)


________________________________

**Comment by aalmada** [comment]
@maxouellet I'd like to comment on the current IInputSource implementation. It assumes two modes: Manipulation and Navigation.
Will there always be only these two modes? Any change on this assumption will force changes either on the interface or in the InputManager.
A generic mouse handler (or multi-touch) doesn't have Manipulation or Navigation events. These would be states implemented on top of the more generic up, down and move events.

**Comment by maxouellet** [comment]
@aalmada I think (and hope) that the IInputSource will eventually evolve to have more interactions, as they become necessary. One example that is currently missing is some kind of ControllerInputSource, which would expose button presses  + joystick information (this might end up just being an extension to SourceUp / SourceDown).

The Manipulation and Navigation events are there specifically to expose the default Windows gesture events. I added the SourceUp, SourceDown and SourceClick events for the purpose of supporting other types of interactions that might not currently be built into the gestures APIs. The HandDraggable script is a good example of that scenario. Or if you wanted to implement some kind of two-handed manipulation, you could leverage the up and down events accordingly. Note that because of how this is designed, there is no need for a Move event: the input source itself is passed to input handlers, so that they can query the input source's position (if it has one) whenever they need it.

**Comment by aalmada** [comment]
I have a 3D model designed in CAD that is structured as a hierarchy with many leaf objects with a mesh and its collider. I want to be able to hand drag entire branches of this hierarchy instead of individual objects.
InputManager sends the messages to the focused object. I can make this work if I add a HandDraggable to each leaf object and set HostTransform to the parent branch node. 
The issue is that adding HandDraggable to each leaf object is very tedious. Is there an alternative?

**Comment by maxouellet** [comment]
The events bubble up according to your game object hierarchy, so you don`t have to have the HandDraggable script (or any other script that implements the input interfaces) on the game object that has the collider. In your case, assuming you have something like the following:

Root
   Branch1
      Leaf1
      Leaf2
   Branch2
      Leaf3
      Leaf4

You can put the HandDraggable script on Branch1 and Branch2, and that will work with the individual colliders that are in their children.

The one exception to this is if the leaves are already handling the same input event. Each input callback passed in an *EventData object that as a Use() function. If something calls that Use() function, the event is considered handled, and thus it will stop bubbling up the game object hierarchy.

Let me know if that doesn`t handle your scenario!

**Comment by aalmada** [comment]
@maxouellet Works just like you explained. Thanks!

**Comment by aalmada** [comment]
@maxouellet KeywordManager doesn't have the same bubbling mechanism. It calls a specific method in a specific object. I have a workaround but I think it would be interesting to make all these managers consistent with how InputManager invokes events.

**Comment by maxouellet** [comment]
@aalmada I agree that would be great, that work just hasn't been done yet, so I left the original classes in there. There are a few things that could be added when the need arises, notably:

- Keyboard input routing
- Controller input routing
- Voice commands input routing (that one is particularly tricky to get right...)

I do not intent to address those soon due to lack of time, but will be happy to review anyone's changes that tries to address them. I think keyboard and controller should be relatively straightforward to do.

**Comment by aalmada** [comment]
@maxouellet fair enough

**Comment by aalmada** [comment]
> I do not intent to address those soon due to lack of time, but will be happy to review anyone's changes that tries to address them. 

@maxouellet Challenge accepted! ;)
While researching on how to extend the InputManager I noticed there are two different patterns. GazeManager is explicitly registered in the InputManager while all others, like GestureInput, derive from BaseInputSource. Why doesn't GazeManager follow the more generic second pattern?

**Comment by HodgsonSDAS** [comment]
GazeManager is the one that handles most of the logic about which objects we're currently focused on, and many of these other classes utilize that information.

**Comment by aalmada** [comment]
@HodgsonSDAS Yes, I do understand that. My question is more like, is really GazeManager a special case? If not, the architecture would be somewhat simpler. Just food for thought. ;)

**Comment by HodgsonSDAS** [comment]
Oh I agree simpler is better, I'll have to take a closer look at it later. nom nom nom.

**Comment by maxouellet** [comment]
@aalmada Yeah, I didn't have enough time to figure out a great way to implement the GazeManager without breaking everything that depends on it being a singleton... 

The long term solution I was thinking was that we should have a one or many FocusSources that register themselves with the InputManager. GazeManager would be one implementation of a FocusSource (a very important one that we might want to keep as a SIngleton), but you could have others (a 6DOF Vive controller, for example). Then, every input event would not only include the input source data, but also the FocusSource that triggered the event on the object.

**Comment by paseb** [comment]
Well there goes my reply :), @maxouellet beat me to it.  I was going to say what max wrote.  Because we should support multiple input focus sources having them independent and register with input manager is a good choice.  We internally separated out a users GazeFocus from the other FocusSources since where the head is looking tends to be complimentary to other focus sources.  Examples would be gaze contextual voice commands, gaze based rendering and culling, etc.

**Comment by aalmada** [comment]
@maxouellet Is IInputSource.SupportedEvents used somewhere?

**Comment by maxouellet** [comment]
@aalmada Not right now, it's there as a convenience in case someone ever needs it. Eventually, as need arises, we might also want to add an InputType enum that tells you whether the input is Hands, Controller or whatever else the Unity APIs currently support.

**Comment by aalmada** [comment]
> There are a few things that could be added when the need arises, notably:
> 
> Keyboard input routing
> Controller input routing
> Voice commands input routing (that one is particularly tricky to get right...)

@maxouellet I was revisiting your post and thinking that the [KeywordManager](https://github.com/Microsoft/HoloToolkit-Unity/blob/7652af9343236d043a530ed3919aa4952687fd51/Assets/HoloToolkit/Input/Scripts/Voice/KeywordManager.cs) and the [SpeechInputSource](https://github.com/aalmada/HoloToolkit-Unity/blob/4e3843341311b4d50d0fe414eac862f129a9bf8f/Assets/HoloToolkit/Input/Scripts/Voice/SpeechInputSource.cs) handle voice commands but also keyboard input. The issue is that they assume that there is always a voice command associated with a key. To make this fully agnostic and reusable maybe there should be the notion of a command that can be mapped to triggers from input sources.

**Comment by yacuzo** [comment]
The diagrams in this discussion are great for learning the new system. Could they be put somewhere intuitive, and have the Input/readme.md link to them?

**Comment by HodgsonSDAS** [comment]
@yacuzo https://github.com/Microsoft/HoloToolkit-Unity/pull/376

**Comment by HodgsonSDAS** [comment]
@maxouellet Does `OnInputClicked` happen before or after `OnInputUp`?

**Comment by maxouellet** [comment]
@HodgsonSDAS OnInputClicked is not guaranteed to happen before or after OnInputUp. This is by design, because OnInputClicked is a OS-level gesture. The clicking speed is defined by the OS, so you can't modify it. It is also by design from the OS that if you click and hold for a certain amount of time, the OnInputClicked doesn't fire. This is all defined by the OS gestures: when you hold for a certain time, it ends up triggering a Hold or a Manipulation/Navigation event.

If you need to customize a click somehow (which I would not recommend, as this would go against the OS definition of a click and might break some user-specific accessibility settings down the line), you could write your own input source that has your own implementation of a click.

**Comment by HodgsonSDAS** [comment]
No, I just wanted to make sure I understand the timing.  Thanks for the info.

**Comment by maxouellet** [comment]
Closing this issue, as this has been integrated to HoloToolkit for a while now.

**Comment by basuarya** [comment]
@maxouellet Hello, I would like to know how to rotate a gameobject using ManipulationHandler. Please help?

**Comment by vbielkin** [comment]
InputManager supports some of Unity UI Events (like ExecuteEvents.pointerClickHandler,  ExecuteEvents.pointerEnterHandler, etc.) but there is nothing about ExecuteEvents.beginDragHandler and ExecuteEvents.dragHandler. As the result, using Unity ScrollBars and ScrollRect with HoloToolkit InputManager becomes impossible.
Are these Unity event handlers going to be supported in future?

**Comment by maxouellet** [comment]
@vbielkin Support could be added by anyone who needs that functionality. The clean way to implement it would be to have InputManager interpret the gestures navigation event and send the appropriate drag events (like ExecuteEvents.beginDragHandler that you pointed out).

Alternatively, you could simply attach a script to your Unity scroll bars that has a reference to your Unity UI Scrollbar and implements the INavigationHandler interface. From that script, you could then smartly manipulate the Value of the scrollbar to scroll it appropriately based on the navigation input you receive.

I don't think I'll get to add native support for drag events to InputManager any time soon, but if someone wants to try it, they are welcome to do so! Otherwise, the alternate solution I proposed should be relatively simple to implement in a project.
