### ISSUE TITLE
About RemoveSurfaceVertices question....

### ISSUE THREAD

**Issue by rtjia** [Microsoft/HoloToolkit-Unity#280]
Sorry for my english....
I want to use RemoveSurfaceVertices class, but i'm very puzzled at " !mesh.bounds.Intersects(bounds)"
,because mesh.bounds is local space, but bounds(Collider.bounds) is world space ! so ,mesh.bounds.Intersects(bounds) ,how it works?

**Comment by darax** [comment]
Good catch!  We should be using the bounds from the renderer rather than the collider.  I think we should also be transforming the verts of the mesh into world space using the transform of the filter.

**Comment by rtjia** [comment]
Thank you very much!

**Comment by NeerajW** [comment]
Fixed by #283
