### ISSUE TITLE
RemoveSurfaceVertices.RemoveSurfaceVerticesWithinBounds null reference exception

### ISSUE THREAD

**Issue by CameronVetter** [Microsoft/HoloToolkit-Unity#284]
Since this executes a coroutine it is possible for meshes to get removed from the spatial mesh while this is executing.  If this happens an exception is thrown in the coroutine and the methods never completes.  This is due to a missing null check.  I will do a PR to fix this issue.

**Comment by NeerajW** [comment]
Fixed by #283
