### ISSUE TITLE
HoloToolKit Build Window - Able to build APPX, Unable to deploy

### ISSUE THREAD

**Issue by slammer8** [Microsoft/HoloToolkit-Unity#287]
**Issue**

When building the SpatialUnderstandingExampleScene using the HoloToolKit build tool, unable to deploy on device.

**Expected Result:**

Deploys correctly

**Actual Result:**

```
System.ArgumentException: JSON parse error: Missing a comma or ']' after an array element.
  at (wrapper managed-to-native) UnityEngine.JsonUtility:FromJson (string,System.Type)
  at UnityEngine.JsonUtility.FromJson[AppList] (System.String json) [0x0000c] in C:\buildslave\unity\build\artifacts\generated\Metro\modules\JSONSerialize\JsonUtilityBindings.gen.cs:24 
  at HoloToolkit.Unity.BuildDeployPortal.QueryAppDetails (System.String packageFamilyName, ConnectInfo connectInfo) [0x0003c] in D:\Documents\Hololens Test Projects\SpatialTest\Assets\HoloToolkit\Build\Editor\BuildDeployPortal.cs:170 
  at HoloToolkit.Unity.BuildDeployPortal.IsAppInstalled (System.String packageFamilyName, ConnectInfo connectInfo) [0x00003] in D:\Documents\Hololens Test Projects\SpatialTest\Assets\HoloToolkit\Build\Editor\BuildDeployPortal.cs:116 
  at HoloToolkit.Unity.BuildDeployWindow.InstallAppOnDevicesList (System.String buildPath, Boolean uninstallBeforeInstall, System.String[] targetList) [0x00048] in D:\Documents\Hololens Test Projects\SpatialTest\Assets\HoloToolkit\Build\Editor\BuildDeployWindow.cs:508 
UnityEngine.Debug:LogError(Object)
HoloToolkit.Unity.BuildDeployWindow:InstallAppOnDevicesList(String, Boolean, String[]) (at Assets/HoloToolkit/Build/Editor/BuildDeployWindow.cs:523)
HoloToolkit.Unity.<OnGUI>c__AnonStorey1:<>m__0() (at Assets/HoloToolkit/Build/Editor/BuildDeployWindow.cs:333)
UnityEditor.EditorApplication:Internal_CallDelayFunctions()
```

**Current Workaround:**
Use device portal to manually install app and dependencies.

**Platform**

Unity 5.5.0b7
Win10 Pro V 1607 B 14393.321

**Comment by darax** [comment]
I was able to repro, but the device portal also failed to install the packages.  Once I got the device portal to work, I was no longer able to repro.

**Comment by slammer8** [comment]
Can you clarify? I'm able to install using the device portal.

**Comment by darax** [comment]
After you've installed with the device portal, have you tried installing from the toolkit build window again?

**Comment by slammer8** [comment]
Yep, same error.

**Comment by darax** [comment]
what build of unity are you running?

**Comment by slammer8** [comment]
5.5.0b7 Personal

**Comment by darax** [comment]
okay, Unity changed their JSON libs in 5.5.  I'll try to repro from 5.5

**Comment by slammer8** [comment]
Thanks!

**Comment by darax** [comment]
hrm... 5.5 is still working.  Can someone else repro?

**Comment by NeerajW** [comment]
I tried from Unity Beta 5.5.0b7 with a clean HoloToolkit-Unity App folder. I deleted all Library, UWP, App folder stuff I had from earlier.

It worked without any issues.

**Comment by darax** [comment]
Looking at the stack, the script is trying to get the list of apps on the HoloLens. I'm wondering if there is an app installed on your HoloLens that has a character which upsets the JSON parsing.

in HoloToolkit-Unity\Assets\HoloToolkit\Build\Editor\BuildDeployPortal.cs can you modify QueryAppDetails to debug.log the appListJSON?  It might be really long, in which case a File.WriteAllText("C:\\temp\\output.txt", appListJSON); would be better.

**Comment by slammer8** [comment]
[output.txt](https://github.com/Microsoft/HoloToolkit-Unity/files/536910/output.txt)

I've attached the output. I've validated it with JSONLint and it seems good.

**Comment by darax** [comment]
cool, Unity 5.5 doesn't like it. :) Unity 5.4 is okay.  I'll see if I can find a way to make 5.5 happy.

**Comment by slammer8** [comment]
Thanks!

Best,

Sam

**Comment by darax** [comment]
Not sure what the workaround is yet, but this app's name is confusing unity's JSON parser in 5.5.

SpaceTrackerâ„¢ (Holographic) BINARYSPACE.SpaceTrackerHolographic BINARYSPACE.SpaceTrackerHolographic_0.2.2.0_x86__m2n15m7j6eax2 3 BINARYSPACE.SpaceTrackerHolographic_m2n15m7j6eax2!App CN=54E260E2-8F4A-4499-B49D-A5A8ECEB1172
UnityEngine.Debug:LogFormat(String, Object[])
quickscript:Start() (at Assets/quickscript.cs:31)

**Comment by slammer8** [comment]
Thanks for figuring that out. After I uninstalled the app, I was able to deploy correctly. 

Maybe because the app title has the (TM) symbol?
