### ISSUE TITLE
Unable to use Spatial Understanding and Hololens Remoting

### ISSUE THREAD

**Issue by slammer8** [Microsoft/HoloToolkit-Unity#290]
## Issue

Unable to use Spatial Understanding with Hololens Remoting
## Steps to reproduce

For spatial understanding, I found numerous references to #IF UNITY_EDITOR within the scripts.

After commenting those lines out, I get a new error of  
`Failed to load 'Assets/HoloToolkit/SpatialUnderstanding/Plugins/WSA/x64/SpatialUnderstanding.dll' with error 'This operation is only valid in the context of an app container.`

It seems that you can't load the DLL's within the unity editor.

**Comment by HodgsonSDAS** [comment]
To get this to work properly you will need to put the `SpatialUnderstanding.dll` in your Unity editor programs folder: `C:\Program Files\Unity\Editor\`

**Comment by HodgsonSDAS** [comment]
Spatial Understanding seems to be compiled only for UWP.
This would probably need to be rewritten or compiled to support .NET

**Comment by mrbobbybobberson** [comment]
Coincidentally, I went down this rabbit hole over the past few weeks and got it working.  I can get the code cleaned up in a branch and share it within the next couple days.

**Comment by slammer8** [comment]
Excited for this!

**Comment by cgmagic** [comment]
I cannot seem to get the example scene to work on the Emulator or Remoting.

**Comment by mrbobbybobberson** [comment]
It's currently broken (not implemented).  I'm working on a pull request that will implement it over the next few days.
