### ISSUE TITLE
Sharing sample -> User joins session but never joins room

### ISSUE THREAD

**Issue by Holo-Krzysztof** [Microsoft/HoloToolkit-Unity#292]
I've noticed a strange bug which seems like a race condition: sometimes, when looking at the debug output of the Sharing sample you get a "User joining session" debug print but after that it seems to be stuck forever in the AnchorStore_Initialized state because the sharing service never gets marked as ready.
This happens because `SharingSessionTracker.SendJoinEvent()` is called before `ImportExportAnchorManager` gets to subscribe to this event.

The problem went away after moving `SharingSessionTracker.Instance.SessionJoined += Instance_SessionJoined;` from `SharingManagerConnected()` to `Start()` , so I'd propose that as a solution.
Can anyone else reproduce this issue and give me some more insight?

**Comment by NeerajW** [comment]
I can believe this. Were you in Debug mode? This was a relatively recent change by @alexdrenea inside SharingStage. Seems reasonable to move SharingSessionTracker.Instance.SessionJoined += Instance_SessionJoined; to Start().

@alexdrenea any thoughts on this?

**Comment by alexdrenea** [comment]
I checked the code as well and I agree that the event should be hooked up in `Start`, there's no good reason for it to be in the `SharingManagerConnected()` method. 

I can't validate it on a real device at the moment though (due to lack of availability 😞).

**Comment by NeerajW** [comment]
@Holo-Krzysztof would you like to make the change?

**Comment by Holo-Krzysztof** [comment]
I'm not entirely sure yet, because after that change I've got a NullReferenceException in InitRoomApi() once, but that could be due to other changes in the project. I'll investigate that and if there are no issues, I'll make a pull request.

**Comment by Holo-Krzysztof** [comment]
Btw, it was in release mode, @NeerajW.

**Comment by Holo-Krzysztof** [comment]
Alright, I discovered another bug related to my change: Sometimes `SharingManagerConnected` never gets called and thus `roomManager` is null, leading to exceptions in `InitRoomApi()`.

Let's look at a sample execution:

- `SharingStage` calls `Awake()`, which in turn calls `Connect()` (in my case, because auto discovery is off)
- `Connect()` does some config steps and creates a `SharingManager` from native and then says "Wait a second and check if we're connected" with the `Invoke()` call below (which seems like asking for trouble, not to mention that it's hard to find in the editor -> no references in Shift+F12 because it's not a direct call, but uses reflection)
- In the meantime, `Awake()` methods of other scripts are running too, and after that each script's `Start()` method is called, such as that of `ImportExportAnchorManager`, which sets up the event handler `SharingManagerConnected`.
- If the above step didn't complete within approx. 1 second (or the time Unity decides to invoke `SendConnectedNotification()`), the event handler in `ImportExportAnchorManager` is never called, which leaves us with `NullReferenceExceptions` all over the place instead of a valid `RoomManager`.

I'm currently thinking of a good way to solve this and will edit this comment accordingly.
Any thoughts on this, @NeerajW @alexdrenea?

**Comment by HodgsonSDAS** [comment]
Yeah I'm no fan of `Invoke()`.  

Another issue is that testing in the Editor is difficult because ImportExportAnchorManager only puts you in a room if `WorldAnchorStore.GetAsync(AnchorStoreReady);` completes successfully (Which it never does because we're not actually on device).
