### ISSUE TITLE
BuildTools fails when "Unity C# Projects" option checked in Unity "Build Settings" menu.

### ISSUE THREAD

**Issue by slammer8** [Microsoft/HoloToolkit-Unity#295]
## Issue

HoloToolKit BuildTool fails to build when "Unity C# Projects" option checked in Unity "Build Settings" menu.
## Steps to reproduce

Create new project
Import HoloToolKit
Open "SpatialUnderstanding" in the HoloToolkit-Examples

Set up build settings as below.
![capture](https://cloud.githubusercontent.com/assets/7374156/19493219/c5d0e1d6-9547-11e6-9140-5185f29112f5.PNG)

Use BuildTool to build

Sample build errors

> D:\Documents\Hololens Test Projects\SpatialProject\WindowsStoreApp\SpatialProject\SpatialProject.csproj(289,9): error M
> SB3030: Could not copy the file "D:\Documents\Hololens Test Projects\SpatialProject\WindowsStoreApp\GeneratedProjects\
> UWP\Assembly-CSharp\bin\x86\Debug\Assembly-CSharp.dll" because it was not found.
> 
> D:\Documents\Hololens Test Projects\SpatialProject\Assets\HoloToolkit\Sharing\Scripts\SDK\SharingClientPINVOKE.cs(1432,
> 51): error CS0234: The type or namespace name 'MarshalAs' does not exist in the namespace 'System.Runtime.InteropServic
> es' (are you missing an assembly reference?) [D:\Documents\Hololens Test Projects\SpatialProject\WindowsStoreApp\Genera
> tedProjects\UWP\Assembly-CSharp\Assembly-CSharp.csproj]
## Platform

Unity 5.5.0b7, latest HoloToolKit

**Comment by NeerajW** [comment]
Actually when trying to repro this, I discovered that Unity 5.5 does not provide APIs for enabling VR to be Windows Holographic.

**Comment by NeerajW** [comment]
When we move HoloToolkit-Unity to 5.5 builds:

**For the VR issue:**
ConfugireMenu.cs will need to look for a new string:
Unity 5.4: Metro::VR::enable:
Unity 5.5:
m_BuildTargetVRSettings:
  - m_BuildTarget: Metro
    m_Enabled: 1
    m_Devices:
    - HoloLens

**Comment by darax** [comment]
does that fix the build errors?

**Comment by NeerajW** [comment]
Build error only happens with Unity C# checked. Still investigating.

**Comment by NeerajW** [comment]
Looks like Build Window never supported compiling with the Unity C# Project option checked. Irrespective of Unity version.

I don't see any code doing it. I suspect it might have been due to not being able to resolve the necessary dependencies.

**Comment by darax** [comment]
If you build once from Visual Studio the appx build seems to work from Unity.

**Comment by NeerajW** [comment]
True. Looks like I forgot to compile from VS :) 

1. Compile using Unity Build Settings with Unity C# checked
2. Open solution
3. Change settings to Release x86 and Rebuild in VS
4. Now you can use the Build Window functionality.

Potentially some NuGet stuff is the tricky part that does not work via the Build Window.

**Comment by HodgsonSDAS** [comment]
Any change to this issue?

There have been some recent updates to the spatial understanding libraries.

**Comment by HodgsonSDAS** [comment]
@NeerajW I believe [this was fixed](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Scripts/Editor/ProjectSettingsWindow.cs#L58-L86) with https://github.com/Microsoft/HoloToolkit-Unity/pull/392, correct?

I was unable to reproduce this in the current version.

**Comment by foluis** [comment]
This worked for me http://www.imaginativeuniversal.com/blog/2017/06/24/hololens-fix-visual-studio-2017-build-error/

**Comment by StephenHodgson** [comment]
Our current build window should already support looking for and updating nuget packages.
