### ISSUE TITLE
Request for Sync System Example

### ISSUE THREAD

**Issue by HodgsonSDAS** [Microsoft/HoloToolkit-Unity#298]
I've been having issues getting the [Sync System](https://github.com/Microsoft/HoloToolkit/blob/master/Sharing/Src/Source/Docs/ExtendedDocs/SyncSystem.md) set up properly.

I was wondering if anyone had any examples they'd like to share?

**Comment by HodgsonSDAS** [comment]
@jwittner Any chance you guys have good examples you could share?

I'm just having trouble getting a listener on the root object to raise events properly.

**Comment by HodgsonSDAS** [comment]
Here's the branch I've set up for proper testing.
https://github.com/HodgsonSDAS/HoloToolkit-Unity/tree/SyncSystemTests

**Comment by NeerajW** [comment]
@jheuvel-ms any thoughts here?

**Comment by HodgsonSDAS** [comment]
Blocked by https://github.com/Microsoft/HoloToolkit-Unity/issues/311

**Comment by HodgsonSDAS** [comment]
@NeerajW please assign this to me. I'd like to learn this more and contribute what I find.
