### ISSUE TITLE
Failed to build appx from solution. Error code: 1

### ISSUE THREAD

**Issue by CaptainMM** [Microsoft/HoloToolkit-Unity#300]
When using the build window and running in Parallels I am unable to build appx from solution. I've tried changing the target to x86 and the app builds and deploys fine from VS. I'm convinced this has something to do with the build directory.

1. No spaces in targets or names
2. Latest builds. 
3. 5.4 0f3
4. Project resides on c:/ (not using mapped drive)

**Comment by NeerajW** [comment]
Are you compiling to the default App directory that is used by the window?
Could you also please paste the path of your app?

**Comment by CaptainMM** [comment]
I tried creating a separate build directory. That worked so simply removed the previous WindowsStoreApp directory and let it recreate the dir. That allows me to now build the solution successfully and the build shows below. However, I am unable to actually deploy the app now from the build window. 

_Build dir_
C:\Users\user\Source\hololens\HoloR\WindowsStoreApp

When attempting to instal from the build window
**Without "uninstall first" checked and manually removing the app from the device first.**
Error: 
System.Net.WebException: Error getting response stream (ReadDone1): ReceiveFailure ---> System.IO.IOException: EndRead failure ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host.

**With Uninstall first checked.**
Error:
System.NullReferenceException: Object reference not set to an instance of an object
  at HoloToolkit.Unity.BuildDeployPortal.InstallApp (System.String appFullPath, ConnectInfo connectInfo, Boolean waitForDone) [0x00226] in C:\Users\markmccorkle\Source\hololens\HoloR\Assets\HoloToolkit\Build\Editor\BuildDeployPortal.cs:246

**Comment by darax** [comment]
I wonder if it has to do with USB on parallels. Can you deploy to 'device' from Visual Studio?  Did you have to do anything special (like give VS permission to talk to 127.0.0.1 port 10080 on your firewall?) to enable this?

**Comment by CaptainMM** [comment]
Building from VS works fine.

**Comment by Hitomilras** [comment]
Build from VS works fine, may be, but we must pass the project in the form of .appx file and this we can't fix this issue for a long time :( 

Can someone help please :)?

**Comment by StephenHodgson** [comment]
Please open a new issue with details of the errors. Thanks
