### ISSUE TITLE
Poll: Move HoloToolkit-Unity to Unity 5.5 beta releases

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/HoloToolkit-Unity#304]
Please feel free to either express your sentiments here or on [this poll](https://forums.hololens.com/discussion/2809/holotoolkit-unity-are-we-ready-to-move-holotoolkit-and-your-projects-to-unity-5-5-beta-releases#latest).
1. We will mark a release version for the master branch for Unity 5.4. So you can still use that code.
2. Then we can move master onto Unity 5.5.
3. We want to ensure you get enough time to make this move.

We will make this move on **November 7th**. 
This gives everyone a 2 week breaking change notice.

[Reference project](https://github.com/Microsoft/HoloToolkit-Unity/projects/2).

**Comment by HodgsonSDAS** [comment]
Awesome, but I think it would be good to get things ready in the beta, but wait until the release to move the master into 5.5.  They're releasing 5.5 in November anyway.

**Comment by thebanjomatic** [comment]
Hey @NeerajW  its now November 8th, any update on the migration?

**Comment by NeerajW** [comment]
@thebanjomatic Unity is on track to release their RC builds in November. 
We will migrate then. I will publish our release plan today.
