### ISSUE TITLE
Spatial mapping stopped working

### ISSUE THREAD

**Issue by kaiomagalhaes** [Microsoft/HoloToolkit-Unity#308]
I'm using the latest version of holotoolkit, the spatial mapping worked for some days but suddenly it stoped. Now when I go to the device portal it says 'Failed to get surfaces' and everything works fine in unity. Any ideas?

**Comment by HodgsonSDAS** [comment]
What version of Unity are you using?

**Comment by kaiomagalhaes** [comment]
5.4.0f3-HTP

**Comment by HodgsonSDAS** [comment]
But you said it's not getting data from the device portal.  Sounds like it might be hardware related, do you have another device to test on?

Have you tried the [device recovery tool](https://support.microsoft.com/en-us/help/12379/windows-10-mobile-device-recovery-tool-faq)?

**Comment by kaiomagalhaes** [comment]
I'm running the Planetarium example just to make sure, because it was working just fine. See the logs below

'Planetarium.exe' (CoreCLR: DefaultDomain): Loaded 'c:\data\Programs\WindowsApps\Microsoft.NET.CoreRuntime.1.0_1.0.23819.0_x86__8wekyb3d8bbwe\mscorlib.ni.dll'. Cannot find or open the PDB file.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\entrypoint\Planetarium.exe'. Symbols loaded.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Runtime.dll'. Cannot find or open the PDB file.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\WinMetadata\Windows.winmd'. Module was built without symbols.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\UnityPlayer.winmd'. Module was built without symbols.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Runtime.InteropServices.WindowsRuntime.dll'. Cannot find or open the PDB file.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Runtime.WindowsRuntime.dll'. Cannot find or open the PDB file.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\WinRTBridge.winmd'. Cannot find or open the PDB file.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\BridgeInterface.winmd'. Module was built without symbols.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Collections.dll'. Cannot find or open the PDB file.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\UnityEngine.dll'. Symbols loaded.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\Assembly-CSharp.dll'. Symbols loaded.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\UnityEngine.Networking.dll'. Symbols loaded.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\UnityEngine.UI.dll'. Symbols loaded.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.IO.dll'. Cannot find or open the PDB file.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Net.Primitives.dll'. Cannot find or open the PDB file.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Private.Networking.dll'. Cannot find or open the PDB file.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Reflection.Primitives.dll'. Module was built without symbols.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Reflection.dll'. Module was built without symbols.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\UnityEngine.HoloLens.dll'. Symbols loaded.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Threading.Tasks.dll'. Cannot find or open the PDB file.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Private.Uri.dll'. Cannot find or open the PDB file.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Text.Encoding.dll'. Module was built without symbols.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Runtime.InteropServices.dll'. Cannot find or open the PDB file.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Threading.dll'. Cannot find or open the PDB file.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Diagnostics.Debug.dll'. Cannot find or open the PDB file.
Module information:
 Built with Compiler Ver '190023026'
 Built from '5.4/platform/winrt/hololens' branch
 Version is '5.4.0f3-HTP (b21dfedb4779)'
 Debug build
 Application type 'D3D11'
 Used 'UWP'

PlayerConnection initialized from C:/Data/Users/DefaultAccount/AppData/Local/DevelopmentFiles/PlanetariumVS.Debug_x86.kaioc/Data (debug = 0)

PlayerConnection initialized network socket : 0.0.0.0 55101

Multi-casting "[IP] 192.168.80.2 [Port] 55101 [Flags] 2 [Guid] 800108582 [EditorId] 4294967295 [Version] 1048832 [Id] MetroPlayerX86(HoloLens-026RG) [Debug] 0" to [225.0.0.222:54997]...

GfxDevice: creating device client; threaded=1

Direct3D:

    Version:  Direct3D 11.0 [level 11.0]

    Renderer: Microsoft RemoteFX Graphics Device - WDDM (ID=0x2c1)

    Vendor:   Microsoft

    VRAM:     639 MB

Initialize engine version: 5.4.0f3-HTP (b21dfedb4779)

'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Runtime.Extensions.dll'. Cannot find or open the PDB file.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\UnityEngineProxy.dll'. Cannot find or open the PDB file.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\UnityEngine.VR.dll'. Symbols loaded.
'Planetarium.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\PlanetariumVS.Debug_x86.kaioc\System.Linq.dll'. Cannot find or open the PDB file.
Shader 'Legacy Shaders/Diffuse': fallback shader 'Legacy Shaders/VertexLit' not found

Capability 'internetClient' is required, please enable it in Package.appxmanifest because you're using WWW functionality.
 
(Filename: C:\buildslave\unity\build\PlatformDependent/MetroPlayer/MetroCapabilities.cpp Line: 126)


Disabling independent input source.

Logical Screen DPI is 144.00.

Begin showing splash screen.

The following GlobalManagers were stripped from the build (Either because they're not used or not supported on this platform):
  NetworkManager
  MasterServerInterface
  UnityAdsSettings
  ClusterInputManager
  UnityAnalyticsManager

Resolution: Switching to 1266 x 720 Fullscreen: True

Resolution: ApplicationView::IsFullScreenMode = False

Resolution: Entering fullscreen mode...

Resolution: Resizing swapchain to 1266 x 720 Fullscreen: True

Resolution: Done.

UnloadTime: 9.177900 ms

Starting the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Setting up 1 worker threads for Enlighten.

  Thread -> id: 5b8 -> priority: 1 

Stopping the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Finished making planes.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Starting the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


The thread 0xb2c has exited with code 0 (0x0).
The thread 0x2c8 has exited with code 0 (0x0).
Stopping the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Finished making planes.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Starting the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


The thread 0x608 has exited with code 0 (0x0).
Stopping the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Finished making planes.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Starting the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


The thread 0x664 has exited with code 0 (0x0).
Stopping the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Finished making planes.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Starting the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


The thread 0x704 has exited with code 0 (0x0).
Stopping the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Finished making planes.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Starting the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


The thread 0x488 has exited with code 0 (0x0).
Stopping the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Finished making planes.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Starting the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


The thread 0x260 has exited with code 0 (0x0).
Stopping the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Finished making planes.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Starting the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


The thread 0xadc has exited with code 0 (0x0).
The thread 0x254 has exited with code 0 (0x0).
Stopping the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Finished making planes.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Starting the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


The thread 0xf28 has exited with code 0 (0x0).
Stopping the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Finished making planes.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Starting the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)

**Comment by kaiomagalhaes** [comment]
@HodgsonSDAS My partner is facing the same problem in his computer. Now I'm going to format my windows just to make sure

**Comment by HodgsonSDAS** [comment]
If it's happening on multiple devices, then it might be software related. 

Please in the future, upload your log file and not post it directly in the thread. It's hard to read that way.

**Comment by kaiomagalhaes** [comment]
@HodgsonSDAS alright, edited my message with a gist link, hope it helps.

**Comment by HodgsonSDAS** [comment]
Yeah we've made some changes to the spatial mapping components over the last week to get it to work in the emulator and while using the Holographic Remoting feature.  It's possible something could have broken.

Could you make a sample scene that can reproduce this for us?

@darax Any thoughts on this?

**Comment by kaiomagalhaes** [comment]
The spatial processing test scene isn't working anymore.

**Comment by HodgsonSDAS** [comment]
Okay, give me a few minutes to test this out on my end.

**Comment by HodgsonSDAS** [comment]
Confirmed. Spatial Mapping broken.

**Comment by kaiomagalhaes** [comment]
Any ideas about when it will be fixed? My company has a product which is based on spatial mapping and we can't do a demo until it is fixed.

**Comment by NeerajW** [comment]
@kaiomagalhaes and @HodgsonSDAS @darax  and I just verified the SpatialProcessing scene on Unity 5.5 b7 and Unity 5.4 f3 and it worked both in editor and on HoloLens.
We debugged the scene and saw no error messages or incorrect stacks. Spatial Mapping rendered well and generated planes after say 30 seconds correctly.
Starting the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Setting up 1 worker threads for Enlighten.

  Thread -> id: e24 -> priority: 1 

Stopping the observer.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Finished making planes.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)


Finished removing vertices.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)

1. What is the error stack you see?
2. What device build are you on?
3. Can you ensure you have SpatialPerception enabled in your Unity app and generated VS solution?

**Comment by kaiomagalhaes** [comment]
@NeerajW 

1 - 
```
Starting the observer.

(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)

The thread 0xb2c has exited with code 0 (0x0).
The thread 0x2c8 has exited with code 0 (0x0).
Stopping the observer.

(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)

Finished making planes.

(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)

Starting the observer.

(Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/UnityEngineDebugBindings.gen.cpp Line: 45)

The thread 0x608 has exited with code 0 (0x0).
Stopping the observer.
```

As you can see it starts and stops the observer a lot of times, in my gist above you can see its full version. 

2 - I'm on my notebook and my partner in a PC

3 - Yes, the spatial perception is enabled in my unit app, but not sure how I could ensure it in the generated VS solution

**Comment by kaiomagalhaes** [comment]
@NeerajW 

@HodgsonSDAS also faced the exactly same issue that I did

**Comment by keveleigh** [comment]
@kaiomagalhaes To check if Spatial Perception is enabled in the generated VS solution, right click on Package.appxmanifest in the Solution Explorer in VS, click View Code, and see if `<uap2:Capability Name="spatialPerception" />` is under `<Capabilities>`

**Comment by darax** [comment]
Have you tried a release build instead of a debug build?

**Comment by kaiomagalhaes** [comment]
Thanks @keveleigh, I'm going to try it today.

@darax I have tried in release, master and debug.

I've formatted my machine today just to make sure and I'm going to check the spatialPerception in the appxmanifest later today.

**Comment by darax** [comment]
okay, I just tried in debug, on my PC, and it worked.  Do make sure that you've pulled the latest HoloToolkit.  Without my changes I would have seen what you did in the log you posted.

**Comment by kaiomagalhaes** [comment]
Hey guys, I updated my computer and as the 5.4.0f3-HTP wasn't available to download (broken link) I downloaded the 5.5.0b9 and it worked just fine. Not sure if it is something with the version, as my partner with the 5.4.0f3-HTP is still facing the issue and @darax faced the same problem it may be something to keep digging. 

Tomorrow I'm going to have my partner updating his unity to see if it works.

**Comment by HodgsonSDAS** [comment]
@darax @NeerajW  Yes the capabilities were enabled for Spatial Perception.
Editor: Unity 5.4.0f3-HTP
Build: x86 Release
Windows Holographic OS: 10.0.14393.321
Firmware revision 005.05.P.1606291233R

**Comment by HodgsonSDAS** [comment]
I was able to narrow it down I think.  If you already have a good portion of the room mapped then it works fine, but when you move to map a new surface is when the error occurs.

**Comment by kaiomagalhaes** [comment]
Update:

With the version 5.5.0b9 it works just fine in debug, master and with the released app. For some reason,my 3D view says that the device is not connected, but I don't know if it is related. 
Also with the 5.5.0b9 it worked with my friend as well, so it is no an isolated case.

**Comment by darax** [comment]
@HodgsonSDAS  that's what the processing scene is supposed to do. 

@kaiomagalhaes it sounds like you are unblocked. Am I wrong?

**Comment by HodgsonSDAS** [comment]
Ah okay, well I'm still getting the `The thread has exited with code 0 (0x0).`

**Comment by kaiomagalhaes** [comment]
Yes @darax I'm unblocked.

**Comment by HodgsonSDAS** [comment]
So the spatial perception is only working for the 5.5 beta?

**Comment by kaiomagalhaes** [comment]
@HodgsonSDAS it is the conclusion I came through.

**Comment by darax** [comment]
It's working in 5.4 for Neeraj and me.  

The thread exited message is likely a red herring.  I see those all the time.

**Comment by HodgsonSDAS** [comment]
So I tested my own scenes and it's working fine. 

I think the thing that threw me off was the error codes and seeing white all the sudden. Seemed like it just showed the tracking lost but if the white planes are intended then I guess it's working haha. Seeing all that white made me think it crashed.

**Comment by darax** [comment]
okay, I'll cancel the apt with my therapist. :)

**Comment by kaiomagalhaes** [comment]
So can I close the issue @HodgsonSDAS @darax ?

**Comment by HodgsonSDAS** [comment]
It's hard to work remotely like this sometimes 😆
