### ISSUE TITLE
Visual Studio Build fails in Unity 5.5 beta

### ISSUE THREAD

**Issue by kotAPI** [Microsoft/HoloToolkit-Unity#310]
Visual Studio builds are successful on the 5.4 but seem to be failing if the solution is being built from 5.5 beta version of Unity via WiFi deploy. It doesn't throw any error but says "remote device is taking too long to respond" and fails eventually. I migrated the 5.5 project to the stable Unity version(5.4) and built the VS solution and it deploys successfully like they used to originally. It's kind of annoying to switch between the versions because Holographic Remoting makes life so much easier and the scenes from 5.5 can't be opened in 5.4 coz of different versions. I'm assuming this is a Unity issue since it's in Beta,  Is this a known issue or am I doing something wrong?

**Comment by HodgsonSDAS** [comment]
Are you completely deleting your exported folder on each build?

**Comment by kotAPI** [comment]
I've tried both, I did fresh builds and replaced old builds with the new ones. I've built a couple of other apps and they build perfectly with the beta. I've no clue why my project doesn't build. Do builds fail if the app is heavy? I'm currently using couple of heavy mesh(about 70mb) models in my project.

**Comment by NeerajW** [comment]
@kotAPI I've deployed apps with over that and worked. Perhaps try deploying with fewer assets first if you think your WiFi is unable to handle so much data?

**Comment by kotAPI** [comment]
@NeerajW you're probably right, the builds seem to be failing if the meshes are heavy. I think this question can be closed, thanks for the help guys.
