### ISSUE TITLE
Sync System: root object added listener does not raise events properly

### ISSUE THREAD

**Issue by HodgsonSDAS** [Microsoft/HoloToolkit-Unity#311]
I'm just having trouble getting a listener on the root object to raise events properly.
```
RootSyncObject = SharingStage.Instance.Manager.GetRootSyncObject();
objElementAdapter = new ObjectElementAdapter();
objElementAdapter.ElementAddedEvent += OnElementAdded;
objElementAdapter.ElementDeletedEvent += OnElementDeleted;
RootSyncObject.AddListener(objElementAdapter);
```
I'm getting the root object and adding a listener but that listener never raises `ElementAddedEvent` nor `ElementDeletedEvent`.

Here's the branch I've set up for proper testing:
https://github.com/HodgsonSDAS/HoloToolkit-Unity/tree/SyncSystemTests

1. Open `SyncSystemTests.unity`
2. Add breakpoints to `ObjectElementAdapter.cs` lines 34, 123, & 137.
3. Start Debugging in visual studio and attach to Unity Editor.
4. Run the `SyncSystemTest.unity` scene.
5. Create/Delete object object and int elements.
6. Increment and decrement int value.
7. Observe events not raised.

**Comment by HodgsonSDAS** [comment]
Blocks https://github.com/Microsoft/HoloToolkit-Unity/issues/298

**Comment by HodgsonSDAS** [comment]
@jwittner any ideas?

**Comment by Ziugy** [comment]
I've noticed similar behaviour in regards to this. Listening to the SyncMessage on the server connection and registering a callback on the NetworkConnectionAdapter's MessageReceivedCallback you would find that the other clients gets the changed events. I think there's something in the underlying HoloToolkit.Sharing that's not processing the operations.

**Comment by jwittner** [comment]
I'm using a version of this library in an application that's a couple months older than the latest. I'm wondering if we're seeing a recently introduced issue.

**Comment by HodgsonSDAS** [comment]
Debugging shows that the listener registers events properly but seems like they never get raised.

**Comment by Ziugy** [comment]
I uncommented #define SYNC_DEBUG in CommonSettings.h to enable further debugging of this. Looks like Modify and Ack operations are getting sent between my clients, but like you said the Unity events aren't getting raised. To investigate this further I added extra debugging in the ModifyOperation's Notify method. For me it looks like the parentElement is always "Root". The modifiedElement is correct. I would have thought the parent element was the ObjectElement name that I attached my primitive elements to. After seeing this I listened directly to the root sync and I'm seeing those events in Unity fire.

**Comment by Ziugy** [comment]
I can confirm that events are firing properly. I just had an initialization issue within my project. Fixing that cause all my events to fire properly. I'm going to compare the setup of my project with what you've created to see where we differ.

**Comment by HodgsonSDAS** [comment]
Thanks @Ziugy that would be really helpful.

**Comment by Ziugy** [comment]
I downloaded your repo, but I'm not seeing a SyncSystemTests.unity scene.

**Comment by HodgsonSDAS** [comment]
Were you able to find it?

https://github.com/HodgsonSDAS/HoloToolkit-Unity/blob/SyncSystemTests/Assets/HoloToolkit/Sharing/Tests/SyncSystemTest.unity

/Stephen

**Comment by Ziugy** [comment]
I've attached a patch with the changes I've made to your repository that fixes the int case. The room connection really isn't needed. You needed to listen to the IntChangedEvent on the ObjectElement where the IntElement is a child of. In the OnElementAdded and OnElementDeleted methods you also needed to properly handle the IntElement being past in. Hopes this helps!

[patch.zip](https://github.com/Microsoft/HoloToolkit-Unity/files/581446/patch.zip)

**Comment by HodgsonSDAS** [comment]
@Ziugy You sir are a scholar and a saint.

**Comment by HodgsonSDAS** [comment]
Shouldn't the listener on the root object raise OnElementAdded when creating ObjectElements?

**Comment by HodgsonSDAS** [comment]
@Ziugy were you able to get the RootObject to raise an event when adding ObjectElements?

**Comment by Ziugy** [comment]
D'oh, looks like it was. Pull request makes much more sense! Done. You should see the add/delete event for ObjectElements too, but I didn't test that. Only investigated the IntElement for you.

Note that for every ObjectElement you need to AddListener to receive that ObjectElement's events. The change events don't propagate up to the root.

**Comment by HodgsonSDAS** [comment]
Hehe, no worries. I really appreciate you looking at this.

**Comment by HodgsonSDAS** [comment]
Merged your pull request but I still can't get the events to fire though.

**Comment by Ziugy** [comment]
Oh, events don't get fired on the local client. You should keep setting the intValueText in TestCreateIntValue and TestDeleteIntValue.

**Comment by HodgsonSDAS** [comment]
Oh, okay so then it doesn't raise events locally by design?
