### ISSUE TITLE
Formatting Guidelines

### ISSUE THREAD

**Issue by HodgsonSDAS** [Microsoft/HoloToolkit-Unity#312]
I'd like to discuss creating a formatting document for use in the HoloToolkit that sets some ground rules about formatting and styles.

for example:

- Using explicit vars instead of implicit.
- Using explicit private modifier for all Unity specific methods.
- Using `[SerializeField]` instead of public fields to set values in the editor.
- etc.

Please add suggestions and discuss the pros and cons of each.

**Comment by NeerajW** [comment]
Here are some [.NET framework guidelines provided by Microsoft](https://msdn.microsoft.com/en-us/library/ms229043(v=vs.110).aspx).
Have you found something similar for Unity?

We've tried to keep this project simple on those and mainly follow the current convention style classes.

**Comment by HodgsonSDAS** [comment]
yeah, those .NET framework guidelines are included in this as well, but I think most of use follow that by default anyway. 

Having a list of other things not covered by that might be helpful.
