### ISSUE TITLE
Failing WACK Compliance

### ISSUE THREAD

**Issue by mister-liss** [Microsoft/HoloToolkit-Unity#315]
Holotoolkit-Unity is failing WACK compliance. I was testing my own changes and noticed the failure. I cloned a clean repo at commit 82fc64462b987f1d572d0db9bb3b39fe8f1a56f0 and found the same failure. This likely goes further back. Below is the output of the failing test from WACK.

Supported API test

FAILED
Supported APIs
Error Found: The supported APIs test detected the following errors:
API D3D12GetDebugInterface in d3d12.dll is not supported for this application type. UnityPlayer.dll calls this API.
API OpenSemaphore in api-ms-win-core-synch-l1-1-0.dll is not supported for this application type. System.Threading.dll calls this API.
API CreateSemaphore in api-ms-win-core-kernel32-legacy-l1-1-0.dll is not supported for this application type. System.Threading.dll calls this API.
API ExecuteAssembly in uwphost.dll is not supported for this application type. HoloToolkit-Unity.exe calls this API.
API DllGetActivationFactory in uwphost.dll is not supported for this application type. HoloToolkit-Unity.exe has an export that forwards to this API.
Impact if not fixed: Using an API that is not part of the Windows SDK for Windows Store apps violates the Windows Store certification requirements. 
How to fix: Review the error messages to identify the API that is not part of the Windows SDK for Windows Store apps. Please note, apps that are built in a debug configuration or without .NET Native enabled (where applicable) can fail this test as these environments may pull in unsupported APIs. Retest your app in a release configuration, and with .NET Native enabled if applicable. See the link below for more information: 
Alternatives to Windows APIs in Windows Store apps.

**Comment by darax** [comment]
are you building Master?

**Comment by mister-liss** [comment]
I'm building Release. Should I be building Master?

**Comment by angelaHillier** [comment]
Yes, Master is required for store submission.

**Comment by NeerajW** [comment]
Please reopen if you still see issues with Master x86.
