### ISSUE TITLE
Manual Camera Control - should it be disabled if not in editor?

### ISSUE THREAD

**Issue by darax** [Microsoft/HoloToolkit-Unity#322]
The update function takes up a little bit of hopefully unnecessary processing when on device.

**Comment by S-Hodgson-MMOARgames** [comment]
I agree, the whole class should be wrapped in an `#if UNITY_EDITOR`

**Comment by HodgsonSDAS** [comment]
Actually should be `#if UNITY_EDITOR || UNITY_STANDALONE`

**Comment by NeerajW** [comment]
Fixed with #324
