### ISSUE TITLE
Input test scene SelectedObjectKeywords crashes

### ISSUE THREAD

**Issue by aalmada** [Microsoft/HoloToolkit-Unity#329]
Scene [SelectedObjectKeywords](https://github.com/Microsoft/HoloToolkit-Unity/blob/4cf37b7ddabca8db0030b0f527341455e13f52d3/Assets/HoloToolkit/Input/Tests/Scenes/SelectedObjectKeywords.unity) crashes on startup in [Cursor.RegisterManagers() when adding the global listener](https://github.com/Microsoft/HoloToolkit-Unity/blob/4cf37b7ddabca8db0030b0f527341455e13f52d3/Assets/HoloToolkit/Input/Scripts/Cursor/Cursor.cs#L208).

Stack trace:
   at HoloToolkit.Unity.InputModule.Cursor.RegisterManagers()
   at HoloToolkit.Unity.InputModule.Cursor.Start()
   at HoloToolkit.Unity.InputModule.Cursor.$Invoke22Start(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method)

**Comment by maxouellet** [comment]
Should be fixed by pull request #330 , once it goes in

**Comment by HodgsonSDAS** [comment]
@aalmada can you confirm that this is now fixed?

**Comment by HodgsonSDAS** [comment]
@aalmada can you confirm that this is now fixed?

**Comment by HodgsonSDAS** [comment]
@aalmada, @maxouellet can you confirm that this is now fixed?

**Comment by keveleigh** [comment]
It isn't crashing anymore, but I'm not sure if I'm seeing the expected behavior. The keywords work, but should I be able to use the Tap gesture to select as well? Also, on a Tap/Hold gesture, the cursor disappears until I release it.

**Comment by aalmada** [comment]
Sorry for delay. I can confirm that it doesn't crash.
@keveleigh I agree that on a app both keyword and tap should work. This seem to be a test scene for a particular feature. The PR #354 allows a much cleaner solution when supporting both features. The MonoBehavior just has to implement interfaces 'IInputClickHandler' and 'ISpeechHandler' and share the rest of the code.

**Comment by HodgsonSDAS** [comment]
So we can close this issue?
