### ISSUE TITLE
HoloToolkit-Unity release plan

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/HoloToolkit-Unity#336]
![image](https://cloud.githubusercontent.com/assets/13281538/20494904/c440abfc-afd3-11e6-939e-42df706bd2a0.png)

I will keep this thread posted if there are any changes. Happy Thanksgiving :)

**Comment by NeerajW** [comment]
[Release version v1.5.4.0](https://github.com/Microsoft/HoloToolkit-Unity/tree/v1.5.4.0) has been completed. If your application wants to use that release, please free to clone the link into your custom folder.

**Comment by HodgsonSDAS** [comment]
FYI, Unity 5.5 was released today.

**Comment by HodgsonSDAS** [comment]
FYI, Unity 5.5.0p1 was released today.

**Comment by HodgsonSDAS** [comment]
FYI, Unity 5.5.0p2 was released today.

Fixes:
(none) - HoloLens: Fixed a crash in Editor when terminating Remoting App during an active Holographic Remoting session.
(848237) - HoloLens: Improved error reporting when failing to load PerceptionRemotingPlugin.dll (used by Holographic Remoting).

**Comment by HodgsonSDAS** [comment]
@NeerajW would you like to keep this issue open for future release announcements or close?

**Comment by HodgsonSDAS** [comment]
FYI, Unity 5.5.0p4 was released today.

Fixeds:

- (858208) AR: Fixed a crash when exiting play mode during a Holographic Simulation session.

**Comment by HodgsonSDAS** [comment]
@NeerajW I'm going to go ahead and close this since the release plan has effectively been executed.
