### ISSUE TITLE
HoloToolkit-Example TextPrefabSamplesTest broken with Missing Prefab error

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/HoloToolkit-Unity#346]
**Repro steps:**
1. Sync to latest master HTK-U
2. Open project using Unity 5.4 releases
3. Open HoloToolkit-Examples\Text\TextPrefabSamplesTest scene

**Observe issue:**
![image](https://cloud.githubusercontent.com/assets/13281538/20687028/bea0580e-b56f-11e6-86ef-9db4656d7ac4.png)

I guess this could be due to either some different version of Unity being used to check in or may be the font dependency? The original prefabs look fine though. It's hard to tell what these prefabs are.

**Comment by cre8ivepark** [comment]
Those are the four text & sample prefabs added as part of #339 
This test scene is just having them in the hierarchy. Let me try with different version.
![2016-11-28 13_49_25-unity personal 64bit - textprefabsamplestest unity - textprefabtest5 - pc mac](https://cloud.githubusercontent.com/assets/13754172/20687494/83695c52-b571-11e6-9302-26a52db55698.png)

**Comment by NeerajW** [comment]
@dbastienMS just mentioned to me that you might be missing meta files.
True indeed: You don't have a meta file checked in for TextPrefabSamplesTest.meta
Also missing meta files for you 3DTextPrefab and other files.
Please add the meta files for all of them.

**Comment by cre8ivepark** [comment]
Created new pull request with added .meta files.
Thank you!

**Comment by NeerajW** [comment]
Still broken. Looks like there is a Scripts.meta but no Scripts folder to go with it.

**Comment by NeerajW** [comment]
Great. That issue is now fixed :)
Only new issue I see in the test scene is:

3DTextPrefab is missing the shader. This shader does not exist on the main prefab in UI\Prefabs.
Perhaps this needs to be fixed:
1. To point to HoloToolkit\3DTextShader
2. Also apply this same shader to the prefab

![image](https://cloud.githubusercontent.com/assets/13281538/20721055/5d0433de-b616-11e6-918d-dbce4cd4978d.png)

**Comment by HodgsonSDAS** [comment]
@NeerajW the shader probably just needs to be recompiled.

**Comment by NeerajW** [comment]
@HodgsonSDAS nope. There was a shader namespace change and it had to be re-applied to the component.

**Comment by NeerajW** [comment]
Fixed with PR #351
