### ISSUE TITLE
HeadsupDirectionIndicator introduced a bad namespace

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/HoloToolkit-Unity#355]
https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Scripts/HeadsUpDirectionIndicator.cs

namespace HoloToolKit instead of namespace HoloToolkit

**Comment by NeerajW** [comment]
Thanks @darax for finding it :)

**Comment by keveleigh** [comment]
Fixed with #356
