### ISSUE TITLE
Shader Warning for Custom/Unlit_glass_button

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/HoloToolkit-Unity#357]
```
Shader warning in 'Custom/Unlit_glass_button': Output value 'vert' is not completely initialized at line 62 (on d3d11)

Compiling Vertex program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING SHADER_API_DESKTOP UNITY_HARDWARE_TIER3 UNITY_COLORSPACE_GAMMA
```

**Comment by NeerajW** [comment]
@dbastienMS is this something you might some time to look into?

**Comment by keveleigh** [comment]
This is also a shader specific to a test scene and in the Tests/Shaders folder. Is it needed to show off the actual test scene functionality? Is it something we'd want to move to the HoloToolkit namespace and ship? It seems unnecessary to me to add textures, materials, shaders, etc. just for test scenes, but I'm curious what others think.

**Comment by dbastienMS** [comment]
Looks like the w component of uv isn't being written in the vertex shader.  
UNITY_INITIALIZE_OUTPUT(v2f, o); at the top of the vertex shader will fix it, or just setting w to 0.

Shader also doesn't support stereo instancing.

**Comment by dbastienMS** [comment]
And yeah I agree it seems unnecessary - it's a maintenance cost.  Also doesn't look like it respects the near plane fade.

**Comment by HodgsonSDAS** [comment]
I think good examples of shaders is needed for those who are learning, but they should be kept strictly in the tests/examples folders.

**Comment by StephenHodgson** [comment]
Closing this issue in favor of https://github.com/Microsoft/HoloToolkit-Unity/issues/515. 

That issue should address this one by making existing materials use standard HTK shaders.
