### ISSUE TITLE
Question: Is anyone else getting Timestamps and assets out of sync with 5.5.0f3?

### ISSUE THREAD

**Issue by HodgsonSDAS** [Microsoft/HoloToolkit-Unity#358]
I already submitted a ticket with Unity, but I'd like to make sure I'm not the only one.

Seems to happen in any project I've ported from the HTK editors and seems to always involves the same 3 guids:
```
Asset with GUID 67e9dad5654047ebbe623cce9dbf7b38 has empty path but has assettimestamp???
Asset with GUID 52a206b72a8f4f749c28d8b18b42dd19 has empty path but has assettimestamp???
Asset with GUID f48df919adea4fa095a7407e773e5aa4 has empty path but has assettimestamp???
```

None of these projects I'm getting this warning in shares assets nor code.
I've already tried deleting the Library, Temp folders, and all project .meta files but still returns.
All 3 GUIDs seem to point to:
```
C:/Program Files/Unity/Editor/Data/PlaybackEngines/MetroSupport/Managed/UAP/UnityEngine.Networking.dll
```

**Comment by aalmada** [comment]
Noticed it just now too

**Comment by jessemcculloch** [comment]
Yeah, this has actually been happening through all the the 5.5 beta builds as well.  I basically just ignore the error, it doesn't seem to cause anything to break or builds to fail...

**Comment by HodgsonSDAS** [comment]
...That we know of...

**Comment by NeerajW** [comment]
@ChimeraScorn is this something we could ask Unity folks?
@HodgsonSDAS a screen shot would be perfect.

**Comment by jessemcculloch** [comment]
![image](https://cloud.githubusercontent.com/assets/11747005/20854342/e5473b40-b8a7-11e6-8971-fde4fa920b25.png)

**Comment by HodgsonSDAS** [comment]
Status Update:
https://issuetracker.unity3d.com/issues/unity-does-not-rebuild-guid-cache-on-boot

**Comment by HodgsonSDAS** [comment]
5.5.0p1 Fixes this issue.
