### ISSUE TITLE
KeywordManager keeps listening when inactive

### ISSUE THREAD

**Issue by r2d2rigo** [Microsoft/HoloToolkit-Unity#359]
The current implementation of `KeywordManager` starts listening for voice commands when the script's `Start` function is called. However, the underlying `KeywordRecognizer` object is only stopped when the script is being destroyed - if the script (or any parent in the hierarchy) is deactivated, it keeps responding to voice commands (key bindings work correctly though, since these are processed in the `Update` method).

`KeywordManager` should check when it is deactivated and stop responding to voice commands until it is activated again.

**Comment by r2d2rigo** [comment]
Hello @HodgsonSDAS, I have just submitted a PR with the fix (#360) - not sure if it would be better than integrating it in @aalmada's one.

**Comment by HodgsonSDAS** [comment]
As long as you sign the CLA you should be good @r2d2rigo.  I just thought it'd save on a PR, but really they should be separate if addressing different issues.

**Comment by r2d2rigo** [comment]
Thanks, I'm on it - just waiting for the DocuSign email to arrive.

**Comment by keveleigh** [comment]
Fixed with #360
