### ISSUE TITLE
Keyboard shortcuts 

### ISSUE THREAD

**Issue by alexdrenea** [Microsoft/HoloToolkit-Unity#36]
I'm wondering if you guys think it would be useful to add a keyboard shortcut to the KeywordManager. 
I find it easier to debug/test my actions in the unity player rather than deploy all the way to the HoloLens (or emulator).
So to that end I was thinking of adding ability to trigger a Keyword action by pressing a key on the keyboard.

**Comment by keveleigh** [comment]
As an additional note, you can actually use the voice commands in the editor if you have a microphone attached and are using Windows 10.

**Comment by alexdrenea** [comment]
Interesting. I believe I tried that and it didn't work. I'll try again.
But even then, you might want a "silent trigger" so you don't annoy everyone around.

**Comment by UWarbs** [comment]
It seems in that case you can just call your method on a keyup event. 

`if(Input.GetKeyUp(KeyCode.A)) {
  //code
}`

**Comment by jwittner** [comment]
I do this very same thing as well and found it extremely useful in the editor and the emulator. I'd lean towards a solution that's separate from the keyword manager, but structured similarly. So that you could setup keybindings to anything and not just things related to keywords.

**Comment by alexdrenea** [comment]
I actually tried both solutions - KeyBindingManager
The downside to the separation is that you need to re-hook up all the commands and objects to the second manager, and if you need to change one, you need to change it in both places.
So other than the separation of concerns, I think it's easier and move convenient to add the keybinding in the keyword manager.

I can make a pull-request for one or the other and see what other comments we get?

**Comment by jwittner** [comment]
Yeah, keeping them in sync creates an annoyance, but the separation buys you a lot of power for keybindings. I guess having a KeyBindingManager doesn't prevent bindings on the KeywordManager as well, though the overlap might be confusing.

**Comment by alexdrenea** [comment]
Resolved by #37
