### ISSUE TITLE
HoloToolkit Apply HoloLens Project Settings not setting virtual reality enabled

### ISSUE THREAD

**Issue by jessemcculloch** [Microsoft/HoloToolkit-Unity#365]
When using the Apply HoloLens Project Settings HoloToolkit menu item, the Boolean for Virtual Reality Enabled is not getting marked as it's supposed to be.

**Comment by HodgsonSDAS** [comment]
Confirmed.

**Comment by jbienzms** [comment]
This code is unfortunately a little fragile. It's in [this file](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Editor/ConfigureMenu.cs) at line 122 and it uses a lot of RegEx parsing. Does anyone know what the strings should be changed TO? I guess we could enable it in a project and look at that. I'll see if I can get to this on Sunday. I'm working on some toolkit related things anyway.
