### ISSUE TITLE
InputManager OnFocusEnter, OnFocusExit Events Reversed

### ISSUE THREAD

**Issue by tshadle** [Microsoft/HoloToolkit-Unity#366]
In InputManager.cs, lines 355 and 364 reverse references to `OnFocusExitEventHandler` and `OnFocusEnterEventHadler`. As a result `OnFocusEnter` and `OnFocusExit` fire in the wrong order.

Also, `OnFocusEnterEventHadler` contains a typo.

To test, run `ColorPickerExample`. It's currently broken. Reverse the refs in InputManager.cs to fix.

Thanks.

**Comment by jessemcculloch** [comment]
Yeah, I am seeing the same thing.  Put in some debug log statements on onFocusEnter and Exit, and they are firing opposite

**Comment by aalmada** [comment]
I checked the code and they really are reversed: https://github.com/Microsoft/HoloToolkit-Unity/blob/63dabf4826332a82ff369569a7f1d7435b9ebb48/Assets/HoloToolkit/Input/Scripts/InputManager.cs#L353-L369

**Comment by HodgsonSDAS** [comment]
Sorry guys, I think that was my fault.
