### ISSUE TITLE
ProjectSettings folder contains many unneeded files overwriting user values

### ISSUE THREAD

**Issue by yoDon** [Microsoft/HoloToolkit-Unity#375]
There are a ton of settings files in checked into the repo that have nothing to do with enabling Holographic functionality and which will overwrite the user's existing files of the same name.

My guess is you just need the ProjectSettings and possibly AudioManager files, but it would be WAY nicer if instead of even including those files there was just a menu item that set the small number of required settings the way they need to be for Holographic projects to work properly (I spent almost 4 hours last night repeatedly building and rebuilding my project trying to figure out what combination of build and project settings was required vs. recommended vs. not supported). Then you wouldn't need to include any of these settings files.

**Comment by keveleigh** [comment]
These files aren't really included for you to overwrite your own ProjectSettings with. They're included so you can open the HoloToolkit-Unity repo itself in Unity as a project. Each component calls out (or should) the necessary project settings needed to use them. Really, you only need to copy the Assets (and then, maybe even just the HoloToolkit folder in Assets) and External folders into your project.

We do have scripts in https://github.com/Microsoft/HoloToolkit-Unity/tree/master/Assets/HoloToolkit/Utilities/Editor, which should show up as a dropdown in Unity when imported and allow you to set the recommended settings all in one place.

**Comment by yoDon** [comment]
I see now - your intent is that we pull the repo as a clean Unity project, open the project, export a unity package from it, and then import that package into our working project. That's a sensible approach, it's just not what I was expecting while downloading things.

**Comment by keveleigh** [comment]
That makes sense! It's probably something we should call out in our README as well, probably once we flesh out our versioning and .unitypackage release plan.

I also typically just copy the folders themselves into my project, but your steps probably preserve the meta files and whatnot better by moving assets the Unity way.

**Comment by HodgsonSDAS** [comment]
@yoDon, if you're looking for unity packages to just import into your own projects, here's a auto build @riverar has so kindly put together for us:  https://riverar.github.io/HoloToolkit-Unity-Builds/

**Comment by jessemcculloch** [comment]
I second the recommendation for using the package builder that @riverar has built

**Comment by yoDon** [comment]
If @riverar's unity package is the preferred install method (which makes sense to me), shouldn't it be listed at the top of the readme?

**Comment by HodgsonSDAS** [comment]
@yoDon I've already addressed that in my latest PR

**Comment by yoDon** [comment]
I recommend instead moving the existing README sentence that points at the install instructions ("To learn how to add the HoloToolkit to your project see the Getting Started guide") forward to in the file the point where you're proposing to add the link to riverar's project, and then discussing riverar's project inside the instructions page.

At present, your PR is sort of trying to turn the main readme into a partial install instructions page, but doing so incompletely (if one were visiting the repo for the first time without having read the thread on this issue page, it's unlikely one would read the added sentence "To download the latest or archived versions check out the [HoloToolkit Archive](https://riverar.github.io/HoloToolkit-Unity-Builds)" as saying that's the recommended install approach, it sounds more like a place with an archive of zips).

That said, I don't want to come across as overly pedantic here, so I'm happy to close the issue or have you close it if you want to leave your PR as is

**Comment by HodgsonSDAS** [comment]
No you bring up good points, I'll make the update in the PR.

**Comment by jessemcculloch** [comment]
I wrote up a blog post about installing the HoloToolkit a couple months ago.  You are welcome to poach any/all of it for the readme if you want.  I wrote it before knowing about the Builds that riverar was doing, but it wouldn't take much to add that in.  https://wordpress.com/post/hololensjournal.com/46

**Comment by HodgsonSDAS** [comment]
@jessemcculloch  your link takes me to a login page.  Do you have a direct link?

**Comment by jessemcculloch** [comment]
Yeah, sorry, my bad, forgot I was logged in as admin on the blog.  Here you go.  https://hololensjournal.com/2016/09/14/jumpstarting-your-hololens-project-with-the-holotoolkit-installing-the-holotoolkit/

**Comment by aalmada** [comment]
Why isn't HoloToolkit available in the Asset Store?

**Comment by yoDon** [comment]
+1 for making HoloToolkit available in the Asset Store, but that feels like it should be its own tracked issue

**Comment by aalmada** [comment]
#379

**Comment by HodgsonSDAS** [comment]
It already has it's own issue: https://github.com/Microsoft/HoloToolkit-Unity/issues/217

**Comment by HodgsonSDAS** [comment]
@yoDon is it safe to say this issue is closed?

**Comment by aalmada** [comment]
@HodgsonSDAS I would say the Thanksgiving release is stable enough to be on the Asset Store. If you mean, lots of changes are planned, then I would bet that it will never be released... ;)

**Comment by HodgsonSDAS** [comment]
So True XD

I think it's close, but we're ultimately not the deciders here, but MSFT.

**Comment by yoDon** [comment]
@HodgsonSDAS My personal belief is the root cause of the confusion is that the link to the Getting Started guide is too low on the page, leading to people not reading it until after they tried to install things incorrectly. I'd move the line "To learn how to add the HoloToolkit to your project see the Getting Started guide." up on the page, perhaps right above or right below the Unity editor version line. But again, ok to close at any point.

**Comment by HodgsonSDAS** [comment]
@yoDon would you like open a more specific issue in regard to it and submit these changes via PR?

**Comment by yoDon** [comment]
@HodgsonSDAS I can hope to do that this weekend

**Comment by HodgsonSDAS** [comment]
@yoDon is it safe to say this issue is closed?
