### ISSUE TITLE
Make HoloToolkit-Unity available in Unity Asset Store

### ISSUE THREAD

**Issue by aalmada** [Microsoft/HoloToolkit-Unity#379]
The Asset Store is the equivalent to NuGet in the Unity ecosystem. Having it the official releases available there make it much easier to install. Users are warned of updates.

**Comment by HodgsonSDAS** [comment]
@aalmada this has an issue already: https://github.com/Microsoft/HoloToolkit-Unity/issues/217

**Comment by keveleigh** [comment]
Closing in favor of #217. This is definitely still something being worked on.
