### ISSUE TITLE
Main Camera prefab missing

### ISSUE THREAD

**Issue by deriven** [Microsoft/HoloToolkit-Unity#380]
Not a huge deal.  But the first step in the README.md says to delete the main camera and add the prefab.  This prefab does not exist in HoloToolkit/Utilities/Prefabs.

The README.md under HoloToolkit/Utilities also says the prefab exists.  Thankfully it details what the prefab sets (except for the clipping plane .. 0.85)

**Comment by deriven** [comment]
Just noticed the HoloLensCamera is a better option.  Perhaps only the README files need to be updated?

**Comment by HodgsonSDAS** [comment]
The main camera prefab was replaced by the HoloLensCamera prefab.
Yes, Seems like the documentation didn't get updated appropriately.

**Comment by kirodge** [comment]
This also needs to be updated in [GettingStarted.md](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/GettingStarted.md)

**Comment by kirodge** [comment]
The `Main Camera.prefab` is also referenced in [GettingStarted.md](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/GettingStarted.md) under the section "Preparing a Scene for Holographic Content"

**Comment by HodgsonSDAS** [comment]
Great catch @kirodge. Updated in the PR.
