### ISSUE TITLE
Deployed Apps Crash - HoloLensWorldManager error

### ISSUE THREAD

**Issue by deriven** [Microsoft/HoloToolkit-Unity#381]
Tested both in emulator and remote device.

```
Begin showing splash screen.

The following GlobalManagers were stripped from the build (Either because they're not used or not supported on this platform):
  NetworkManager
  MasterServerInterface
  UnityAdsManager
  ClusterInputManager
  UnityAnalyticsManager
  CrashReportManager

UnloadTime: 2.947000 ms

HoloLensWorldManager failed to return a world coordinate system!
 
(Filename: C:/buildslave/unity/build/Runtime/VR/HoloLens/SpatialMapping/SurfaceObserver.cpp Line: 466)


```

**Comment by deriven** [comment]
Unity 5.5.0f3
OS Build on emulator: 10.0.14393.0

**Comment by deriven** [comment]
Posted to Unity as well:
https://forum.unity3d.com/threads/deployed-apps-crash-hololensworldmanager-error.445312/

**Comment by HodgsonSDAS** [comment]
Be sure to include a sample scene & repo steps.

**Comment by deriven** [comment]
Ah sorry about that.  I used created a new Unity project, imported the latest toolkit (included examples), and tried the GazeRulerExample scene (HoloToolkit-Examples/GazeRuler/Scenes) as well as the BasicCursor scene (HoloTookit/Input/Tests/Scenes).  I used the HoloToolkit menu options to apply to scene, project and player settings.  I also confirmed that each setting was done.  (I noted that the Unity C# project was not checked in build settings and checked that manually.)  I confirmed that the SpatialPerception was checked as well.

While within Unity, playing the scene works fine.  However within the emulator or the device, no splashscreen appears (which I find odd) and the system returns.  It doesn't state an error.

I can open the app by pinning it somewhere.  The same situation happens (no splashscreen and it returns) and the pinned app is there.

For all of my older apps that I used 5.4f on, they worked fine and still work.  You may review my examples on my YT (maokomeeb).

Hope that helps.

**Comment by HodgsonSDAS** [comment]
Have you tried the new patch update? 5.5.0p1

I've been unable to duplicate this with your repro steps.

**Comment by deriven** [comment]
Figured it out.  It's related to this:
https://github.com/Microsoft/HoloToolkit-Unity/issues/365

VR Supported wasn't checked.  Checked it manually and all good.
