### ISSUE TITLE
Please wrap toolkit code in #if UNITY_WSA

### ISSUE THREAD

**Issue by yoDon** [Microsoft/HoloToolkit-Unity#387]
Unity is used to build multi-platform applications. Simply adding the HoloToolkit-Unity code to a unity project should not break other build targets, but it does. 

The HoloToolkit-Unity scripts and the HoloToolkit example scripts generate large numbers of compile errors preventing builds for Windows *.exe, Mac OSX, iOS, Android, and other targets. The root cause of these compile errors is HoloLens and UWP Unity builds use a different .NET framework than other more general Unity build targets.

Please as a policy wrap all HoloToolkit-Unity and HoloToolkit Example scripts in #if UNITY_WSA/#endif pairs so adding the toolkit to a project doesn't break all other build targets of the project.

**Comment by yoDon** [comment]
Also, can someone from Microsoft please indicate whether this is a PR you'd accept (it's "easy" but will take a fair amount of time so it'd be great to know if the PR will hit a wall of objections if it's submitted)

**Comment by HodgsonSDAS** [comment]
This was mostly working without the define symbols until the last update to 5.50f3.  I second this because now certain parts of my application also rely on cross platform use.

@yoDon would you be willing to make these changes?

**Comment by yoDon** [comment]
I can't get to it before this weekend

**Comment by yoDon** [comment]
PR for this issue submitted above

**Comment by HodgsonSDAS** [comment]
Does it makes sense for the [HoloToolkit-Unity to be cross platform](https://forums.hololens.com/discussion/6011/should-the-holotoolkit-unity-primarily-focus-on-the-hololens-platform)?

We have the vanilla [HoloToolkit](https://github.com/Microsoft/HoloToolkit).
We could also provide just the glue for network connectivity for companion applications using the [sharing](https://github.com/Microsoft/HoloToolkit-Unity/tree/master/Assets/HoloToolkit/Sharing) library

**Comment by yoDon** [comment]
"Does it makes sense for the HoloToolkit-Unity to be cross platform?"

Yes. 

Unity is a cross-platform development environment. Most (many?) large Unity projects are cross-platform. At present, simply checking out the files HoloToolkit-Unity into your project (without even adding any of the functionality to your application) is enough to break the build on all non-WSA projects. This is a complete deal-breaker preventing any such project from even considering using the HoloToolkit-Unity.

In the notes to my PR, it was suggested that there is a lower-impact way to do the #if-defing, which is great but no one has had time to wrap it up as a competing PR.

What's really needed most is an extension to the test harness that checks for errors when the build settings are set to non-WSA platforms, because cross-platform "don't break the build" support needs to be maintained not just in the moment but going forward.

**Comment by HodgsonSDAS** [comment]
@yoDon I really like your response. Sorry, I moved my comment over to the PR.  Would you be willing to move your reply over there for others to read?

Thanks
