### ISSUE TITLE
Cursor design

### ISSUE THREAD

**Issue by GKersten** [Microsoft/HoloToolkit-Unity#388]
The native cursor in the HoloLens looks quite nice, I am talking about the white donut that turns into a filled white circle when airtapping. The cursor in the HoloTookit however looks not so great. Is there a reason for this? I have been searching for some alternatives, but was not able to find one. Anyone else facing this or created an improved cursor?

**Comment by HodgsonSDAS** [comment]
That white cursor you described is indeed in the HoloToolkit:
[DefaultCursor.prefab](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Prefabs/Cursor/DefaultCursor.prefab)

**Comment by GKersten** [comment]
That's indeed what I am looking for, should have updated my HoloToolkit first:) Thanks!
