### ISSUE TITLE
Shaders don't support singlepass stereo instancing

### ISSUE THREAD

**Issue by thebanjomatic** [Microsoft/HoloToolkit-Unity#390]
For a bunch of the holotoolkit shaders, single-pass stereo instancing in Unity 5.5 isn't supported, and as a result, the holograms only render in the left eye.  

For reference, this is the setting I am referring to:  
![image](https://cloud.githubusercontent.com/assets/17907922/21144815/0693638a-c11a-11e6-94a1-eb6fea9fd639.png)

So far my testing has reveiled the following:   

Shader Name | Status
------------ | -------------
StandardFast | ✅ 
BlinnPhong | ✅
Lambertian | ✅ 
Cursor | :x:
EditorHands | :x:
Occlusion | :x:
SpatialMapping\SpatialMappingTap | :x:
SpatialUnderstanding\Mapping | :x:
SpatialUnderstanding\Understanding | :x:
UnlitConfigurable | :x:
VertexLit | :x:
WindowOcclusion| :x:
Wireframe | :x:

**Comment by HodgsonSDAS** [comment]
@thebanjomatic this is now closed correct?

**Comment by thebanjomatic** [comment]
Yes, thanks!
