### ISSUE TITLE
Adding new fast configurable shader

### ISSUE THREAD

**Issue by dbastienMS** [Microsoft/HoloToolkit-Unity#395]
I'd like to start a discussion around the possible removal of the standard fast shader (~50 ALU ops per pixel is still too much for the device), and the adding of a new fast configurable shader designed to replace most of the existing shaders.

Currently, it supports main texture, main color, vertex color, occlusion/detail texture, normal map, ambient lighting via unity's spherical harmonics, diffuse/lambertian lighting, specular/blinn-phong lighting, additional diffuse lighting for lights with a fadeoff such as point and spot, emission color, emission texture.  Near plane fade would continue to be supported.

Culling mode, etc. would continue to be configurable, I'm adding blendop configuration, and since unity now has support for changing the queue on a per-material basis from the UI, the need for the transparent variant shaders should go away.

Is there any odd uses of the standard fast shader that I'm not considering, or any features we feel would be appropriate?

**Comment by NeerajW** [comment]
Merged #454
