### ISSUE TITLE
ERROR_ALREADY_EXISTS: Path

### ISSUE THREAD

**Issue by felixmeissgeier** [Microsoft/HoloToolkit-Unity#397]
Hi,

when using build window to build the VS solution and then open it, I usually get following (attached) error message several times. It only works again after I closed Visual Studio. This is kind of an inefficient workflow  to always restart VS once I built the solution.

Any suggestions?

![error_win32_path](https://cloud.githubusercontent.com/assets/725640/21179087/bf88988c-c1f2-11e6-8154-72e84017ac1f.png)

**Comment by HodgsonSDAS** [comment]
Never seen this error. Do you have repro steps?

**Comment by jessemcculloch** [comment]
I have also never seen this error, and I almost exclusively use the build window for deployments, both with and without visual studio already running.

**Comment by keveleigh** [comment]
Closing due to not being able to repro either. Please reopen if you have repro steps for us to try!
