### ISSUE TITLE
Bug in Sharing - CustomMessages implementation?

### ISSUE THREAD

**Issue by alexdrenea** [Microsoft/HoloToolkit-Unity#40]
I noticed this code in the [CustomMessages.cs](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Sharing/Tests/CustomMessages.cs) class.

``` CSharp 
void InitializeMessageHandlers()
    {
        SharingStage sharingStage = SharingStage.Instance;
        if (sharingStage != null)
        {
            serverConnection = sharingStage.Manager.GetServerConnection();
            connectionAdapter = new NetworkConnectionAdapter();
        }

        connectionAdapter.MessageReceivedCallback += OnMessageReceived;
...
```

If _sharingService_ is null, we don't instantiate the _connectionAdapter_ and the code will crash when we try and set the MessageRecievedCallback. 

Unless I'm missing something, I think we should put the last line of code **inside** the if statement.

**Comment by NeerajW** [comment]
Makes sense. A null check for connectionAdapter would be good too. 
Would you like to make the change? Thank you for filing the issue.

**Comment by alexdrenea** [comment]
Yes, i can make thw change. I'll have a pull request ready later today.
Thanks
