### ISSUE TITLE
Rendered Font does not face in the forward vector

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/HoloToolkit-Unity#400]
Font is rendered backwards in regard to its transform forward vector direction.

Might be how it's implemented in the shader?

**Comment by madvlad** [comment]
I just looked into this. This might be what we want. For scripts like `Billboard` and `TapToPlace` the rotation of the object is based off the rotation of the camera, so when the camera looks at the object it will be looking at it from behind. For the text to be readable we want to face in the opposite direction of the forward vector.

**Comment by S-Hodgson-MMOARgames** [comment]
I disagree. Most likely the text will be a child of the GameObjects that have the scripts on them in the first place.  Generally you'd want things to be facing in the forward direction, so if you need to do some maths on said object, you don't need to guess which direction it's facing.

**Comment by StephenHodgson** [comment]
I'm going to go ahead and close this.  I rewrote the shader once and couldn't get a good way of doing it without breaking stuff.
