### ISSUE TITLE
Refactor TapToPlace.cs to be more generic

### ISSUE THREAD

**Issue by HodgsonSDAS** [Microsoft/HoloToolkit-Unity#404]
Should probably be a base class that others can extend in their own projects.

Someone should be able to put their own logic into `Start`, `OnInputClicked`, and `Update` by extending this base class.

Also being able to specify a parent transform to move, but keeping the script and collider on the object you wish to tap would be helpful as well.

**Comment by madvlad** [comment]
Great idea. I thought about this as well since I'm frequently editing my TapToPlace.cs file in my own projects.

I've created a pull request with changes that address your issues here.

**Comment by HodgsonSDAS** [comment]
Thanks @madvlad!
