### ISSUE TITLE
Minor text update request on "Getting Started" page

### ISSUE THREAD

**Issue by designnomad** [Microsoft/HoloToolkit-Unity#411]
Hello, 

I noticed "ManualCameraControl.cs" changed into "ManualGazeControl.cs"
but the description did not change in the "Getting Started" page.
https://github.com/Microsoft/HoloToolkit-Unity/blob/master/GettingStarted.md

![oldtext](https://cloud.githubusercontent.com/assets/1609471/21334975/1e9e5908-c610-11e6-8a39-46b29b40e8f4.PNG)

**Comment by keveleigh** [comment]
This looks to be fixed as part of #376
