### ISSUE TITLE
Suggestion: used [obsolete] when you rename stuff

### ISSUE THREAD

**Issue by LocalJoost** [Microsoft/HoloToolkit-Unity#423]
Dear people,

I am trying to update a project that I made in September to the new version of the HoloToolkit. This is a painful process. For instance:

- In GazeManager all StableHeadXXX members are renamed to StableXXX

- Various classes have moved name spaces and some I have not been able to find back at all yet.

- I even lost my bloody CAMERA prefab. WHY?

As Unity works, my whole project is broken now - no classes compile till all compile. How about at least using [obsolete] on members, or giving other hints when things have moved namespaces? And try to prevent moving namespaces at all - a 5.4 to 5.5 bump does not suggest breaking code.

Just my $0.05

**Comment by HodgsonSDAS** [comment]
Hi @LocalJoost. I definitely understand you pain.

There is a tag to use for the breaking changes: https://github.com/Microsoft/HoloToolkit-Unity/releases

**Comment by LocalJoost** [comment]
Thanks for your clarification. I think I am 'through the looking glass' now, and although it was a pain to get my app working again, I must admit the new structure works way better.

**Comment by HodgsonSDAS** [comment]
Glad to hear!
We welcome your sharp eyes in future pull requests to help keep the quality of the toolkit at its highest.

Has this issue been resolved for you?

**Comment by LocalJoost** [comment]
Yes. I have the feeling though people are still a bit struggling here and there. Planning on a couple of blog post on it.
