### ISSUE TITLE
Holograms 210 Error! Can't display Billbard & Tag-Along

### ISSUE THREAD

**Issue by Mecil9** [Microsoft/HoloToolkit-Unity#434]
Tutorial 210, i have done the tutorial 210
.But I am debugging on device,can't display billboard and Tag-Along.
 I can see the AstroMan in the sense.
VS debug throw the error:
```
NullReferenceException: Object reference not set to an instance of an object.
at Interactible.Start()
at Interactible.$Invoke4(Int64 instance, Int64* args)
at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: Line: 0)
```

**Comment by Mecil9** [comment]
I recoding this program. the problem begin form adding InteractibleManager.cs file . 
:NullReferenceException: Object reference not set to an instance of an object.
at Interactible.Start()

code:
void Start()
{
defaultMaterials = GetComponent().materials;
        // Add a BoxCollider if the interactible does not contain one.
        Collider collider = GetComponentInChildren<Collider>();
        if (collider == null)
        {
            gameObject.AddComponent<BoxCollider>();
        }

        EnableAudioHapticFeedback();
    }
i find some answers: Not in the Start() method to instantiate?????

**Comment by HodgsonSDAS** [comment]
I'm unsure how much of the HoloToolkit and the HoloAcademy files relate to each other.
They may be very different.
That being said, this might be a question for either the [HoloLens Forums](https://forums.hololens.com/categories/questions-and-answers) or if a bug, the [HoloAcademey 210 Github page](https://github.com/holoacademy/holograms-210).

**Comment by keveleigh** [comment]
Just a quick addition, the Holographic Academy repo is here: https://github.com/microsoft/HolographicAcademy/tree/Holograms-210-Gaze. I'm not sure who the person is who owns the repo linked above.

Agreed that this likely should be added as an issue there instead of here. Also, you mentioned that you were debugging. Do you see this problem when running as Release?

**Comment by HodgsonSDAS** [comment]
@keveleigh , Sorry about that! I've updated my link to point to the correct repo.

**Comment by keveleigh** [comment]
@HodgsonSDAS All good! Thanks :)
