### ISSUE TITLE
SpatialMapping and SpatialUnderstanding document clarification

### ISSUE THREAD

**Issue by Xwil** [Microsoft/HoloToolkit-Unity#435]
Hi,I'm new to Hololens,I'm making a dancer demo.
now,my dancer works good in Hololens,then I want my dancer standing on the floor ,just like RoboRaid on the wall .
I have read the documents about SpatialMapping and Holograms 230,but still confusing,please help me,thanks.
and I'm working on translate HTK doucments into Chinese,when I finished,will you guys include the Chinese version docs here?because Hololens will come to china in 2017!

**Comment by Xwil** [comment]
I tried the spatial understanding example,but the ui are uninteractable...

**Comment by HodgsonSDAS** [comment]
I'm unsure how localization works for github, but I think that would be very beneficial for our Chinese friends.

I think there's already been another issue concerning the lack of documentation in these areas:
https://github.com/Microsoft/HoloToolkit-Unity/issues/218
https://github.com/Microsoft/HoloToolkit-Unity/issues/261
