### ISSUE TITLE
Build Error.

### ISSUE THREAD

**Issue by Joeeeeeeeee** [Microsoft/HoloToolkit-Unity#437]
HoloToolkit->Bulild Window-> Build Visual Studio SLN 
![image](https://cloud.githubusercontent.com/assets/13176253/21536154/c4113f1c-cdb9-11e6-955b-e7daae3600b4.png)

**Comment by S-Hodgson-MMOARgames** [comment]
@darax

**Comment by HodgsonSDAS** [comment]
@Joeeeeeeeee, do you have repro steps?

**Comment by NeerajW** [comment]
@Joeeeeeeeee please reopen with repro steps. I could not repro this.
