### ISSUE TITLE
GestureManager removed from holotoolkit for Unity 5.5?

### ISSUE THREAD

**Issue by krishnan-unni** [Microsoft/HoloToolkit-Unity#439]
I was using the Unity 5.4 beta for hololens and using holotoolkit with GestureManager in it. Now when I updated the toolkit for Unity 5.5 I don't see the GestureManager anymore. Is there any direction on how to capture Tap event and other Gestures?

**Comment by comarabi** [comment]
still cant find the GestureManager in the Holokit. @aalmada they are talking about the gesturemanipulator and not the manager, or did i miss something?
