### ISSUE TITLE
Prefab Cursors don't appear to work.

### ISSUE THREAD

**Issue by imaginethepoet** [Microsoft/HoloToolkit-Unity#444]
I created a new project today. I thought it was me at first.

1. Imported the toolkit
2. Create a new scene
3. fixed the "vr setting in unity
4. Added a cursor (tried them all to my scene)
5. Load my app in Holo. - The cursor doesn't display anywhere in the scene when I run it.

**Comment by HodgsonSDAS** [comment]
@imaginethepoet, you will also need a few more components in your scene.

Take a look at my proposed update to [GettingStarted.md on my fork](https://github.com/HodgsonSDAS/HoloToolkit-Unity/blob/HTK-local/GettingStarted.md#3-preparing-a-scene-for-holographic-content)

**Comment by imaginethepoet** [comment]
Thank you let me give this a go....

**Comment by HodgsonSDAS** [comment]
@imaginethepoet, were you able to get your new project going with the updated GettingStarted document?

**Comment by imaginethepoet** [comment]
I followed the instructions on your branch and can now see the cursor. I was having difficulty though with the build not wanting to register when I added spatial. I believe that's on my side.

Just curious why the changes?

**Comment by HodgsonSDAS** [comment]
spatial mapping is optional.

**Comment by NeerajW** [comment]
Please re-open with your new specific issue. Thank much!
