### ISSUE TITLE
GazeManager sets the normal incorrectly when the Raycast does not hit a hologram

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/HoloToolkit-Unity#45]
This is noticeable if you create a "CursorOffHolograms" model that does not have a "back" side to render. What is happening is the normal when no collision is detected is set in the direction of the user's gaze, this turns the model's face away from the user. The solution is to set the normal in the opposite direction of the user's gaze (back toward the user).

**Comment by NeerajW** [comment]
Does this seem like an app/asset specific fix or you think this will work with all assets?

**Comment by davidkline-ms** [comment]
I do not see why this would not work with all assets. In fact, I believe this proposal was the initial intent of the code. ☺

David

**Comment by NeerajW** [comment]
Please test that out before the pull. Thanks!

**Comment by NeerajW** [comment]
@jochao I believe your recent check in fixed this issue?
https://github.com/Microsoft/HoloToolkit-Unity/pull/59

**Comment by jochao** [comment]
Yes, in checkin #59, GazeManager was updated with reversing the normal direction the asset points when the raycast doesn't hit a hologram.

```C#
                  // If the raycast does not hit a hologram, default the position to last hit distance in front of the user,
                 // and the normal to face the user.
                 Position = gazeOrigin + (gazeDirection * lastHitDistance);
                Normal = -gazeDirection;
                 focusedObject = null;
             }
```
