### ISSUE TITLE
Suggestion: Future PRs to incorporate at least 2 approvals by reviewers

### ISSUE THREAD

**Issue by HodgsonSDAS** [Microsoft/HoloToolkit-Unity#450]
I've noticed sometimes we merge pull requests in too soon without proper time to get reviews.

I'd like to suggest that PRs require at least 3 reviews before we're able to merge into main.

There may be some CI solutions that can automatically check the build status of an incoming PR and flag it ahead of time if changes break the build.

**Comment by LocalJoost** [comment]
Q: who is 'we'? Who are actually able to merge PRs?

**Comment by HodgsonSDAS** [comment]
Microsoft and Moderators assigned by Microsoft, (like myself).

**Comment by LocalJoost** [comment]
I understand, but who are the moderators assigned by Microsoft. You and ... ?

**Comment by HodgsonSDAS** [comment]
I've got no clue. There's lots of people working at MS that contribute to this, and do merges.

As far as Moderators assigned by Microsoft, I really don't know.

**Comment by NeerajW** [comment]
@HodgsonSDAS thanks for the feedback. Will get back to you on this.

**Comment by NeerajW** [comment]
How about we start with 2 approvers to begin with? See how this goes.
Any contributor can approve changes.
Before a moderator merges a PR there must be atleast one other Approver different from the merger.

**Comment by HodgsonSDAS** [comment]
Sounds good to me.

**Comment by HodgsonSDAS** [comment]
https://help.github.com/articles/enabling-required-reviews-for-pull-requests/
