### ISSUE TITLE
Build error after getting latest from IInputClickHandler in TapToPlace

### ISSUE THREAD

**Issue by genereddick** [Microsoft/HoloToolkit-Unity#451]
I just synced to latest and project no longer builds:

Error	
CS0737	
'TapToPlace' does not implement interface member 'IInputClickHandler.OnInputClicked(InputEventData)'. 'TapToPlace.OnInputClicked(InputEventData)' cannot implement an interface member because it is not public.

Also errors for:

Error	CS0621	'TapToPlace.Update()': virtual or abstract members cannot be private	HoloToolkit-Unity	D:\GeneDocs\Documents\GitHub\HoloToolkit-Unity\Assets\HoloToolkit\SpatialMapping\Scripts\TapToPlace.cs	86	Active

Error	CS0621	'TapToPlace.Start()': virtual or abstract members cannot be private	HoloToolkit-Unity	D:\GeneDocs\Documents\GitHub\HoloToolkit-Unity\Assets\HoloToolkit\SpatialMapping\Scripts\TapToPlace.cs	50	Active

**Comment by HodgsonSDAS** [comment]
There's already a PR submitted for this.

**Comment by genereddick** [comment]
Then I'll delete.

**Comment by HodgsonSDAS** [comment]
@genereddick, it was fine to keep open. We didn't have a specific issue to track with yet.
