### ISSUE TITLE
ManualGazeControl.cs NullReferenceException

### ISSUE THREAD

**Issue by jjarthur** [Microsoft/HoloToolkit-Unity#452]
I'm having some trouble getting Manual Gaze Control working with my project. After adding the component to the main camera and playing, I am getting:

`NullReferenceException: Object reference not set to an instance of an object
HoloToolkit.Unity.InputModule.ManualGazeControl.Awake () (at Assets/HoloToolkit/Input/Scripts/Utilities/ManualGazeControl.cs:46)`

Am I missing something?
Thanks

**Comment by S-Hodgson-MMOARgames** [comment]
Sounds like your missing a reference to your AxisController for MouseXYRotationAxisControl.  Did you assign these in the inspector?

**Comment by jjarthur** [comment]
Oops, how do I do that?

**Comment by S-Hodgson-MMOARgames** [comment]
I'd suggest taking a look at the [HoloLensCamera.prefab](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Prefabs/HoloLensCamera.prefab) that implements it. Seems like it has some child objects that each have axis controller scripts attached.

**Comment by S-Hodgson-MMOARgames** [comment]
I'd suggest just using the HoloLensCamera.prefab unless you've got a custom requirement.

**Comment by jjarthur** [comment]
I had no idea that existed, thanks!

**Comment by MartinOrtiz** [comment]
I am trying to use ManualGazeControl too....

I had the same issue, and fixed it (the assigning of the axis stuff).

So now, the look camera stuff works now, but none of the keys work....
I tried the arrow keys, and w,a,s,z keys, none of them worked...
The "Keyboard.Supported" is checked and enabled, but the arrow keys don't work.
