### ISSUE TITLE
Should we remove the unused ExtensibleInputModule branch?

### ISSUE THREAD

**Issue by HodgsonSDAS** [Microsoft/HoloToolkit-Unity#456]
Work for the ExtensibleInputModule has been merged into the Master branch.

Does it make since to keep this branch?

**Comment by jessemcculloch** [comment]
I think its time to clean it up, I cant see any reason to keep it

**Comment by NeerajW** [comment]
Yes!

**Comment by HodgsonSDAS** [comment]
@NeerajW yes we should remove, or yes we should keep it?

**Comment by NeerajW** [comment]
Q: Should we remove the unused ExtensibleInputModule branch?
A: Yes remove :)
