### ISSUE TITLE
Consume new HoloToolkit sharing components, merge other Microsoft changes from shipping products back into HoloToolkit

### ISSUE THREAD

**Issue by matthejo** [Microsoft/HoloToolkit-Unity#458]
[PR #69](https://github.com/Microsoft/HoloToolkit/pull/69) in the HoloToolkit project changes the native Sharing library to remove the usage of unsafe code in the managed Sharing scripts.  This requires corresponding changes to HoloToolkit-Unity to match changes in the native library.

Additionally, there are a large number of other changes made in Microsoft-internal projects to the HoloToolkit that can be merged back.  Changes include:
* Moving all examples into namespaces
* Adding new sync primitives to the sync system in the Sharing component
* Updated C# headers for consistency across the project
* New documentation for the Sharing system

**Comment by HodgsonSDAS** [comment]
Totally stoked about the sync primitives in the sync system.

**Comment by NeerajW** [comment]
Merged #459
