### ISSUE TITLE
How to Handle URI activation and access URI in Unity Script

### ISSUE THREAD

**Issue by cnsdato** [Microsoft/HoloToolkit-Unity#460]
How to access the URI in a GameObject Script, see: https://msdn.microsoft.com/en-us/windows/uwp/launch-resume/handle-uri-activation

**Comment by cnsdato** [comment]
I find a working solution my self.
I have added a `SendMessage()` call into the `ApplicationView_Activated()` Method in App.cs:

```cs
private void ApplicationView_Activated(CoreApplicationView sender, IActivatedEventArgs args)
{
    CoreWindow.GetForCurrentThread().Activate();
    if(args.Kind == ActivationKind.Protocol)
    {
        ProtocolActivatedEventArgs eventArgs = args as ProtocolActivatedEventArgs;
        UnityEngine.WSA.Application.InvokeOnAppThread(() =>
        {
            GameObject go = GameObject.Find("model_holder/model");
            if(go)
            {
                go.SendMessage("LoadByUri", eventArgs.Uri);
            }
        }, false);
    }
}
```

Then in my GameObject script I have the Method 'LoadByUri' implemented:
```cs
private void LoadByUri(Uri uri)
{
   // handle the Uri
}
```

**Comment by HodgsonSDAS** [comment]
@cnsdato Thanks for sharing!

**Comment by quynhnguyen68** [comment]
Thanks for sharing

**Comment by PJBowron** [comment]
Just out of interest, I wonder if @cnsdato might have insight on how to do the same thing from App.cpp when building under IL2CPP?

**Comment by cnsdato** [comment]
> Just out of interest, I wonder if @cnsdato might have insight on how to do the same thing from App.cpp when building under IL2CPP?

No sorry, not out of the box.
But I think it could be done nearly the same as with C#

**Comment by pampas93** [comment]
But in IL2CPP, I'm not able to access any functions defined in Unity. How exactly can I do that?

**Comment by PJBowron** [comment]
My team has a potential solution that we're testing - if it works out we'll post some details :)

**Comment by Jace-Samsung** [comment]
Also currently looking into launching our Unity-exported IL2CPP-backend app via a URI.  The best solution I found so far has been here:  https://forum.unity.com/threads/how-to-call-scripts-from-the-xaml-file-in-uwp-il2cpp.558445/

**Comment by pampas93** [comment]
Perfect. For now, the callback setup and call through that works just fine. Thanks

**Comment by PJBowron** [comment]
We actually went in a similar direction! Exporting a small data struct, for the launch args, and an accessor via a .cpp file in the Unity project, populating the struct via App.cpp, and calling the accessor via a script.
