### ISSUE TITLE
Movement with IManipulationHandler

### ISSUE THREAD

**Issue by charlesMP** [Microsoft/HoloToolkit-Unity#461]
Hey Guys, 
I've been working with the updated version of HoloToolKit for Unity 5.5 and have been running into a lot up changes in how input is handled. Chief among these is the new IManipulationHandler and INavigationHandler interfaces.

I have IManipulationHandler implemented but am getting some weird movement from it.  Theres stutters(even with Time.deltaTime), jumps, movement on weird angles and movement when you move your head.

Did I wrongly assume this is the only line I needed to get an object to move?

public void OnManipulationUpdated(ManipulationEventData eventData)
{
     transform.position += (eventData.CumulativeDelta * Time.deltaTime);
}
(Note this a simplified version of the code but it is all I'm doing to move the object.)

I've taken a look at HandDraggable.cs but that class also has the same stutter and weird movement. Also theres weird rotation stuff going on in it that Doesn't seem to turn off even with the Boolean flags that are there. 

Any help is appreciated.

P.S. I'm also using IManipulationHandler to rotate a different object and this works just like the tutorials from microsoft.

**Comment by HodgsonSDAS** [comment]
Hi @charlesMP, do you have repro steps?

Are you sure it's not the geometry/rendering that's causing the studders to the rendering thread?

**Comment by charlesMP** [comment]
Stutter might be the wrong word, more like it jumps.  And yeah its not rendering thats the cause as of now I only have a single cube rendered in the Scene. (I've run a lot more high-poly objects with particle effects and seen minimal lag on the HoloLens.)

**Comment by charlesMP** [comment]
So the main thing I've tracked down is that when walking around an object things get flipped all sorts of directions. How does the CumulativeDelta get calculated? It seems to return an ABS of movement or local movement as opposed to the actual WorldSpaceMovement.

**Comment by HodgsonSDAS** [comment]
Might be related to https://github.com/Microsoft/HoloToolkit-Unity/issues/448?

**Comment by charlesMP** [comment]
I did take a look at that and am using it for rotation. I did update to a newer version of holoToolkit and it seemed to address what ever issue I was having and the object is moving like expected.

Thanks,
 
The only issue I see right now is that Manipulation events still trigger when you rotate/move your head in space not just your hand.

**Comment by HodgsonSDAS** [comment]
Thanks Charles.  Could you close this one and open a new issue addressing the manipulation events being triggered when your turn your head but keep your hand in place?

**Comment by charlesMP** [comment]
Will do
