### ISSUE TITLE
Tap without focused object is not responded

### ISSUE THREAD

**Issue by qian256** [Microsoft/HoloToolkit-Unity#462]
Hi,
I noticed that in the latest release of HoloToolkit-Unity, there is no interface for responding to tapping event, if there is no focused object. It seems that "OnInputUp", "OnInputDown", "OnInputClick" are sent to the focused object only. Is there access point to the "background" tapping event?
In the old version, the GestureManager can do something like this:
`recognizer = new GestureRecognizer();
recognizer.TappedEvent += (source, tapCount, ray) => {
    MyParseTapEvent();
};
recognizer.StartCapturingGestures();`
I can still add this to the my c# script, but it will be a little bit redundant and weird in the Event-Interface design pattern.

**Comment by aalmada** [comment]
You need to register as global listener the game object that contains the script. Add the SetGlobalListener to the object.

**Comment by qian256** [comment]
Nice! Thanks
