### ISSUE TITLE
Release notes for v1.5.5.0 has incorrect Unity package

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/HoloToolkit-Unity#463]
The unity package in the [release notes](https://github.com/Microsoft/HoloToolkit-Unity/releases/tag/v1.5.5.0) is buggy.
Best to use one good source truth which is checked in under External\UnityPackages.

**Comment by HodgsonSDAS** [comment]
Hmm, strange. I uploaded the file from that path to the release.

I'd fix it but I got removed from the project somehow.

**Comment by HodgsonSDAS** [comment]
I re uploaded the unity package from the External\UnityPackages location to the release

**Comment by NeerajW** [comment]
This was reported to me during a hack yesterday. I tested at my desk and it's good. Closing.
