### ISSUE TITLE
Sharing with UNET scene runtime error in log, devices never connect

### ISSUE THREAD

**Issue by flarb** [Microsoft/HoloToolkit-Unity#469]
I'm trying to run the SharingWithUNET test scene on my devices but they can't connect to each other or the editor. The server is broadcasting, but the client never gets the broadcast. I see this error on the HoloLens from VS' output:

"host id out of bound id {-1} max id should be greater 0 and less than {1}"

Anyone else see this?

**Comment by HodgsonSDAS** [comment]
@flarb, are you having issues with the test scene in the example folder?

**Comment by HodgsonSDAS** [comment]
@darax, any ideas?

**Comment by flarb** [comment]
I'm not sure this error message has anything to do with the reason why they can't connect. I've narrowed it down to something wrong with my actual LAN. If I connect my HoloLens devices via iPhone hotspot, they connect. Has to be some weird firewall setting.

**Comment by flarb** [comment]
Ah, we can close this....I turned off all firewalls (on my dev box and firewall) and now it works.
