### ISSUE TITLE
Unity 5.5.1f1 Released

### ISSUE THREAD

**Issue by g-bataille** [Microsoft/HoloToolkit-Unity#475]
Unity compiler errors with overriden Awake and OnDestroy noticely for the Singleton class.
And with Holotoolkit.Sharing.SharingClientPINVOKE : unknown definitions

**Comment by HodgsonSDAS** [comment]
The HoloToolkit version is currently 5.5.0f3.

**Comment by g-bataille** [comment]
Thank you ! :)

**Comment by HodgsonSDAS** [comment]
Although this Known Issue doesn't bode well:
https://unity3d.com/unity/whats-new/unity-5.5.1

> Warning about missing object references in the inspector after upgraded to 5.5. We have only received one bug report and we have not been able to reproduce the issue. If you find some/all of your object references missing in the inspector do not save your scene. Quit the editor and re-open your project and the references should come back correctly.

**Comment by HodgsonSDAS** [comment]
@g-bataille I didn't get any of these errors when upgrading.

Do these errors show up when you create a build?

**Comment by g-bataille** [comment]
They appeared after I imported the last package, I then pulled the last commit but it didn't change the issue.
Gonna try with a fresh new project.

**Comment by HodgsonSDAS** [comment]
So it happens when you import the [HTK 1.5.5 asset package](https://github.com/Microsoft/HoloToolkit-Unity/tree/master/External/Unitypackages)?

**Comment by g-bataille** [comment]
Yup, same here, doesn't happen on a new project, the problem occured on an existing project.

**Comment by HodgsonSDAS** [comment]
It sounds like you need to do some work to get your existing project updated with the HTK.

**Comment by HodgsonSDAS** [comment]
No worries! glad to hear you got it sorted out.

**Comment by g-bataille** [comment]
Than you for your reactivity !

**Comment by g-bataille** [comment]
I confirm that this is due to a side effect generated by another package, gonna see that with the maintainer of the other package. Sorry for the inconvenience.

**Comment by HodgsonSDAS** [comment]
Well Patch 5.5.1p1 is out already haha.

> - HoloLens: Fixed a crash that occurs on device when downloading files with WWW.(860775 ) 
> - Mono: Correct an invalid C# compiler error with generic types in compiler generated code (like lambdas and enumerators). The error from the C# compiler often includes this text: "There is no boxing or type parameter conversion from..." (847798 )
> - Scripting: Added the following non-allocating accessors to Mesh. These accessors write into a user-specified List. The accessors are GetBindposes, GetBoneWeights, GetColors, GetIndices, GetNormals, GetTangents, GetTriangles, and GetVertices.

This one is probably really great for spatial mapping and understanding.
