### ISSUE TITLE
Can I know when new User joined to my Session?

### ISSUE THREAD

**Issue by Sachin4dotnet** [Microsoft/HoloToolkit-Unity#480]
Hello All,

I have used a SharingService and successfully implemented my application. Sharing Service is installed in a live server, I have used the live IP and we have connected more than one devices successfully.

Now the issue is when some one joined to current Session then on Server (if we have run service with cmd > SharingService.exe -local) we can see "User UnknownUser at address 192.168.4.15 joined session Default". But we can't keep a watch on Server every time.
So I have put one text object and shown whether is Server Connected successfully or not. I got success in that also.

Now I want to show **Which Users are already connected to the current Session**? and also notification **if new User join the session**. How can I achieve this?

Please Help me.

Thanks.

**Comment by NeerajW** [comment]
There are Instance_SessionJoin events that you can subscribe to. Please look at the Sharing.unity test scene. Please post if that event join does not help you. Thanks!

**Comment by HodgsonSDAS** [comment]
There was quite a bit of changes to the sharing library.  Unfortunately some of the libraries were broken in https://github.com/Microsoft/HoloToolkit-Unity/pull/459

**Comment by HodgsonSDAS** [comment]
SharingStage.cs creates an instance of SessionUsersTracker you can use to subscribe to UserJoined and UserLeft events.

```
using HoloToolkit.Sharing;
using UnityEngine;

public class UserNotifications : MonoBehaviour
{
    private SessionUsersTracker usersTracker;
    private void OnEnable()
    {
        usersTracker = SharingStage.Instance.SessionUsersTracker;

        Debug.Log("{0} users in room:");

        foreach (User currentUser in usersTracker.CurrentUsers)
        {
            Debug.LogFormat(currentUser.GetName());
        }

        usersTracker.UserJoined += NotifyUserJoined;
        usersTracker.UserLeft -= NotifyUserLeft;
    }

    private void OnDisable()
    {
        usersTracker.UserJoined -= NotifyUserJoined;
        usersTracker.UserLeft -= NotifyUserLeft;
        usersTracker = null;
    }

    private void NotifyUserJoined(User user)
    {
        Debug.LogFormat("User {0} has joined the room.", user.GetName());
    }

    private void NotifyUserLeft(User user)
    {
        Debug.LogFormat("User {0} has left the room.", user.GetName());
    }
}
```
