### ISSUE TITLE
Spatial Mapping Meshes not aligned with Unity UP vector

### ISSUE THREAD

**Issue by matmuze** [Microsoft/HoloToolkit-Unity#481]
Hello,

I am using Unity to develop a Hololens app.

Most of the time the room mesh that I receive from the Lens is aligned with the UP direction in Unity's world (0,1,0).

However, it sometimes occurs that the room meshes suddenly losses its alignment with Unity UP vector, which results in a tilted mesh (about 40 degree off Unity's UP direction).

(Please note that the room mesh looks perfectly fine inside the lens, its just that its UP vector is off compared to Unity's UP so it looks tilted in the editor)

(Please also note that once the tilt happens the room meshes will be tilted both on the editor with remote debug, and when running the app directly on the lens itself).

Now I understand that the origin of the room is different from Unity but 40 degrees seems a bit off, that would also mean that many game properties would have to be changed accordingly (gravity direction for instance).

The strange thing is that the room is normally aligned with Unity's UP for a while, and then it changes for no obvious reason and cannot be reverted back to normal alignment and remains off 40 degrees, unless I create an entirely new scene (some obscure residual cache value might cause the problem ???)

Could anybody confirm that this behavior is not to be expected, and that a room mesh should always more or less be aligned with Unity's UP vector?

**Comment by HodgsonSDAS** [comment]
It's your device losing it's tracking when this error happens?

**Comment by matmuze** [comment]
The tracking is working fine, like I said, inside the lens everything is fine.

The up vector is only off ONLY compared to unity up vector, so If I place an object inside the scene and pointing in the UP direction (0,1,0) it  will not be aligned with the room anymore.

But again the room mesh appears perfectly aligned with the actual room.

This issue appears suddenly after several tests on the Lens using "Remote to Device" directly in the editor.

Only if I create a new scene from scratch the problem disappear for a while...

**Comment by HodgsonSDAS** [comment]
Do you have specific reproduction steps I can try?

**Comment by matmuze** [comment]
Unfortunately no, I do not know how to reproduce the problem.

But since the problem seems to persist perhaps I could share one of my scene broken scene so that you guys could have a look.

**Comment by HodgsonSDAS** [comment]
Sure, but I think you'd have to share more than just the scene file.
I'm unsure if the scene is broken or maybe scripts associated with the specific functionality.
It could possibly even be a bug in the editor.

**Comment by matmuze** [comment]
Yes sure, thats what I meant

**Comment by matmuze** [comment]
This issue was probably due because my suddenly camera lost its original position & rotation (which is weird because I only modify these values in play mode, probably a unity glitch or something). Resetting the camera position and rotation will solve this issue.

**Comment by HodgsonSDAS** [comment]
That's good to hear!

Did you submit a bug report to unity?

**Comment by matmuze** [comment]
No I just made a script that always reset my camera transform.

I don't really want to bother them because I have literally no clue how/when/why the camera transform suddenly keeps changes made in play mode.

**Comment by HodgsonSDAS** [comment]
I'd do a search and make sure you're not manually changing the camera transform for any reason.

**Comment by HodgsonSDAS** [comment]
@matmuze any update on this, or how to reproduce it?

**Comment by StephenHodgson** [comment]
@matmuze if you can provide reproducible steps please reopen the issue. Thanks
