### ISSUE TITLE
Unable to test sharing scenes on device

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/HoloToolkit-Unity#494]
Not all sharing test scenes are not set up to easily test on device.
- [x] ~SharingSpawnTest~
- [ ] RoomAndAnchorTest

**Comment by HodgsonSDAS** [comment]
For the RoomAndAnchorTest scene I'm thinking about creating a uGUI panel with a way to create and and name rooms/anchors.

I'm thinking the flow will go like this:
1. Start Sharing Service
2. Start Test Scene
3. Add new Room
4. Name the room using dictation
5. Press Join button to fully initialize room on server
5. Create a new Anchor
6. Place the Anchor in the scene
7. Name the Anchor using dictation

Repeat steps 5-7

8. Delete anchor via panel or modal window on anchor
9. Toggle Keep Open on room
10. Leave Room
11. Join room
