### ISSUE TITLE
Configuring HoloLens Projects and Scenes is Complex and Cumbersome

### ISSUE THREAD

**Issue by jwittner** [Microsoft/HoloToolkit-Unity#50]
I'd like to write two HoloToolkit menu options that automatically apply the settings specified here: 

https://developer.microsoft.com/en-us/windows/holographic/unity_development_overview#Configuring_a_Unity_project_for_HoloLens

I'm thinking something like:

- HoloToolkit
    - Auto Configure Project
    - Auto Configure Scene

**Comment by ChimeraScorn** [comment]
Sounds good... I look forward to seeing the pull request. :)
