### ISSUE TITLE
In sharing, how to update the position of the spawnObject?

### ISSUE THREAD

**Issue by bobbycho** [Microsoft/HoloToolkit-Unity#501]
Hi, 

Once I spawned a cube, I moved a new position when I clicked as shown below. But, the new position was not synchronized with other HLs. 

public void OnInputClicked(InputClickedEventData eventData)
{
DefaultSyncModelAccessor spawnedObject =        GameObject.Find("Cube").GetComponent<DefaultSyncModelAccessor>();
SyncSpawnedObject cube = (SyncSpawnedObject ) spawnedObject.SyncModel; (I am not sure ??)
Vector3 position = Random.onUnitSphere * 2;
cube.Transform.Position = position;
 }

Please help me to fix my problem,
Thanks,
Woon

**Comment by HodgsonSDAS** [comment]
Still trying to figure this out myself @bobbycho.

**Comment by bobbycho** [comment]
Thanks HodgsonSDAS. Please let me know when you resolve it.

Thanks again,
Woon

**Comment by bobbycho** [comment]
I figured it out. Once I changed the root of the spawned objects, synctransform did not work well.
I fixed it.

Thanks,
Woon
