### ISSUE TITLE
Can't notify user of manipulation event 

### ISSUE THREAD

**Issue by genereddick** [Microsoft/HoloToolkit-Unity#511]
I'm getting an error where manipulation drops but the OnManipulationCanceled event never gets called. The object gets stuck in this state and cannot be selected or manipulated again.

The error reported is: 

    Can't notify user of manipulation event - error code says we successfully retrieved the delta, but it's null!
    
    (Filename: C:/buildslave/unity/build/Runtime/VR/HoloLens/Gestures/GestureRecognizer.cpp Line: 950)

**Comment by HodgsonSDAS** [comment]
Hi @genereddick, could you share some example code so I can confirm?

**Comment by genereddick** [comment]
Sorry, I already refactored everything and it has stopped happening. 

As near as I can tell it occurred — both on HoloLens and the Emulator — when two sets of code, an Update and OnManipulationUpdated were both interacting with and moving the same object. 

If it comes up again I'll capture in more detail and post a new issue.

**Comment by NeerajW** [comment]
I will try to build a min repro. I think it's with having Tap and Manipulation enabled on the same GR in GestureInput.cs.

**Comment by genereddick** [comment]
I have both enabled.

**Comment by vickytseng0906** [comment]
I'm getting this with the Spatial Controllers in 2018

**Comment by Alexees** [comment]
@StephenHodgson this is really old, but just happened to me with 2018.2.6f1. What was the solution when you closed this, or the current status of it?
