### ISSUE TITLE
Hololens LiveView does not work with remoting

### ISSUE THREAD

**Issue by jmfranz** [Microsoft/HoloToolkit-Unity#512]
Hey Folks,
I've noticed today that if you enable live while using an application in "remote to device" mode the holograms on the right eye scale up (a lot) and move around with the user's head. If I run the same application directly on the HoloLens the issue does not occur.

I am not sure if this is an limitation of the remoting or a bug. It is also hard to record this but it should be easy to replicate.

Cheers

**Comment by HodgsonSDAS** [comment]
Are you sure this isn't a bug with Unity and not the HTK?

**Comment by jmfranz** [comment]
Hey Stephen, it might be but this only happens when I am remoting (which is
provided by the toolkit isn't? I might be wrong here) and turn on live view
on a other computer.
Left eye works perfectly, right eye doesn't.

Any tips for me to investigate further and provide extra info?

**Comment by HodgsonSDAS** [comment]
No I believe the remoting features are built into the editor.

Sounds like it might be something to do with the graphics device on that particular machine.

**Comment by jmfranz** [comment]
Hmm I thought it was from the toolkit, not sure why. I'll open a post on the Unity forums :)
The setup was:

- Remoting machine:
Windows 10 x64
 Unity 5.5
 GTX 1070
- Live view machine
 Surface Pro 3

**Comment by HodgsonSDAS** [comment]
Is it for a HoloLens companion application?

**Comment by HodgsonSDAS** [comment]
Check out the [HoloLens Companion Repo](https://github.com/Microsoft/HoloLensCompanionKit)
