### ISSUE TITLE
How do you exclude objects from gaze input?

### ISSUE THREAD

**Issue by StarWardo** [Microsoft/HoloToolkit-Unity#514]
I am looking for a way to let the Hololens ignore certain objects that would not be affected by gaze input. When a gameobject is inside another gameobject (for example a glass orb) they cannot be tapped.

**Comment by HodgsonSDAS** [comment]
I actually just merged a PR that addresses this exact issue. https://github.com/Microsoft/HoloToolkit-Unity/pull/510

You'd want to assign an overridden focused object.

**Comment by HodgsonSDAS** [comment]
Also, you can assign objects to specific layers and on the InputManager's Gaze Manager remove the layer you'd like to ignore.

Or just remove the collider from the object you're having issues with.

**Comment by StarWardo** [comment]
Sorry that I missed that, thanks a lot!

**Comment by S-Hodgson-MMOARgames** [comment]
No worries, glad I could help.
