### ISSUE TITLE
Request: Better camera display

### ISSUE THREAD

**Issue by xwipeoutx** [Microsoft/HoloToolkit-Unity#518]
The low FOV of the default camera makes it difficult to have context around what is in the room.  My suggestion is:

* Increase the FOV back to `60` (camera default)
* Show a box representing the "viewport" of the hololens (which is essentially at 14 degrees FOV)
* Decouple the input icons from the camera FOV

The result would be similar to the Web Portal's 3D View (in first person mode) - the green box is what's in the Hololens viewport.

![image](https://cloud.githubusercontent.com/assets/1008567/22960760/3b8794ae-f38c-11e6-93fa-c710352a0ea7.png)

**Comment by HodgsonSDAS** [comment]
This looks like a view from the device portal, correct?

Or is this a view from the editor using Holographic remote?

**Comment by xwipeoutx** [comment]
@HodgsonSDAS , thanks for your reply. A few notes.

The recommended camera settings on the Windows Holographic site mention nothing about FOV - and their example screenshot has `60` as the FOV. 

Note the FOV setting of the unity camera does not affect the render when on a device or emulator.

I would think that showing more context, with a box saying "this is what will be on the HoloLens" will lead to much _less_ confusion. I think it would be valuable to see what others think before `wontfix`/closing it - it's the first component a new user will use/see, and having it as useful would be good.

**Comment by S-Hodgson-MMOARgames** [comment]
You're right, I should have left this open a bit longer for others to comment on. My Apologies.
