### ISSUE TITLE
Changing cursor according to hovered object (Custom Cursor)

### ISSUE THREAD

**Issue by cnspaha** [Microsoft/HoloToolkit-Unity#521]
**What I am trying to do:**
If my gaze hits a target (TargetedObject in Cursor.cs) I wanna show a custom cursor like in the hologram app where the cursor becomes two arrows for rotating the object. 

Is there any simple way to achieve this?
As far as I know there is a "contextual" state in the Cursor.cs which is meant for something like this, but it isn't used anywhere...

**I already made a simple approach (if u like it I will be glad to make a PR):**
In the CursorModifier.cs I add public objects for the cursors when the targeted object is observed/interact hovered or not.
In the ObjectCursor.cs I override the "OnFocusedObjectChanged" function to also check if the targeted object has a CursorModifier component and also if the component has prefabs for the current state. If it has, I instantiate the according prefab, set the custom cursor alongside the "CursorOnHolograms" and "CursorOffHolograms" and set a flag that a custom cursor should be used.

what do you think about my approach? since it is still under development I won't post code before I beautified and tested it a bit more ;)

**Comment by HodgsonSDAS** [comment]
Hi @cnspaha.  I've seen many projects just create their own implementation of the cursor and just animate the cursor changes via `OnFocusedObjectChanged`.  Checking the layer is much more efficient than using `GetComponent<T>`.  Take a look at the `DefaultCursor.prefab` and `AnimatedCursor.cs`.
