### ISSUE TITLE
Running an External batch (.bat) file

### ISSUE THREAD

**Issue by pranavgadamsetty** [Microsoft/HoloToolkit-Unity#523]
Hi,

I want to run an external .bat file by clicking on a UI Button in Unity 3D. Can I do this using HoloToolkit. If so, how? 

Thank you

**Comment by HodgsonSDAS** [comment]
I think this is more a [general Unity question](https://www.google.com/search?espv=2&q=unity+c%23+run+batch+file&sa=X&ved=0ahUKEwio4uX86p7SAhXHgFQKHUhHAxkQ7xYIGSgA&biw=1680&bih=920).

**Comment by HodgsonSDAS** [comment]
I'm not even sure a bat file will run on HoloLens

**Comment by pranavgadamsetty** [comment]
I have followed an answer to this question on Unity Answers but I always end up getting an error reading **"The type or namespace name "Process" could not be found. Are you missing a using directive or an assembly reference?"**. Nothing I do fixed this problem. So, I was trying to do it using HoloToolkit instead.

**Comment by HodgsonSDAS** [comment]
Take a look at [this class](https://github.com/HodgsonSDAS/HoloToolkit-Unity/blob/4df915a61045f0c768cc847783f93d22573cf21f/Assets/HoloToolkit/Utilities/Scripts/Editor/ExternalResourcesHelper.cs) I wrote. Does something similar, but again, I'm not even sure it will run on the device.

**Comment by HodgsonSDAS** [comment]
> Windows Store applications are not allowed to start new processes.

[Direct reply from Unity](https://forum.unity3d.com/threads/launch-hololens-applications-since-unity.423988/#post-2967268)

**Comment by pranavgadamsetty** [comment]
Hi,
I never realized that. Thanks for the early reply.
Regards
