### ISSUE TITLE
Hand draggable changes object's rotation when it shouldn't

### ISSUE THREAD

**Issue by 8greg8** [Microsoft/HoloToolkit-Unity#525]
Let's say I use Hand Draggable script to move some cylinder which it lies on a plane (Z rotation 90°). Is Keep Upright and Is Orient towards user are unchecked. 

When I click on it in Game mode to move it, it changes rotatation to upwards (Z rotation 0°).

Shouldn't the lines 199 and 200 in Hand Draggable script simply be:

`draggingRotation = HostTransform.rotation;`

**Comment by cnspaha** [comment]
probably duplicate of #519 ?

**Comment by HodgsonSDAS** [comment]
Yeah this has been fixed with @cnspaha's pull request.

**Comment by HodgsonSDAS** [comment]
@8greg8 is this issue closed?

**Comment by 8greg8** [comment]
Pulled the latest and everything works now. @HodgsonSDAS the issue is closed.
