### ISSUE TITLE
Speech Input Source Test scene is broken

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/HoloToolkit-Unity#527]
```
MissingComponentException: There is no 'Renderer' attached to the "Spheres" game object, but a script is trying to access it.
```

Also it seems Spheres Speech Input Handler is missing a reference in the response callback.

**Comment by UWarbs** [comment]
#603

**Comment by StephenHodgson** [comment]
I've already addressed this in my pull request https://github.com/Microsoft/HoloToolkit-Unity/pull/533

**Comment by UWarbs** [comment]
Don't know how I missed that. Thanks.

**Comment by StephenHodgson** [comment]
No worries, I really appreciate you taking the time to check this out and work up a fix.

**Comment by StephenHodgson** [comment]
@UWarbs, I'd appreciate it if you could review that PR if you'd like to help see this issue resolved. Thanks.

**Comment by UWarbs** [comment]
@StephenHodgson in Unity 5.6 and on the HoloLens your PR addresses this issue. #555 also works well.
