### ISSUE TITLE
Voice VOIP garbled & slow on WAN when using MicrophoneTransmitter & MicrophoneReceiver 

### ISSUE THREAD

**Issue by StokedOnIt** [Microsoft/HoloToolkit-Unity#529]
Voice VOIP garbled & slow on WAN when using MicrophoneTransmitter & MicrophoneReceiver

**Comment by HodgsonSDAS** [comment]
Any steps to reproduce?
Have any example scripts to show?

**Comment by StokedOnIt** [comment]
Hmmm, just adding the MicrophoneTransmitter & MicrophoneReceiver to the Camera. Works fine on localhost with multiple emulators connected through Unity using Holographic Emulation and HL Emulator. Once it is on an internet server with a real HoloLens it get garbled, slow and only bits and pieces come through. 

Also, doesn't seem to matter if I put an Anchor Transform on it or not.

**Comment by HodgsonSDAS** [comment]
are you using MicStream or Unity.Microphone?

**Comment by StokedOnIt** [comment]
I just used the premade scripts that came with the HoloToolKit-Unity in HoloToolKit/Sharing/Scripts/VoiceChat

**Comment by HodgsonSDAS** [comment]
What's your transmission rate?  Maybe try lowering your recording quality.
Could be network issues over the line?  It's hard to debug something like that though.

**Comment by StokedOnIt** [comment]
I was using the preset LOW_QUALITY_VOICE in Unity when the Script is added to the Camera. Yeah I'm assuming it has something to do with the packets. I was assuming since it comes in the HoloToolKit-Unity that it works, haha. I've had to modify so much of the Toolkit's code though to get some things to work.

**Comment by HodgsonSDAS** [comment]
Well any fixes are welcome to be submitted! 

It helps to get more eyes on it as well.  I've been working on some mic stuff, but it's mostly with dictation.

**Comment by StokedOnIt** [comment]
I'm thinking it is on the SharingServer end. As it works great on LAN but WAN no. The speech com-es - I-n lik-e th-is.

**Comment by S-Hodgson-MMOARgames** [comment]
Maybe. suggest opening a ticket on the main HoloToolkit repository addressing this.

**Comment by StephenHodgson** [comment]
Closing this in favor of https://github.com/Microsoft/HoloToolkit/issues/72
