### ISSUE TITLE
Mic Stream Demo throws Null Ref w/cube selected and entering playmode

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/HoloToolkit-Unity#555]
```
MissingReferenceException: The object of type 'MicStreamDemo' has been destroyed but you are still trying to access it.
```
Mic Stream Demo throws Null Ref when cube is selected when entering play mode.

[Source of problem](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnAudioFilterRead.html):
> - If OnAudioFilterRead is implemented a VU meter will show up in the inspector showing the outgoing samples level.
> - OnAudioFilterRead is called on a different thread from the main thread.

The Editor is trying to render the VU meter before we initialize the `MicStream` in `Awake`.

Fix: Simply move initialization logic from `Awake` to `Start`.

**Comment by branchbark** [comment]
Hi Stephen, I receive a similar issue while trying to set up the mic streaming function for a shared experience:

MissingReferenceException: The object of type 'MicrophoneReceiver' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEditor.Editor.IsEnabled () (at C:/buildslave/unity/build/Editor/Mono/Inspector/Editor.cs:587)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1146)
UnityEditor.InspectorWindow.DrawEditors (UnityEditor.Editor[] editors) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1022)
UnityEditor.InspectorWindow.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:352)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
HoloToolkit.Unity.InputModule.MicStream:MicInitializeCustomRate(Int32, Int32)
HoloToolkit.Sharing.VoiceChat.MicrophoneTransmitter:Awake() (at Assets/HoloToolkit/Sharing/Scripts/VoiceChat/MicrophoneTransmitter.cs:100)

Not sure if this is related or the appropriate location to post.  Thanks.

**Comment by StephenHodgson** [comment]
Yup, that's the same error I got minus the stack trace.

I've got it fixed already but haven't submitted a PR yet.

**Comment by branchbark** [comment]
Sweet, I've been looking at this since last night!

**Comment by sorianog** [comment]
Who would be able to look into this?

**Comment by StephenHodgson** [comment]
@sorianog I just added the fix.
