### ISSUE TITLE
Changing SpatialMappingObserver extens to an AxisOrientedBox

### ISSUE THREAD

**Issue by HoloFan** [Microsoft/HoloToolkit-Unity#557]
Hey,

As already mentioned in this [post](https://forums.hololens.com/discussion/comment/13591#Comment_13591), I would like to change the observed volume of a SpatialMappingObserver. As this class uses the SurfaceObserver (UnityClass) which allows to manipulate the observed volume to be an [oriented box](https://docs.unity3d.com/ScriptReference/VR.WSA.SurfaceObserver.SetVolumeAsOrientedBox.html) it would simply be an additional method.

I would suggest to implement to new methods, one to change the extents as an axis aligned box and the other as an axis oriented box. This would also have the advantage of actually changing the extents. As far as I read the code at the moment, one has to change the public property "extents" and than call the "SetObserverOrigin" to really change the extents of the observed volume.

The new methods could look similar to this:
```
// create an private variable to hold the origin (may also be public to change this in the inspector)
private Vector3 origin = Vector3.zero;

// public method to change the extents to an axis aligned box
public bool SetObserverExtentsAxisAligned(Vector3 extents)
{
    bool extentsUpdated = false;
    if (observer != null)
    {
        observer.SetVolumeAsAxisAlignedBox(origin, extents);
        extentsUpdated = true;
    }
    return extentsUpdated;
}
```

**Comment by StephenHodgson** [comment]
@HoloFan, I think this a fantastic addition. Please submit a PR with your proposed changes.
