### ISSUE TITLE
How to clean memory of taptoplace?

### ISSUE THREAD

**Issue by mauricioalfonso007** [Microsoft/HoloToolkit-Unity#580]
Hi,

I'm using the TapToPlace script for a game I'm working on, but every time I close the app and reopen it, the object is where I put it last time, I try to change the initial position but it does not Work.

It's any way to clean the position when the app restarts?

**Comment by niklas87** [comment]
You have to delete the WorldAnchor set in the WorldAnchorManager by the TapToPlace script.

**Comment by mattfedocsg** [comment]
@niklas87 is right.  Also, it may benefit you to make an object pool to keep track of which objects have tap to place and what their anchor names are.

**Comment by mauricioalfonso007** [comment]
Thank guys,

it works like a charm.
