### ISSUE TITLE
Unity "StreamingAssets" folder with HoloToolkit Build & Deploy

### ISSUE THREAD

**Issue by GKersten** [Microsoft/HoloToolkit-Unity#593]
I'm experiencing a weird situation right now. I am trying to add multilanguage assets (audio and images) to my app, grouped per language in a named folder ("en", "nl", etc). I do this inside the [StreamingAssets folder in Unity](https://docs.unity3d.com/Manual/StreamingAssets.html) so I can search through the supported languages at runtime by folder paths.

This works fine when Building the app manually via Unity -> Build Settings and then Build & Deploy the app in Visual Studio. At runtime I can loop through the language folders, I can see "en" and "nl" are present.

However, when I choose to "Build SLN, Build APPX, then Install" in the Build Windows of the HoloToolkit, I only see 1 folder "en" when trying to loop through the StreamAssets at runtime. 

With the following code I try to get the folders at runtime. Which, as stated above, works fine when building and deploying without the Build Window.

`    public string[] GetSupportedLanguages()
    {
        var dir = new DirectoryInfo(Application.streamingAssetsPath);
        return dir.GetDirectories().Select(x => x.Name).ToArray();
    }
`

Anyone has an idea what could be wrong? I really like to use the Build window:)

**Comment by MRCalderon3D** [comment]
Im having problems with videos in StreamingAssets folder. It works in unity
editor but doesn't work in Hololens. Yesterday, before a windows update,
everything works great.

2017-03-28 10:50 GMT+02:00 Guido Kersten <notifications@github.com>:

**Comment by GKersten** [comment]
So I finally figured out what is causing this problem. It's actually not related to HoloToolkit, but to creating AppxBundles. By default the AppxBundle is created and with that, the compiler is smart enough to create appxpackages for each languages when folders in the project are named using ISO convention, for example "en", "nl". At first this is what you want, but the problem is that the HoloLens does not support multiple languages yet, so the app won't be able to switch languages based on system settings. This is why I want to include all language resources in 1 appxpackage and as a result do NOT want to create the appxbundle.

To solve this: Set build app bundle to "Never" when building App Packages. Or add AppxBundle=Never as an argument.
