### ISSUE TITLE
5.6.0f3: Holographic Remoting doesnt work with Camera Prefab.

### ISSUE THREAD

**Issue by markval** [Microsoft/HoloToolkit-Unity#597]
HoloLensCamera prefab doesnt work in latest version of Unity.

A newly created camera from scratch in f3 will work well.

![image](https://cloud.githubusercontent.com/assets/51227/24568244/84405cc4-1661-11e7-9951-1897be43275a.png)
You can see up here that im connected with remote, the camera is controlled by the Hololens, the cursor goes on the ball but the camera doesnt render anything on both hololens and editor. The same scene works in 5.5.

**Comment by StephenHodgson** [comment]
Known issue in 5.6:` VR: Mirror mode is incompatible with Single-Pass stereo rendering`

**Comment by StephenHodgson** [comment]
@markval, could you do a diff of the HoloLensCamera.prefab and the new camera you've setup here so we can see the exact changes?  Thanks

**Comment by Benmarad** [comment]
I have experienced the same problem. Seems like selecting "Allow HDR" solves it.

**Comment by StephenHodgson** [comment]
I have not been able to reproduce this with the default HoloLensCamera.prefab from the HTK.

The problem is that you're on the scene tab and not on the game tab. The Remote player does not render the scene if you're in a different tab other than the game tab.

**Comment by jrlafarge** [comment]
I know this discussed in different place, but just uncheck the MSAA on the prefab and it will start working again,.

**Comment by StephenHodgson** [comment]
That is correct. I have already addressed this in the 5.6.0p1 pull request.
