### ISSUE TITLE
Wiki: Microsoft developer links: /holographic moved to /mixed-reality

### ISSUE THREAD

**Issue by danilogr** [Microsoft/HoloToolkit-Unity#598]
Hi, if you are reading the documentation and click on any link to Microsoft Developer, you will get a cute 🐕  telling you that it "lost the trail to that page."

Well, it turns out that all the Microsoft Developer Links for HoloLens moved to a new location. URLs beginning with https://developer.microsoft.com/en-us/windows/holographic/ won't work anymore. The new URL prefix seems to be https://developer.microsoft.com/en-us/windows/mixed-reality/.

For instance, if you want the check the documentation on Coordinate Systems, you need to go to https://developer.microsoft.com/en-us/windows/mixed-reality/coordinate_systems instead of https://developer.microsoft.com/en-us/windows/holographic/coordinate_systems.

Since I am not sure if Microsoft Developer will redirect from one to the other in the future, I am creating this ticket here to guide other Hololens developers to the right page 😄

**Comment by StephenHodgson** [comment]
You've got to be kidding... This is really annoying.

**Comment by StephenHodgson** [comment]
This doesn't just affect the Wiki, but all links in the documentation of the repository.

**Comment by StephenHodgson** [comment]
Fixed. Let me know if you find any others.
