### ISSUE TITLE
Unable to Build Error in Unity HoloTookkit/ 

### ISSUE THREAD

**Issue by studio216** [Microsoft/HoloToolkit-Unity#60]
Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingComponent/Support/SMBaseAbstract.cs(332,88): error CS1501: No overload for method `Update' takes `1' arguments

Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingComponent/Support/SMBaseAbstract.cs(481,33): error CS1501: No overload for method `RequestMeshAsync' takes `2' arguments

**Comment by studio216** [comment]
Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingComponent/Support/SMBAbstract.cs

Tested with 5.4.b09 and above

**Comment by NeerajW** [comment]
@studio216 I just tried the [test scene](https://github.com/Microsoft/HoloToolkit-Unity/tree/master/Assets/HoloToolkit/SpatialMapping/Tests/SpatialMappingComponent) with the component and it worked for me.

I am using Unity Beta 18. [Install the tools](https://developer.microsoft.com/en-us/windows/holographic/install_the_tools) page has all the information you need to update to the latest Unity.

**Comment by reallybigpictures** [comment]
ahhhh ok will do Neeraj. Perhaps it is the version of Unity.

**Comment by reallybigpictures** [comment]
Reporting back. Worked fine with B18. All good here! Start developing!

**Comment by NeerajW** [comment]
Sweet. Thanks for the update.
