### ISSUE TITLE
Bump Unity Editor Version to 5.6.1f1

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/HoloToolkit-Unity#600]
https://unity3d.com/unity/whats-new/unity-5.6.0

Lots of API changes.
Please reference any 5.6 related bugs to this issue.

**Comment by StephenHodgson** [comment]
https://github.com/Microsoft/HoloToolkit-Unity/issues/597

**Comment by thebanjomatic** [comment]
#554

**Comment by StephenHodgson** [comment]
[5.6.0p1 Released](https://unity3d.com/unity/qa/patch-releases/5.6.0p1):

- (none) - UGUI: Fixed a memory leak in UGUI.
- (896314) - VR: Fixed a potential crash when entering play mode.
- (884058) - Windows Store: Fixed a build error "Failed to resolve assembly: 'Windows.Foundation.UniversalApiContract, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'"." when using default parameters of Windows Runtime types in method signatures and "C# projects" build option on .NET scripting backend.
- (869168) - Windows Store: Fixed a build error on .NET scripting backend when a method with name OnMouseDown was defined in a non-monobehaviour class.
- (869407) - Windows Store: Fixed a crash when using "SceneManager.UnloadSceneAsync" on .NET scripting backend with .NET native enabled.
- (885997) - Windows Store: Fixed a rare build error "Failed to resolve assembly: 'System.Reflection.TypeExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'" on .NET scripting backend when using "C# projects" option.
- (886049) - Windows Store: Fixed a rare build error "Version not supported: 255.255.255.255" when using certain .winmd plugins and "C# projects" option on .NET scripting backend.
- (872058) - Windows Store: Fixed a System.TypeInitializationException on startup with .NET scripting backend when a nested class derives from a non-nested class and overrides one of its methods.
- (875849) - Windows Store: Fixed Screen.SetResolution not accounting for DPI settings.
- (885964) - Windows Store: Fixed a crash that could occur with D3D build type when the window was minimized or closed.
- (888660) - Windows Store: Fixed non-alloc physics overlap functions causing a crash on .NET Scripting Backend.
- (890043) - Windows Store: Fixed an issue whereby not being able to switch to Windows Store platform when Windows 10 SDK was not installed.

**Comment by StephenHodgson** [comment]
5.6.0p2 is out. Doesn't look like it has any HoloLens related changes tho.

**Comment by thebanjomatic** [comment]
[5.6.0p4](https://unity3d.com/unity/qa/patch-releases/5.6.0p4) is out with the following hololens related change (that I am personally very excited about): 

> ([897406](https://issuetracker.unity3d.com/issues/hololens-editor-crashes-when-doing-the-bloom-gesture-during-holographic-remoting)) - VR: Fixed an editor crash when performing a bloom gesture while using HoloLens remoting.

**Comment by thebanjomatic** [comment]
@StephenHodgson and now [5.6.1](https://unity3d.com/unity/whats-new/unity-5.6.1)

**Comment by StephenHodgson** [comment]
@thebanjomatic that was exactly what I was waiting for!

**Comment by thebanjomatic** [comment]
Yeah, its irritating that they aren't listed here: https://unity3d.com/unity/qa/patch-releases 5.6.1f1 was released 5 days ago, but I just found out about it yesterday through a co-worker.

**Comment by Sacristan** [comment]
i found out it today by checking Unity site. We switched to patch release 6 days ago :D

**Comment by StephenHodgson** [comment]
I was waiting to mark a tag and make a new release just for this.
