### ISSUE TITLE
Build Failure due to App Name with Space

### ISSUE THREAD

**Issue by Shubham7694** [Microsoft/HoloToolkit-Unity#601]
I tried a make a build of my HL application using Holotoolkit. The build is successful if App Name doesn't contain spaces. In player settings if i keep "GoogleCloud" as name it works while "Google Cloud" fails the build.

**Comment by StephenHodgson** [comment]
I'm unsure how this relates to the HoloToolkit.

**Comment by Zod-** [comment]
Maybe trying to build with the build window from HoloToolkit? 

I have a space in my project name and it builds just fine.

**Comment by Shubham7694** [comment]
@StephenHodgson  i was trying to automate build process through Command Line using HoloToolKit. I called the function below to build. The solution (.sln) is generated successfully but the MSBuild part fails.
` public static void PerformReleaseBuild()
    {
        BuildDeployPrefs.BuildConfig = "Release";
        BuildDeployWindow.BuildAndRun(PlayerSettings.productName);
    }`
Here playersettings.productname with and without space seems to make a difference for build results.
Thanks for suggestion. I will post in Unity HL Forum as well.

**Comment by mattfedocsg** [comment]
If you are using cmd and Jenkins shouldn't you be formatting the path correctly.  Maybe using a backslash for the space in the product name.  Or maybe just reject any release name that has a space.

**Comment by Shubham7694** [comment]
@mattfedocsg  1. Jenkins isn't creating trouble.Problem is before that. When i try building through CMD using holotoolkit provided functions, there it self the build fails when product name has string separated by space.
2. I can't reject the release because our Product name has a space.

**Comment by StephenHodgson** [comment]
That makes a lot more sense now. Haha.
Thanks for the report.

**Comment by StephenHodgson** [comment]
Do you have a sample project and repro steps?  I can't seem to get the build to fail using the Build Window. 

Are you sure the string you're passing from the cmd line is formatted properly?

**Comment by Shubham7694** [comment]
Sorry for late reply. PFA the sample project.
Steps to reproduce:
1. Open the Project and Go to player settings
2. Enter the 'Product Name' parameter with "Test Project" {or for that matter, any string with two words segregated by space.i.e. "TestProject" -> "Test Project".
3. Make a build through holotoolkit by choosing "BuildSLN, Build Appx, then Install".
 Outcome: Build Fails
Surprisingly if i concatenate the names together i.e ("TestProject"), build succceds.
Unity: 5.5.0f3
[BuildNameTest.zip](https://github.com/Microsoft/HoloToolkit-Unity/files/969936/BuildNameTest.zip)

**Comment by StephenHodgson** [comment]
I'm pretty sure this is a issue even when setting in Visual Studio, that the name cannot include white space.

**Comment by Shubham7694** [comment]
Yeah i think so i tried that but can't remember. Will verify that. Is there a way to separate PlayerSettings.ProductName [Unity] and the name of generated solution. 
I guess MSBuild is fails to correctly refer to soln due to spacing in path name.

**Comment by The-MAZZTer** [comment]
I found a bug in this line which may or may not be relevant to this specific bug but it does deal with build failures due to spaces in the project name.

https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Build/Editor/BuildDeployTools.cs#L96

The code reads:
`     nugetPInfo.Arguments = @"restore " + PlayerSettings.productName + "/project.json";`

I would change it to:
`     nugetPInfo.Arguments = "restore \"" + PlayerSettings.productName + "/project.json\"";`

**Comment by Danta1st** [comment]
This solution worked for me. 

I have not - yet - found any correlations to other issues.
