### ISSUE TITLE
Unity Editor Task Support

### ISSUE THREAD

**Issue by waynebaby** [Microsoft/HoloToolkit-Unity#611]
Hi Guys 

I have a Task.Editor.dll, which can be used as a plugin, make Unity Editor supports System.Threading.Tasks TAP feature.  It is quite useful for UWP unity programming, and I hope I can add it to HoloToolkit， but I am not sure if it is fit HoloToolkit's aim, and I am not sure which folder it should be in.

The dll is compiled  from the code of  "Async CTP Extenssion for VS2010" which runs perfectly in .net 2.0-.net 3.5 platforms.

Thanks

Wayne

**Comment by thebanjomatic** [comment]
I'm pretty sure that Task + Async/Await support will be coming to the Unity editor 2017.1 (https://forum.unity3d.com/threads/will-2017-1-support-async-await-on-xbox-one.464972/)

There may be some utility in having this sort of thing available sooner, but I'd personally hesitate to build in a dependency if the next release of Unity will have built-in support with (potentially) different semantics in terms of the synchronization contexts are available.

**Comment by StephenHodgson** [comment]
@thebanjomatic agreed.
