### ISSUE TITLE
editor extension to create the windows tile images

### ISSUE THREAD

**Issue by davesmits** [Microsoft/HoloToolkit-Unity#616]
we build a extension so you can create the different tile images automatically based one master image. we use it a lot to get our apps in the store so can do LOB distrubition via the business store. While its not fully hololens related is it still very useful to have in your hololens app. Is this relevant for this the holotoolkit?

**Comment by StephenHodgson** [comment]
Yes please.

**Comment by alca259** [comment]
I do my custom software :D

https://github.com/alca259/ImageBatcherResizer

**Comment by jessemcculloch** [comment]
@davesmits - I would love this extension!

**Comment by MichealReed** [comment]
Fantastic idea. I can't wait to see this added.
