### ISSUE TITLE
SpatialUnderstandingCursor is hidden behind UI elements

### ISSUE THREAD

**Issue by Zod-** [Microsoft/HoloToolkit-Unity#621]
The cursor in the SpatialUnderstandingExample disappears behind UI elements if it gets slightly rotated. For example if you look at the UI canvas in a 90° angle the cursor is displayed properly but after rotating
 the camera towards the edges, the cursor will disappears behind the canvas after a few degress.

Visible:
![cursorangle](https://cloud.githubusercontent.com/assets/5775094/25011934/3d27ab18-206f-11e7-939d-def9b79ae7c0.PNG)
Disappears at this point:
![cursorangle2](https://cloud.githubusercontent.com/assets/5775094/25011938/412d9f56-206f-11e7-89d2-6f99b3059092.PNG)
Edge of the frame:
![cursorangle3](https://cloud.githubusercontent.com/assets/5775094/25011942/4335b482-206f-11e7-9e40-3ee717c2648c.PNG)

In this case it's enough to up the DistanceFromCollision of the cursor from 0.01 to ~0.08 to work around it but this doesn't really fix the underlying issue. This also only works because the UI is always facing the camera so the set of angles will always be the same.

**Comment by StephenHodgson** [comment]
Most likely a symptom of the last bug you reported.

**Comment by Zod-** [comment]
Nah there is some some flickering in the cursor caused by the other bug otherwise it's something else. I also tested this with a commit that is before the merge of the pull request that caused the other. 

This is an issue about the z-index of the 2D UI elements in combination with the 3D cursor. I didn't include the scene view from the editor but in that one the cursor appears to be in front of the UI elements and not behind because the draw order is different from that view. 

In the game view the cursor gets drawn first and because it ends up having the same z-index it gets overdrawn by the UI elements. At least that's how I understood it so far.

**Comment by Zod-** [comment]
Scene view is showing the cursor:
![cursor1](https://cloud.githubusercontent.com/assets/5775094/25015852/e531fc2e-207d-11e7-8c14-9b2508b958b1.PNG)
Game view:
![cursor2](https://cloud.githubusercontent.com/assets/5775094/25015882/055584f8-207e-11e7-90b5-49da9b006faa.PNG)

**Comment by StephenHodgson** [comment]
Thanks for clarifying

**Comment by Zod-** [comment]
A solution for this could be to introduce a sorting layer for UI elements. When the cursor is focused on an UI object it could be assigned to that layer and have it be always be rendered above all UI elements. 

The reason to dynamically change the layers is that when the raycast passes through the UI and hits a wall behind it, it will still appear to be infront of the UI. So to make it appear behind the UI the sorting layer would have to be change depending on what is being hit.
![passthrough](https://cloud.githubusercontent.com/assets/5775094/25121392/db654032-2421-11e7-86c2-9cd05f34da30.PNG)

**Comment by Zod-** [comment]
I looked at the issue again and found out that changing the render queue on the cursor material fixes it too. Both the cursor and the UI material have a render queue value of 3000. Changing the cursor queue to 3001 fixes it.

Is there a reason the values are at 2000, 3000 and so on?
Like would I change it to 3500/4000 or is 3001 fine too.

**Comment by StephenHodgson** [comment]
I'd use the mesh cursor instead of the UI cursor then.  Let me know the results.

**Comment by Danta1st** [comment]
If you are using a canvas based cursor you could simply adjust the "Order in Layer" option on the canvas itself. 

This is a much preferred option compared to fiddling around with render queue options on the shaders.

What you are seing is propably a z-fighting issue between the two canvas instances. This solution will solve that permanently.

**Comment by StephenHodgson** [comment]
This was actually caused by custom raycast logic that needed to accommodate for the spatial mapping mesh.  Now correctly uses gaze manager result.
