### ISSUE TITLE
WorldAnchorManager causes WinRTScriptingObjectWrapper crash in Debug Mode

### ISSUE THREAD

**Issue by dixoncb** [Microsoft/HoloToolkit-Unity#623]
Using the HoloLens, the call to GetAsync() in WorldAnchorManager::Awake() never returns. A breakpoint on line 65 is hit, then the app crashes. Runs fine in Release mode. 

`WinRTScriptingObjectWrapper::InternalAddRef Reference Count cannot be zero
(Filename: C:\buildslave\unity\build\Runtime/ScriptingBackend/DotNet/ScriptingApi_DotNet.cpp Line: 661)
The program '[4144] test8.exe' has exited with code -2147483645 (0x80000003). `

We can replicate this on PCs with VS2017 Enterprise and Community, with Unity 5.6, and on two separate HoloLens devices.

**Comment by StephenHodgson** [comment]
`GetAsync` is never called in the editor

**Comment by gitAllender** [comment]
Just see this topic:
https://forums.hololens.com/discussion/2667/how-to-use-unity-world-anchors

Have the same problem with VS2017, Unity 5.60f3 and Hololense

**Comment by StephenHodgson** [comment]
Did you try the patch release? They seemed to have addressed a lot of windows store platform build fixes.

**Comment by gitAllender** [comment]
Updated. The same result.

**Comment by elbruno** [comment]
My 2 cents: tested with Unity3D 5.6.0p2, and I got the same error.

**Comment by StephenHodgson** [comment]
This only happens in a Debug build correct?

**Comment by StephenHodgson** [comment]
I believe this was a Unity bug and has been resolved in later editor releases. Please reopen if issue persists in Unity Editor 2017+

**Comment by dixoncb** [comment]
I can confirm this. I’m working with v2017.1.0f3, and all is well. Thank you.
