### ISSUE TITLE
Multiple errors on build

### ISSUE THREAD

**Issue by bkfichter** [Microsoft/HoloToolkit-Unity#624]
I was having issues with the latest download so I created a blank project with just the Holotoolkit package. Applied settings.

Versions:
Unity 5.5.0f3
VS 2017 15.1 (26403.7)

Build:
Universal 10
Holoens
D3D
Unity C# Projects

Error list:
Assets\HoloToolkit-Examples\SharingWithUNET\Scripts\GenericNetworkTransmitter.cs(114,57): error CS0246: The type or namespace name 'StreamSocketListener' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit-Examples\SharingWithUNET\Scripts\GenericNetworkTransmitter.cs(114,86): error CS0246: The type or namespace name 'StreamSocketListenerConnectionReceivedEventArgs' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit-Examples\SharingWithUNET\Scripts\GenericNetworkTransmitter.cs(159,55): error CS0246: The type or namespace name 'IAsyncAction' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit-Examples\SharingWithUNET\Scripts\GenericNetworkTransmitter.cs(159,79): error CS0246: The type or namespace name 'AsyncStatus' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit-Examples\SharingWithUNET\Scripts\GenericNetworkTransmitter.cs(81,17): error CS0246: The type or namespace name 'StreamSocket' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit-Examples\SharingWithUNET\Scripts\GenericNetworkTransmitter.cs(86,17): error CS0246: The type or namespace name 'StreamSocketListener' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit\SpatialMapping\Scripts\RemoteMapping\RemoteMeshSource.cs(140,45): error CS0246: The type or namespace name 'IAsyncAction' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit\SpatialMapping\Scripts\RemoteMapping\RemoteMeshSource.cs(140,69): error CS0246: The type or namespace name 'AsyncStatus' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit\Utilities\Scripts\TextToSpeechManager.cs(228,51): error CS0246: The type or namespace name 'IAsyncOperation<>' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit\Utilities\Scripts\TextToSpeechManager.cs(228,67): error CS0246: The type or namespace name 'SpeechSynthesisStream' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit\Utilities\Scripts\TextToSpeechManager.cs(66,17): error CS0246: The type or namespace name 'SpeechSynthesizer' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit\Utilities\Scripts\TextToSpeechManager.cs(67,17): error CS0246: The type or namespace name 'VoiceInformation' could not be found (are you missing a using directive or an assembly reference?)
v

Assets\HoloToolkit\SpatialMapping\Scripts\RemoteMapping\RemoteMeshSource.cs(182,37): error CS0246: The type or namespace name 'IAsyncOperation<>' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit\SpatialMapping\Scripts\RemoteMapping\RemoteMeshSource.cs(182,70): error CS0246: The type or namespace name 'AsyncStatus' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit\SpatialMapping\Scripts\RemoteMapping\RemoteMeshSource.cs(31,17): error CS0246: The type or namespace name 'StreamSocket' could not be found (are you missing a using directive or an assembly reference?)

**Comment by StephenHodgson** [comment]
Which scene are you building with?

**Comment by bkfichter** [comment]
I had it in an existing project and it stopped working. So I downloaded the latest version, packaged it, and imported it into an empty project. At first I just tried a blank scene with just the camera prefab. Then I tried Color Picker. Same bugs all around. Could it be a problem with the "Windows" namespace?

**Comment by StephenHodgson** [comment]
Yeah it looks like build settings errors of some sort, which is why you'd get the windows namespace errors.

**Comment by jessemcculloch** [comment]
Try updating the .net core from the Nuget Package Manager...

**Comment by StephenHodgson** [comment]
Also, I haven't had much luck with visual studio 17 and unity prior to 5.6

**Comment by bkfichter** [comment]
If you're not having any issues with 5.6 then I will just bump up.

**Comment by StephenHodgson** [comment]
Nope. Let me know how that goes.

**Comment by StephenHodgson** [comment]
https://github.com/Microsoft/HoloToolkit-Unity/issues/612

**Comment by bkfichter** [comment]
That fixed everything! Still kinda curious what the build issues are. I looked through and nothing jumped out.

**Comment by bkfichter** [comment]
I looked into 612 yesterday and it didn't seem to solve the issue. I just suggest everybody move to 5.6.

**Comment by StephenHodgson** [comment]
I suggest only moving to 5.6 if using vs 2017

**Comment by dixoncb** [comment]
The problem with 5.6 is that there's still a blocker with the WorldAnchorManager (https://forums.hololens.com/discussion/7203/vs2017-u5-6-crash-winrtscriptingobjectwrapper-internaladdref-reference-count-cannot-be-zero) which is not yet fixed.

**Comment by StephenHodgson** [comment]
I've been using the 10.0.1.4.14393 target build in the meantime. Thanks for the update.
