### ISSUE TITLE
Question: Why was GestureManager removed

### ISSUE THREAD

**Issue by Sacristan** [Microsoft/HoloToolkit-Unity#626]
Why was GestureManager was removed in commit 3c404ad3adf2570bd227b4a989f2999ea9522659 ? 

Is there a replacement or this should be handled individually ?

**Comment by StephenHodgson** [comment]
It was replaced by the input manager.

The input system was completely rewritten.

**Comment by Sacristan** [comment]
Ok. Thanks!
