### ISSUE TITLE
Move existing materials to FastConfigurable, delete old shaders

### ISSUE THREAD

**Issue by dbastienMS** [Microsoft/HoloToolkit-Unity#628]
With the superior performance in the new FastConfigurable and growth of features there, all my older shaders should be removed:

1. BlinnPhongConfigurable
2. BlinnPhongConfigurableTransparent
3. LambertianConfigurable
4. LambertianConfigurableTransparent
5. StandardFast
6. UnlitConfigurable
7. UnlitConfigurableTransparent
8. UnlitNoDepthTest
9. VertexLitConfigurable
10. VertexLitConfigurableTransparent

And matierals using them moved to use FastConfigurable.

**Comment by thebanjomatic** [comment]
@dbastienMS I can look at updating the materials used throughout the toolkit test scenes and examples, but is there a strategy for removing the old shaders without breaking user materials based on the old shaders when they upgrade to the latest toolkit?

**Comment by dbastienMS** [comment]
@thebanjomatic their materials will point to the old meta files - the only way I can think of to solve this is to have a script that rips through materials looking for ones that point to the old shaders and pointing them to the new one.  there's some work done on auto-migration in the editor script already.  depending on how well that works as you're converting, we can look into making that script or improving the auto-migration.  great question - this is a tricky but super important issue.

**Comment by dbastienMS** [comment]
You know I think it's fine for them to manually move things over - they can keep using the existing shaders if they want, they just won't be present in the htk going forwards.

**Comment by StephenHodgson** [comment]
@dbastienMS is there a way to mark a shader as obsolete?

**Comment by StephenHodgson** [comment]
Only thing I could think of was to move its folder location. For Example:
```
// Very fast shader that uses the Unity lighting model.
// Compiles down to only performing the operations you're actually using.
// Uses material property drawers rather than a custom editor for ease of maintenance.

Shader "HoloToolkit/Obsolete/BlinnPhong Configurable"
{
    Properties
    {
...
```

**Comment by dbastienMS** [comment]
Hah, I was just about to say the same thing!

I think either that approach or just removing them are both fine - if they're removed users moving from older HTK versions can still keep their old copies.

**Comment by StephenHodgson** [comment]
One small step at a time haha

**Comment by StephenHodgson** [comment]
@dbastienMS do you know anything about the UnlitTriplanar shaders?

**Comment by dbastienMS** [comment]
I don't - theoretically a triplanar shader should be combining axial textures in world space but this one does not appear to be doing that.

**Comment by StephenHodgson** [comment]
Yeah it seems to be used in all sorts of materials that don't do what you'd think. I'm thinking of making that one obsolete too and switching them to the fast configurable too lol.

**Comment by dbastien** [comment]
If it's a good replacement that'd be ideal - the fewer things the better!
