### ISSUE TITLE
Tagalongs need to face camera

### ISSUE THREAD

**Issue by flarb** [Microsoft/HoloToolkit-Unity#63]
Isn't it kind of weird how the tagalongs don't orient towards the camera? If you turn about 90 degrees off, the tagalong will be facing so far away from you it's impossible to access. 

I tried putting a simple lookat in the Tagalong's update (and restricted rotation to just Y) but I think it's messing up the visibility check with the bounding box so it floats out of view more often...but I'm not totally sure.

Any best practices for keeping a tagalong facing the player--or is this something we need to fix in the tagalong scripts?

**Comment by davidkline-ms** [comment]
I have always added a Billboard script to my Tagalong objects. That could easily be made a requirement.

**Comment by ChimeraScorn** [comment]
It would definitely be a cool option… Not sure if I would make it mandatory.

**Comment by flarb** [comment]
Ah never thought about using the billboard script on it. Although I think it would be better if they only rotate on the Y axis, so any interface buttons you may have on the tagalong are easily clickable (if the thing keeps rotating it might make it tricky)

Maybe a checkbox in the inspector for billboard, or Y-only billboard on the tagalongs would be good.

**Comment by jwittner** [comment]
@flarb Isn't the Pivot Axis of the Billboard script what you're looking for?

**Comment by flarb** [comment]
@jwittner oh! I haven't tried using it yet (I usually write my own billboarding stuff) I'll give it a shot, thanks!

**Comment by jwittner** [comment]
@flarb If that works for you, can we close this issue?

**Comment by jwittner** [comment]
Closing as last sense was that it was resolved via discussion.
