### ISSUE TITLE
I just pushed to master

### ISSUE THREAD

**Issue by killerantz** [Microsoft/HoloToolkit-Unity#632]
I was trying to get my local and remote branches updated to the latest version of HoloToolkit-Unity, but now I see one of them points to our master. Can someone revert may latest commit or let me know how to do it?

**Comment by StephenHodgson** [comment]
You should be able to revert fairly easy. 

Which git client are you using?

**Comment by StephenHodgson** [comment]
I'm actually really confused because some of the changes it says you made are things that already got merged into main... 

Any chance to revert your commit?

**Comment by killerantz** [comment]
Visual Studio

**Comment by StephenHodgson** [comment]
fixed

**Comment by killerantz** [comment]
Thanks,
