### ISSUE TITLE
TapToPlace script Small Issue

### ISSUE THREAD

**Issue by HaraldHeide** [Microsoft/HoloToolkit-Unity#636]
Have a feeling that we should check if the anchorManager.AnchorStore exists and are ready before Attach or Remove Anchors in the OnInputClicked handler.
Something like:
if (anchorManager.AnchorStore != null)
{
// Add world anchor when object placement is done.
anchorManager.AttachAnchor(gameObject, SavedAnchorFriendlyName);
}

**Comment by jessemcculloch** [comment]
This check is already happening in the start method

**Comment by StephenHodgson** [comment]
@jessemcculloch, your last PR fixed this issue, correct?

**Comment by jessemcculloch** [comment]
I didn't explicitly make a change to fix this. There is a check in the start method to verify that the anchor store exists, however I suppose it could get removed at some point between start running and when the placement tries to create an anchor.

**Comment by StephenHodgson** [comment]
Looking through the WorldAnchorManager, it looks like it doesn't matter if the AnchorStore is null when we call AttachAnchor, because we're using a queue that will wait until the AnchorStore is initialized before attempting to add the anchor.

**Comment by jessemcculloch** [comment]
So in theory we can close my PR, it's not necessary?

**Comment by jessemcculloch** [comment]
Closed my PR, I think this issue can be closed as well
