### ISSUE TITLE
Build window crashes unity

### ISSUE THREAD

**Issue by firativerson** [Microsoft/HoloToolkit-Unity#648]
Hello , I recently upgraded to unity 5.5 2f1 and to latest realase of HTK and I'm using VS15.
Cant seem to build, unity crashes right away and only thing I can find from logs is  "Read from location 00000010 caused an access violation."

There are similar topics but did not find a clear answer to this issue.

**Comment by jessemcculloch** [comment]
To use the build window, I often find that the key is to do an initial build from unity, then open the visual studio solution, set your VS to Master, x86, Device, and deploy to it.  From that point forward, I can generally use the build window from the HTK without issue

**Comment by firativerson** [comment]
oops that's my bad. I thought I switched to uwp. But this is still a bug for unity that it is crashing if the wrong platform is picked
