### ISSUE TITLE
why is ImportExportAnchorManager part of tests?

### ISSUE THREAD

**Issue by davesmits** [Microsoft/HoloToolkit-Unity#652]
The ImportExportAnchorManager is a pretty important part of making a great shared experiences. Why is this part of HoloToolkit-Tests and not more in the core?

Beside i have two issues with this class:

- If InitRoomApi is unable to move to the next state of the class within the same frame it will be called multiple times. While this is not happening very often it will happen sometimes. I suggest adding an extra state that it is initializing the room api

- running the app in the unity editor (for the recording in the spectator view) causes to create new room while there is already a room.

This happens on this line of code: if (roomManager.GetRoomCount() == 0)
one on the time times the roomcount is 0 while i am sure there is a room already created. when adding a second delay before really initializing works around it. Any ideas on this. Fixing the GetRoomCount() seems impossible since not having the code

**Comment by StephenHodgson** [comment]
This class is in tests because the needs of other developers may require a lot of modification of this class to function as desired. Thanks for bringing these two issues up.  If you would be so kind to submit new issues for each, maybe someone (or yourself) will be kind enough to submit a PR addressing them.

**Comment by davesmits** [comment]
@StephenHodgson well i can fix the first issue and happy to make pull request for that. More concerned about the second. i dont have the code of GetRoomCount() (wrapper for that sharing service) so can't solve the root cause but can do the same 'hack' we used with the additional delay. How do you think about this?

**Comment by StephenHodgson** [comment]
That would be wonderful.  I have not personally experienced the second issue, though, so I can't comment on it until I have a better understanding of what's happening exactly.  Generally I won't start the editor until my HoloLens is already connected and uploaded an anchor.

**Comment by keveleigh** [comment]
@davesmits The sharing service's source code is in the [HoloToolkit repo](https://github.com/Microsoft/HoloToolkit/tree/938bc028afa96c82665bc78f3a4e68e357fbad8d/Sharing)! Here's a link to some code implementing [GetRoomCount()](https://github.com/Microsoft/HoloToolkit/blob/938bc028afa96c82665bc78f3a4e68e357fbad8d/Sharing/Src/Source/Common/Private/RoomManagerImpl.cpp#L44).
