### ISSUE TITLE
Building herror

### ISSUE THREAD

**Issue by EmreSuzenExia** [Microsoft/HoloToolkit-Unity#653]
Hi,

When I try to build (HoloToolkit -> Build Window)
I got 10 errors:

![image](https://cloud.githubusercontent.com/assets/17028416/25742289/1568d044-318f-11e7-9c27-ef540cbe54a4.png)

I don't understand it, can someone help me please ?

**Comment by jessemcculloch** [comment]
We need significantly more info when helping to troubleshoot something like this.  What versions of Visual Studio and Unity are you running.  Have you made an initial build using Unity and Visual Studio successfully?  It appears you need to put in your username and password for the deploy.  There is just not enough info for us to help at this point.

**Comment by StephenHodgson** [comment]
Looks like you may not have the correct build settings.
