### ISSUE TITLE
How to not load system-global space data on start?

### ISSUE THREAD

**Issue by YoungxHelsinki** [Microsoft/HoloToolkit-Unity#659]
I'm trying to build an app like "Young Conker" where you can have your own spatial mapping, isolated from the system-global space data. I looked at `SpatialMappingObserver` and `SpatialMappingManager` but cannot find where it's loading from the system.

**Comment by YoungxHelsinki** [comment]
I tested with "Young Conker" again and it seems like even that game is using system-global space data BUT it can somehow smartly **select specific parts of the data.** 

Here's how I tested:
1. Run "Young Conker"
2. Scan new area and save it.
3. Repeat step 1 & 2 few more times. Check system-global space size. They get larger and larger in each iteration.
4. Now delete your system-global space from `Settings`.
5. Run "Young Conker"
6. Try to load saved spaces.
7. None of the saved spaces will be usable.

Here's my understanding about spatial mapping logic in HoloLens:
* Every app uses system-global space which is shared by all other apps on the HL.
* All scanned data within an app will be shared by all other apps on the HL.
* Space data cannot be deleted programmatically.
* An app can ***save*** space like "Young Conker" but it's just referring to the system global space. 

Am I understanding correctly?

**Comment by thebanjomatic** [comment]
More or less sounds correct, its also worth noting that the spatial mapping / understanding technology from Conker and Fragments has been made available in the HoloToolkit: https://github.com/Microsoft/HoloToolkit-Unity/tree/master/Assets/HoloToolkit-Examples/SpatialUnderstanding

https://developer.microsoft.com/en-us/windows/mixed-reality/case_study_-_expanding_the_spatial_mapping_capabilities_of_hololens

**Comment by jessemcculloch** [comment]
Just one correction.  When you say all scanned data will be shared by all other apps, that's not quite correct.  The mesh that is created by mapping can be manipulated or changed in app, which you obviously would not want to happen in your other apps.  I recommend you look at this post in the forums for the best explaination - https://forums.hololens.com/discussion/comment/8737#Comment_8737

**Comment by YoungxHelsinki** [comment]
Thank you. It's weird that this developer device is so limited. It limits academic research ability hugely.
