### ISSUE TITLE
Simplify options of FastConfigurable, provide advanced mode

### ISSUE THREAD

**Issue by niklas87** [Microsoft/HoloToolkit-Unity#660]
I really appreciate the performance and variability of the new FastConfigurable shader. But I'd suggest to simplify the settings a little bit:

I had a few issues when trying to use transparent or semi-transparent materials. After reading up on Alpha Blending, I was able to configure the shader in the way I wanted to use it (SrcAlpha->One, Add), but objects in the depth were hidden by a completely transparent object until I noticed that I have to turn ZWrite off.

Therefore, for easier usage of the shader, I propose to wrap some settings into a easier understandable setting (e.g. "Opaque", "Transparent", etc. as given in the standard shader) and maybe add a more advanced mode, enabled by setting a simple flag in the shader settings. This would enable users which are new to "rendering mathematics" to simply select a descriptive option such as "Transparent" to automatically set the more advanced settings for SrcBlend and DestBlend and ZWrite and so on.

**Comment by StephenHodgson** [comment]
@dbastienMS

**Comment by dbastienMS** [comment]
There is such a thing!  At the top of the editor you can choose transparent, etc modes.

**Comment by niklas87** [comment]
I'm sorry - you're totally right. It seemed that somehow a few files wasn't copied to my working directory. I've now set up a symlink to the repo so this can't happen again.

Anyway, take this issue as a thanks then. The updated shader configuration panel looks great! 👍
