### ISSUE TITLE
Unity 2017 beta, error on compile

### ISSUE THREAD

**Issue by genereddick** [Microsoft/HoloToolkit-Unity#669]
In case this comes up for anyone else, I just installed the latest Unity beta, 2017.1.0b56 to give it a try, and using latest HoloLens code. A single error blocks build:

CustomMaterialEditor.cs, line 103

    matEditor.BeginAnimatedCheck(scaleOffsetProp);

Looks like the signature changed and it now requires (Rect totalPosition,...)  as a first param. Easy fix to get it to compile (though not sure of any other impact).

    matEditor.BeginAnimatedCheck(new Rect(), scaleOffsetProp);

**Comment by StephenHodgson** [comment]
Thanks for the report. We don't normally support the beta versions of the editor. Looks like those methods got depreciated. Let's wait and see if the release will automatically​ update these or mark them at least as obsolete.

**Comment by genereddick** [comment]
@StephenHodgson Understood. 

Just wanted to try out using .NET 4.6 with Unity. That is the only issue I have hit so far.
