### ISSUE TITLE
Need an easy way to switch between scenes when testing HoloToolkit-Unity

### ISSUE THREAD

**Issue by ForrestTrepte** [Microsoft/HoloToolkit-Unity#674]
There are currently more than 50 scenes in the project. Someone may want to try out multiple different scenes in order to browse the features that are available in HoloToolkit or in order to test a change to make sure it hasn't broken things.

Currently, in order to run scenes on HoloLens, I open them in Unity, make a Unity build, make a Visual Studio build, and wait for the HoloLens app to load.

Is there a easier way to do this that I'm missing?

**Comment by ForrestTrepte** [comment]
One idea I have is to create a Launcher scene. The launcher scene would enumerate the other scenes, providing buttons to jump into them.

Some issues that would need to be decided:
1) The Unity build would have to include the desired scenes. Would we include all 50+ scenes in the build settings? (Possibly this would increase build times and defeat the nice current behavior that the scene that is open in the editor is automatically included as the startup scene.) Or would the user need to manually find each of the scenes they want and drag them into the build settings?
2) After launching a scene, can you return to the launcher scene? Perhaps the launcher scene loads the new scene additively and hangs around with a button or voice command to return to the launcher menu. (This would mean that scenes would need to shut down cleanly and be able to be restarted multiple times.)

Or maybe someone has a better idea?

**Comment by KumaVolt** [comment]
If you want to try out the different scenes is [Holographic remoting](https://blogs.unity3d.com/2016/09/29/introducing-holographic-emulation/) not a option?

**Comment by ForrestTrepte** [comment]
Thanks, KumaVolt. That's a good idea and I will use that approach for fast browsing. However, for testing that scenes are working prior to committing a change I would like verify them running fully on device. And for browsing features, it could be nice to have the full on-device experience because remoting introduces some lag and visual artifacts.
