### ISSUE TITLE
Failure to compile APPX with VS2017-only versions of Windows 10 SDK does not instruct the user on how to fix (HTU/Unity only seems to support VS2015 which needs an older SDK version)

### ISSUE THREAD

**Issue by The-MAZZTer** [Microsoft/HoloToolkit-Unity#685]
[Edit: Correction: I had VS2015 installed but none of the bundled Windows 10 SDKs. The SDKs I had were for VS2017.]

I receive an error about missing the Windows Mobile SDK 10.0.15063.0 (eg Windows 10 Creator Update version) even if the SDK is installed.

The issue seems to be that the HoloToolkiit-Unity is trying to use MSBuild v14 (which is present) but the Windows 10 SDK download page specifically says the 15063 SDK is not usable in VS2015 (v14?) or earlier versions.

If I manually invoke the build process using MSBuild v15 from a VS2017 developer cmd.exe (using the start menu shortcut) the APPX build works fine.

If I try to switch to MSBuild v15 using the HoloToolkit-Unity UI it can't find it. It seems like it is looking for a registry key which does not contain an entry for v15. I have to manually patch the code to hardcode the location (in C:\Windows\Microsoft.NET\v4.0.XXXX whatever\MSBuild.exe).

However there are still further issues since it still won't compile using HoloToolkit-Unity as I receive the error: MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v11.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. There must be something else the Developer console shortcut for VS2017 is doing that HTU needs to do.

(It may be relevant that I am targeting XAML in Unity for Hololens keyboard support.)

I am running Unity v5.6.1 on Windows 10 x64 Build 14393.1198. (This is a work PC and that is the newest approved version of Windows to my knowledge.)

**Comment by The-MAZZTer** [comment]
After lots of experimentation it seems you NEED VS2015 plus the VS2015-bundled Windows 10 SDK versions. Unity will display newer SDK versions in the build settings but if you select one of these the build fails.

**Comment by StephenHodgson** [comment]
Thanks for the report.  This has been an issue for me for a few weeks while trying to migrate to VS2017 as well.
