### ISSUE TITLE
Are the examples no longer included in the Holotoolkit Unity Package or is it just me? 

### ISSUE THREAD

**Issue by oladapooni** [Microsoft/HoloToolkit-Unity#686]
Do we just download the examples individually or is there a separate package I need to download?

**Comment by StephenHodgson** [comment]
That is correct.  They are a separate asset package.

**Comment by oladapooni** [comment]
Where can I download it? @StephenHodgson

**Comment by StephenHodgson** [comment]
The examples can be downloaded directly by forking this repository. Many of the test scenes can be found in the HoloToolkit-Unity-Tests package at https://github.com/Microsoft/HoloToolkit-Unity/releases: [HoloToolkit-Unity-Tests-v1.5.7.0.unitypackage](https://github.com/Microsoft/HoloToolkit-Unity/releases/download/v1.5.7.0/HoloToolkit-Unity-Tests-v1.5.7.0.unitypackage)

**Comment by StephenHodgson** [comment]
I think I'll also start including the HoloToolkit-Unity-Examples unity package in this and future releases as well.

**Comment by oladapooni** [comment]
Thank you, and I definitely hear you about the more lightweight toolkit file.
