### ISSUE TITLE
NearFadePlane sample

### ISSUE THREAD

**Issue by davesmits** [Microsoft/HoloToolkit-Unity#690]
are there any examples how the nearfadeplane works? tried to get it working but not getting it to work

**Comment by thebanjomatic** [comment]
@davesmits I usually add the script to the camera with the camera's near plane fade set to 0.25, and the near plane fade script set to fade from 0.85 to 0.3. The only other thing you need to do is ensure that the shaders you are using support it. This is true for most of the holotoolkit shaders, and you can look at their source to see how to apply it to your own shaders as well.
