### ISSUE TITLE
Reset All command in SpeechInputSource scene doesn't function

### ISSUE THREAD

**Issue by ForrestTrepte** [Microsoft/HoloToolkit-Unity#704]
1) Run SpeechInputSource scene
2) Gaze at a sphere and say "green". The sphere turns green.
3) Say "reset all".
expected: Sphere turns back to grey.
result: Sphere remains green.

**Comment by StephenHodgson** [comment]
Hey there, this issue is addressed in https://github.com/Microsoft/HoloToolkit-Unity/pull/533

**Comment by ForrestTrepte** [comment]
Thanks for letting me know! Confirmed that this is fixed in #533. I'll review the larger change (dictionation? cool!) tomorrow.

**Comment by ForrestTrepte** [comment]
I didn't make it all the way through the pull request, but I added some feedback comments and will continue reviewing tomorrow.

**Comment by StephenHodgson** [comment]
No worries, every little bit is appreciated.

**Comment by ForrestTrepte** [comment]
Correction, actually I don't think this is fixed in #533. I'm not sure what happened, but I may have merged incorrectly when I tested this before. Running StephenHodgson/HTK-Dictation, I am not seeing an effect for "reset all".

**Comment by StephenHodgson** [comment]
I'll double check this later this evening. Thanks

**Comment by StephenHodgson** [comment]
@ForrestTrepte, just tested this out. Works for me here.

Try cleaning any pending changes and test again?
