### ISSUE TITLE
ShareingServer

### ISSUE THREAD

**Issue by Joeeeeeeeee** [Microsoft/HoloToolkit-Unity#720]
unity5.6.1f1&HoloToolkit-Unity-v1.5.7.0

UnityLog:
SharingService [..\..\Source\Common\Private\XSocketManagerImpl.cpp (728)]: Failed to create incoming connection on port 20605.  Error code: 5
UnityEngine.Debug:LogError(Object)
HoloToolkit.Sharing.Utilities.ConsoleLogWriter:WriteLogEntry(LogSeverity, String) (at Assets/HoloToolkit/Sharing/Scripts/Utilities/ConsoleLogWriter.cs:23)

ShareingServerLog:
Warning: SharingService [..\..\Source\Common\Private\SessionListHandshakeLogic.cpp (96)]:
***************************************************************
List Server Handshake Failed: Invalid schema version.
Expected: 15, got 17
Please sync to latest XTools
***************************************************************
SharingService: ListServer: Handshake failed with error 2

**Comment by StephenHodgson** [comment]
See https://github.com/Microsoft/HoloToolkit-Unity/issues/487
