### ISSUE TITLE
Custom UI/Default shader causing confusing with Unity's UI/Default shader

### ISSUE THREAD

**Issue by jochao** [Microsoft/HoloToolkit-Unity#75]
HoloToolkit has a cursor asset that uses a shader called UI-default.shader in Assets\HoloToolkit\Input\Models\Cursor\UI-Default.shader".  As a result, Unity confuses using its own UI\Default shader and using HoloToolkit's custom UI\Default shader.

To fix this, the custom shader should be renamed and appropriately placed in HoloToolkit\Utilities\Shaders folder.

**Comment by NeerajW** [comment]
Should we put the shader in Input\Shaders folder instead?
To avoid cross folder dependencies.
