### ISSUE TITLE
Input Events get fired twice - GlobalListener

### ISSUE THREAD

**Issue by HoloFan** [Microsoft/HoloToolkit-Unity#756]
Hello,

I came across a strange thing. 
When you attach a script which acts on IInputClicked (or any other input interface) to, for example, a cube and also attach the Script "SetGlobalListener" to the cube, the event will be fired twice when gazing at the cube and initating the event (i.e. tapping).

One can resolve this with using the following mechanism:

    public void OnInputClicked(InputClickedEventData eventData)
    {
      if (!eventData.used)
      {
        eventData.Use();
        // Do stuff
      }
    }

Maybe we should adapte the SpeechInputHandler to take this into account. As there we do not implement the interface ourselfs.
Or maybe someone else has some other idea how to prevent this? 

Another thing is, that the SpeechInputHandler has the option to register as GlobalListener. But when attaching the Script "SetGlobalListener" at the same time the GameObject is actually registered twice as a global listener. Maybe we can check inside the InputModule whether a GameObject is already a GlobalListener?

**Comment by StephenHodgson** [comment]
https://github.com/Microsoft/HoloToolkit-Unity/issues/658

**Comment by StephenHodgson** [comment]
@HoloFan, That is a good fix, but the root of the problem lies in the `InputManger` itself. We needed to move the handling of the global listeners only if we didn't handle the event by any other objects first.

**Comment by StephenHodgson** [comment]
@HoloFan, after further discussion I think that maybe we need to clarify how you've setup your UI.

Can you give us some details about your setup, so we can fix this issue?

**Comment by StephenHodgson** [comment]
@HoloFan, let's take a look at your implementation, and see if there's another way we can handle your input without getting double events fired.

**Comment by HoloFan** [comment]
@StephenHodgson : I just read the discussion and I agree that we should not change the input Manager just now. But rather some time later after a through-out discussion about benefits and challenges.

For the start I can work with the work-around stated in my starting post. For another implementation I have to take a deeper look at my project. Maybe there is a better way to handle this.

**Comment by StephenHodgson** [comment]
@paseb
