### ISSUE TITLE
GazeManager default GazeTransform does not always default to Camera.main.transform

### ISSUE THREAD

**Issue by 4random** [Microsoft/HoloToolkit-Unity#778]
After deleting a GameObject and adding a new one I observed the following behaviour:
Before the mentioned change the HoloToolkit Basic Cursor worked perfectly. After that change I managed seeing the cursor by fast moving my had (I see the cursor at the right edge of the HoloLens screen). Without any head movement the cursor is not visible. The cursor works fine in the Unity Play mode.
The reason for that behaviour was that the Camera.main.transform reference address changed after the GazeManager initialisation `GazeTransform = Camera.main.transform;`. I figured that out by modifying the function  UpdateGazeInfo of the GazeManager:
```
private void UpdateGazeInfo()
{
            Vector3 newGazeOrigin = GazeTransform.position;
            Vector3 newGazeNormal = GazeTransform.forward;
            Vector3 newGazeOrigin2 = Camera.main.transform.position;
            Vector3 newGazeNormal2 = Camera.main.transform.forward;
}
```
The two approaches were not returning the same values!

I fixed the issue by setting the GazeTransform explicitly to the HoloLens Camera.

Due to this observation I suggest referring to the Camera.main directly in the GazeManager and not via a stored reference (in the default case where the GazeTransform is not set by the user).

I am using HoloToolit 1.5.7, Unity 5.6.2f1 and Vuforia 6.2.10

**Comment by StephenHodgson** [comment]
The reason for this is to smooth the gaze position.

**Comment by 4random** [comment]
Unfortunately I cannot provide you the code to reproduce it. Additionally I tried making a movie but I am not able to provoke the cursor being displayed. Well, I am not able to see the cursor on any occasion, sometimes I see it when I fast move my head and sometimes not. The smoothing is the reason that I am able to see any cursor since the main camera transformation is wrong.

In other words:
At initialisation (and only at initialisation) `Camera.main.transform; ` is not returning the HoloLens main camera. Let's assume that the transformation of one of the side cameras is returned. When I fast move my head due to the smoothing I am sometimes able to see the cursor (as mentioned only at the edge of the screen since it is "behind" the movement of the head due to the smoothing). Gazing at an object does also not return any object as hit object. I have to turn my head away from the object so that I can't see it anymore to get a raycast hit.
In fact this might be a Unity bug but it can be omitted by referring directly to the main camera transformation inside the `UpdateGazeInfo()` where the transformation is set correctly during the `Update()` steps.

@StephenHodgson: if you think it's worth fixing that bug leave the Issue open, otherwise close it since the easy workaround is as mentioned by dragging the HoloLensCamera to the GazeManager GazeTransform field in the Unity editor.

**Comment by 4random** [comment]
The following link is describing the same problem.
https://developer.vuforia.com/forum/hololens/cursor-issues-holotoolkit-and-vuforia

**Comment by StephenHodgson** [comment]
I wonder if it would help if the contents of start were moved to awake. Where we're setting the main camera if the gaze transform is null.
```
if (GazeTransform == null)
{
    if (Camera.main != null)
    {
        GazeTransform = Camera.main.transform;
    }
    else
    {
        Debug.LogError("Gaze Manager was not given a GazeTransform and no main camera exists to default to.");
    }
}
```

**Comment by StephenHodgson** [comment]
I'm also curious if you've got more than one camera with a main camera tag in your scene. This could also confuse the system when trying to figure out which is the main camera when calling `Camera.main`
