### ISSUE TITLE
Unity 2017.1.0f3 - HoloToolkit Menu not available after import

### ISSUE THREAD

**Issue by Masi5192** [Microsoft/HoloToolkit-Unity#794]
Hey,
i tried to import the HoloToolkit (Build by me with  Unity 2017.1.0f3 and the guide: https://github.com/Microsoft/HoloToolkit-Unity/blob/master/GettingStarted.md) into new projects in Unity 2017.1.0f3. 
The import itself runs with one error:
"Assets/HoloToolkit/UI/Scripts/Keyboard.cs(582,9): error CS0103: The name `m_Dictation' does not exist in the current context"

But my main problem is that the HoloToolkit Menu is not available. Is there a option to bring it back? Or is this a Problem with Unity 2017.1.0.f3?

**Comment by jessemcculloch** [comment]
You need to resolve the keyboard error before the menu will show up.  Any errors will stop the loading of the editor code files from completing, which is what creates and populates the HoloToolkit Menu.

**Comment by paseb** [comment]
Did you change the target to WSA in the build settings?  There appears to be a missing ifdef for UNITY_WSA that's causing this if you're not targeting WSA.

**Comment by paseb** [comment]
Updated with a fix for the issue in [pull request 795](https://github.com/Microsoft/HoloToolkit-Unity/pull/795).
