### ISSUE TITLE
Holographic emulation not rendering to Hololens

### ISSUE THREAD

**Issue by carlosbarraganrey** [Microsoft/HoloToolkit-Unity#799]
I'm experiencing an issue with the holographic emulation, not being able to render any scene to my Hololens as remote device. 

The Holographic emulation tab shows the green Connected indicator, and the "Remote holographic player" in the Hololens gets in ready state, but when I press Play nothing renders to the Hololens. In the editor, I see the camera is moving along with the Hololens with my head movements, and the Game tab shows correctly what should be rendered in them, but nothing is rendered in the Hololens, neither in the Camera preview in the Scene tab of the editor, just black.

I've already tried formatting my laptop, updating Windows10 Pro to the very last version, reinstalling all the necessary tools, connecting to different Wifi networks, and tried with Unity versions 5.5.4f1, 5.6.1f1, 5.6.2f1, 2017.1f. In all of them I get the exact same problem.

I'd really appreciate any help with this, thank you!

**Comment by Jihosong** [comment]
The issue gone after deploying the app to HoloLens- Holographic emulation seems to cause the problem.

**Comment by StephenHodgson** [comment]
Make sure you have MSAA disabled.

**Comment by StephenHodgson** [comment]
Is this issue directly related to an issue you're having with part of the HoloToolkit, or just with the Holographic Emulation in general?

**Comment by carlosbarraganrey** [comment]
Hi @StephenHodgson, thanks a lot for your answer. I have tried with MSAA disabled, as well as combined with HDR enabled/disabled, which I read as a solution in another thread. 

The problem is with the Holographic Emulation module, since I experience the same issue with projects not using Holotoolkit, but that run in the Hololens device without problem after building them.

**Comment by StephenHodgson** [comment]
Yeah I thought it sounded like a Unity Bug. Gonna close this, please add to this thread if needed.
