### ISSUE TITLE
Is there a way create a menu, similar to the holo start menu (Movement)?

### ISSUE THREAD

**Issue by pampas93** [Microsoft/HoloToolkit-Unity#802]
I wanted to know if there a way to create a menu/gameObject which will follow the movements of camera; just like the Holo Start menu.
To describe a little more, Just like how the start menu doesn't move until you look away from the FOV, can I create a menu which moves similar to it?

**Comment by HoloFan** [comment]
Take a look at the "Tag-Along"-Scripts. There are a few different ones which might fullfill your requirements. And don't forget to attach the Billboard-Script to force the menu to face the camera.

**Comment by pampas93** [comment]
@HoloFan Perfect. Works like a charm.
