### ISSUE TITLE
Cursors Render behind UnityUI on Unity 2017

### ISSUE THREAD

**Issue by hayalk** [Microsoft/HoloToolkit-Unity#804]
The problem is that the cursor now renders behind the UnityUI at about the same distance as the "near clipping plane" in the Main Camera. I've set the canvas to Z depth 2. And my "near clipping plane" is 0.85

![image](https://user-images.githubusercontent.com/2148404/28613374-dba7a1b6-720f-11e7-9e94-4b8b2a76a328.png)

I've been comparing the results between unity 5.6 and 2017. Nothing much seems to have changed in the GazeManager.cs but in "RaycastUnityUI"

`EventSystem.current.RaycastAll(UnityUIPointerEvent, raycastResultList);`

Seems to account for the near clipping distance too in unity 2017 and always returns 2.9 as the distance for the objects in "raycastResultList". It does not in unity 5.6. In GazeManager.cs - RaycastUnityUI there is code to manually account for this

`float uiRaycastDistance = uiRaycastResult.distance + Camera.main.nearClipPlane;`

So in 2017 it accounts for the nearClipPlane twice and renders all cursors behind the UI elements. I'm guessing that you do not need the "+ Camera.main.nearClipPlane" anymore.

**Comment by Neuxxx** [comment]
I found the same behavior.

+1

**Comment by StephenHodgson** [comment]
I'll look into this today. Thanks for the report.

**Comment by StephenHodgson** [comment]
Problem is, I'm not sure if this is a bug in the editor, or if we should accommodate this as a bug in the HTK.

**Comment by StephenHodgson** [comment]
Found this in the[ 2017.1 release notes](https://unity3d.com/unity/whats-new/unity-2017.1.0):
- UI: Fixed GraphicRaycaster Ray-cast distance value (848130)

**Comment by hayalk** [comment]
Great! So the HTK was compensating for a long time Unity bug all along.

**Comment by StephenHodgson** [comment]
Haha, yeah, pretty much
