### ISSUE TITLE
GestureManager to call OnSelect on focused object from Unity

### ISSUE THREAD

**Issue by stbertou** [Microsoft/HoloToolkit-Unity#81]
Hi all

Another small change that would make it easier to work straight from the editor.
It would be great to call the "OnSelect" message when in the editor we either right mouse click or press a specific key (enter or space) like in the emulator.
Any thoughts?

-s

**Comment by NeerajW** [comment]
@stbertou that sounds like a good idea. 
Would you like to implement this feature?

**Comment by jwittner** [comment]
@stbertou I'm all about solutions that match the emulator! =)

**Comment by SUBERE23** [comment]
I have just been using
void OnMouseDown(){

OnSelect();

}

Has worked well for the most part.

**Comment by stbertou** [comment]
OK no worries I'll put a pull request later today

**Comment by stbertou** [comment]
https://github.com/Microsoft/HoloToolkit-Unity/pull/83

btw sorry about that looks like the PR contains both kind-of related changes, next time I'll make sure to create a branch for each feature

**Comment by NeerajW** [comment]
#83 added this functionality. Closing issue.
