### ISSUE TITLE
Input Manager makes Unity Player in Editor Freeze

### ISSUE THREAD

**Issue by reillydonovan** [Microsoft/HoloToolkit-Unity#811]
This is somewhat of a strange issue and it is not consistent across machines.  For some reason whenever the Input Manager is active Unity will freeze when I hit play within the editor.  If I disable the Input Manager everything plays fine.  I can also reactivate the manager for build and it works fine when published to the headset, its just a little tedious to have to disable/enable the manager every time I want preview my progress.  Any ideas at as to what might cause this and a way to resolve it?  Thanks.

Using the latest Unity 2017 & Holotoolkit package.

**Comment by AndrejRu** [comment]
#710 This should be it.

**Comment by StephenHodgson** [comment]
![enabledevmodewin10](https://user-images.githubusercontent.com/13334553/28676740-4e3a2e66-72a0-11e7-9510-c4cadf1d64ca.PNG)
