### ISSUE TITLE
Link in wiki to "Gestures in Unity" does not work

### ISSUE THREAD

**Issue by brean** [Microsoft/HoloToolkit-Unity#818]
[Input](https://github.com/Microsoft/HoloToolkit-Unity/wiki/Input) points to [Gestures in Unity](https://developer.microsoft.com/en-us/windows/mixed-reality/gestures_in_unity) which does not exist.

**Comment by atouchet** [comment]
The link should probably be changed to: https://developer.microsoft.com/en-us/windows/mixed-reality/gestures_and_motion_controllers_in_unity

**Comment by StephenHodgson** [comment]
Yeah I think MSFT broke the url links again instead of doing a proper redirect.
