### ISSUE TITLE
Documentation is hard to navigate and collaborate on.

### ISSUE THREAD

**Issue by jwittner** [Microsoft/HoloToolkit-Unity#82]
Right now we've got documentation spread throughout the README and the Wiki. This causes a few problems:

- The front page of our GitHub is polluted with in-depth scripting documentation.
- The wiki documentation is hard to collaborate on.
- Documentation is hard to navigate and doesn't connect well.

After investigating using pages ( see comment below ) I'm recommending we simply reorganize the wiki to look something like this:

- Manual
 - Logical descriptions of systems, like the sections of the wiki we have now
 - Descriptions of prefabs and the exposed editor data, should include screenshots from the editor
 - Tutorials
 - Should contain links to relevant Scripting API sections.
- Scripting API
 - API descriptions of script types and their API
 - All the descriptions that currently live in the README
 - Should contain links to relevant Manual sections.

It'd be nice to auto-generate the Scripting API section someday, which should be possible given some VS XML documentation to Markdown Open Source projects out there.

**Comment by jwittner** [comment]
Looks like Jekyll, which makes using Github Pages nice and easy with Markdown support, isn't officially supported on Windows. I think it's probably still worth moving to Pages over the wiki because all of my reasons above hold except that moving the current documentation over is a little more difficult.

**Comment by jwittner** [comment]
After configuring Jekyll and creating a page I think it's too much of a burden to contributing to documentation. Perhaps we'll have to live with making changes in the Wiki. Looks like the wiki is cloneable and from my own fork I was able to modify the Markdown and push.

I do feel that this lacks some of the nicety of the PR model for contributing changes, but feel it's made up for in the ease of avoiding the issues with Jekyll on Windows. I'm amending my recommendation above.

**Comment by NeerajW** [comment]
Thanks Josh. I will also keep thinking on how to make this better.

**Comment by jwittner** [comment]
Ok if I pursue moving the scripting documentation out of the README and into the Wiki?

**Comment by NeerajW** [comment]
For making the README lighter, let's split up the bigger readme into smaller readme's in each feature folder.

**Comment by jwittner** [comment]
@NeerajW You're thinking we should put the feature area .md files inside the Unity asset folders for each area? I'm thinking maybe we just make aptly named files at put them at the root level. Or maybe a docs folder with files named after the feature are?

**Comment by NeerajW** [comment]
Most open source projects but README.md for each folder area where developers need to read about components. So let's for now split the README into multiple ones inside the feature folders.

1. Easiest access to readme inside feature area.
2. Common practice on open source projects which seems to work.
3. Separate docs folder may be trickier to find / extra effort to go read.
