### ISSUE TITLE
Voice command implementations?

### ISSUE THREAD

**Issue by jvhgamer** [Microsoft/HoloToolkit-Unity#822]
Can I assign the' Response' editor fields for object and function at run-time in the KeyManager script component? Link to a visual of what I am attempting to describe here

**Comment by StephenHodgson** [comment]
"Select" is actually a reserved keyword by the Win 10 Operating System.

**Comment by jvhgamer** [comment]
@StephenHodgson How is the voice command "Select" performing an Air Tap gesture? I never implemented voice commands.

**Comment by StephenHodgson** [comment]
Like I said, It's built into the OS, and Unity & MSFT engineered it to perform the equivalent to a click.  Even if you don't have the `InputHandler` and just use the build in `EventSystem`, you'd get a click event.

**Comment by jvhgamer** [comment]
Oh, I misinterpreted that from what you said earlier. So then how to implement my own custom gestures? Would I only need the ISpeechHandler and SpeechInputSource scripts and implement the keywords/responses in the editor?

**Comment by HattMarris1** [comment]
https://developer.microsoft.com/en-us/windows/mixed-reality/voice_design

Looks like there are only two reserved system commands to worry about: "Select" and "Hey Cortana"

**Comment by StephenHodgson** [comment]
No worries, and for custom gestures create a new script and implement the appropriate interfaces.

**Comment by jvhgamer** [comment]
@StephenHodgson Not to ask for a working demo, but even after browsing through HoloAcademy 212's Voice tutorials I'm still confused. When you say appropriate interfaces could you please be specific?

**Comment by StephenHodgson** [comment]
[Documentation](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Input/README.md#input-module-design).  (Sorry, not trying to be dismissive but I'm a bit busy and trying to be helpful)

**Comment by jvhgamer** [comment]
@StephenHodgson Candidly I don't find it very useful aside from being able to reference the source code. The video tutorials breeze through the code and cut/paste or un-comment pre-written code. Again I apologize if it seems like I am pestering, but I am viewing the documentation and still quite lost. I am going to go ahead and see if google can't turn up some helpful examples this time. But if you have a links to examples or could copy-paste examples here that implement a simple voice gesture. Example: if a user says "Scale" it will increase the size of currently selected object

**Comment by jvhgamer** [comment]
@StephenHodgson Is it possible to assign the response object and function at runtime? I have objects that are loaded/unloaded dynamically. I can add my custom script that contains the keywords to these objects at runtime no problem, but can I then fill in the editor fields at runtime too?

**Comment by jvhgamer** [comment]
@StephenHodgson Can I then fill in the Response editor fields at runtime for the object and the specific function in the KeyManager script component? [Link for visual of what I am attempting to describe](https://ibb.co/nrL4Zk) EDIT: Added link
