### ISSUE TITLE
Typo in PanelLayout scene name

### ISSUE THREAD

**Issue by atouchet** [Microsoft/HoloToolkit-Unity#823]
In HoloToolkit-Unity/Assets/HoloToolkit-Examples/Prototyping/Scenes/ PlanelLayout.unity and PlanelLayout.unity.meta should instead be named PanelLayout. I am not sure if the typo is referenced anywhere else in the project.

**Comment by killerantz** [comment]
I updated the file name and did a search to make sure it was not referenced anywhere else in the project. Thanks for catching that. PR #838
