### ISSUE TITLE
AnchorLoaded event in ImportExportAnchorManager

### ISSUE THREAD

**Issue by FlorianJa** [Microsoft/HoloToolkit-Unity#837]
Why is the AnchorLoaded Event in ImportExportAnchorManager class disabled for UnityEditor?

https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit-Tests/Sharing/Scripts/ImportExportAnchorManager.cs#L117

I can not build an app were i hook up on this event because unity throws an error because AnchorLoaded is  unknown.

Is this a bug or design decision?

**Comment by StephenHodgson** [comment]
Design decision because the editor does not initialize the `AnchorStore`.  This class will be depreciated by PR https://github.com/Microsoft/HoloToolkit-Unity/pull/742.

**Comment by StephenHodgson** [comment]
Also make sure your building for WSA.

**Comment by FlorianJa** [comment]
> Also make sure your building for WSA.

I am building for WSA.


> Design decision because the editor does not initialize the `AnchorStore`.

But how to use this event for example like this in anther class? 
`ImportExportAnchorManager.Instance.AnchorLoaded += Instance_AnchorLoaded;`

**Comment by FlorianJa** [comment]
i solved my problem by adding the same preprocessor directive
```
#if UNITY_WSA && !UNITY_EDITOR

ImportExportAnchorManager.Instance.AnchorLoaded += Instance_AnchorLoaded;

#endif
```
