### ISSUE TITLE
There's no way to configure where builds from the Build menu are output to.

### ISSUE THREAD

**Issue by jwittner** [Microsoft/HoloToolkit-Unity#84]
I've already run into issues where I've wanted the output build folder from BuildsCommands.BuildForHololens to differ from the hardcoded value. I'm thinking I'll add a new section to the preferences for the HoloToolkit and then we'll have a nice place to configure this and any other data that should be configurable.

**Comment by jwittner** [comment]
Looks like potentially the same upcoming PR for #49 will include a place where this directory might be specified. I'll leave this issue for a bit pending that PR.

**Comment by jwittner** [comment]
#87 Should resolve this.

**Comment by rgardler** [comment]
Indeed #89 has resolved this, can be closed in my opinion
