### ISSUE TITLE
Built in Transform menu available in Holotoolkit?

### ISSUE THREAD

**Issue by pampas93** [Microsoft/HoloToolkit-Unity#844]
When I select a 3D hologram; Is there a built in transform prefab that can be used to Edit the 3D gameObject (Move, scale or rotate)?

**Comment by FlorianJa** [comment]
Have a look at [MRDesignLabs](https://github.com/Microsoft/MRDesignLabs_Unity)

**Comment by pampas93** [comment]
Exactly what I was looking for. Thanks. @FlorianJa
