### ISSUE TITLE
BuildCommands.BuildForHololens is undiscoverable from the command line.

### ISSUE THREAD

**Issue by jwittner** [Microsoft/HoloToolkit-Unity#85]
Need to move the class out of the HoloToolkit namespace unfortunately. Is that a big concern for anyone?

**Comment by NeerajW** [comment]
It does break our existing paradigm of all classes in the HoloToolkit namespace. 
Do you see this class being access from other Unity MonoBehaviors?
Do you see this being replaced by some other work in the pipeline?

**Comment by jwittner** [comment]
I'm attempting to build an automated pipeline for our HoloLens projects via Visual Studio Team Services. Currently the only way to do this is to use a script method and the -executeMethod command line args. To do this the method must not be under a namespace or Unity won't find it. I'll look into #87 soon and see if it has code that can replace this - either way something will need to be outside a namespace to make it work via the command line.

**Comment by StephenHodgson** [comment]
@jwittner, this issue you're referring to?

**Comment by jwittner** [comment]
Yeah, this was the issue.
