### ISSUE TITLE
Separate background thread for PlaneFinding

### ISSUE THREAD

**Issue by yosun** [Microsoft/HoloToolkit-Unity#88]
Clarification on blurb from readme:

> NOTE: In the interest of simplicity, this test script calls the PlaneFinding APIs directly from the main Unity thread in Update(). In a real application, the PlaneFinding APIs MUST be called from a background thread in order to avoid stalling the rendering thread and causing a drop in frame rate.

Separate background thread - using something like Loom? Further clarification on background thread, please..

**Comment by jwittner** [comment]
I suspect you can get away with using System.Threading.ThreadPool: https://msdn.microsoft.com/en-us/library/mt679040.aspx

**Comment by angelaHillier** [comment]
The SurfaceMeshesToPlanes.cs uses the Task class to run in the background:

#if !UNITY_EDITOR
            Task<BoundedPlane[]> planeTask = Task.Run(() => PlaneFinding.FindPlanes(meshData, snapToGravityThreshold, MinArea));
        
            while (planeTask.IsCompleted == false)
            {
                yield return null;
            }

            BoundedPlane[] planes = planeTask.Result;
#else
